language: python

dist: bionic
python:
   - 3.8

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get -q update
   - sudo apt-get -y install gfortran-7
   - sudo apt-get install libopenmpi-dev openmpi-bin libhdf5-openmpi-dev
   - sudo apt-get -y install python3-pip
   - sudo apt-get -y install python3-setuptools
   - sudo apt-get install libfftw3-dev
   - python --version
   - git submodule update --init

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export OMPI_FC=gfortran-7
  - export OMPI_CC=gcc-7
  - ln -fs /usr/bin/mpifort "$HOME/.local/bin/mpifort" && mpifort --version
  - ln -fs /usr/bin/mpicc "$HOME/.local/bin/mpicc" && mpicc --version
  - ln -fs /usr/bin/gcov-7 "$HOME/.local/bin/gcov" && gcov --version
  - export FFTW3_ROOT="$HOME/fftw3" && mkdir $FFTW3_ROOT
  - mkdir $FFTW3_ROOT/include && cp /usr/include/fftw3* $FFTW3_ROOT/include
  - mkdir $FFTW3_ROOT/lib && cp /usr/lib/x86_64-linux-gnu/libfftw3* $FFTW3_ROOT/lib
  - sudo -H pip3 install --upgrade ford

script:
  - make tests -j
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)