add – dtFFT
add Subroutine
29 statements
Source File
private subroutine add(self, cuda_module, cuda_kernel, kernel_type, transpose_type, tile_size, padding, base_storage)
Adds new entry to cache
Type Bound
nvrtc_cache
Arguments
Type Intent Optional Attributes Name
class(nvrtc_cache), intent(inout) :: self
Cache instance
type(CUmodule), intent(in) :: cuda_module
Compiled CUDA module
type(CUfunction), intent(in) :: cuda_kernel
Extracted CUDA kernel
type(kernel_type_t), intent(in) :: kernel_type
Kernel type
type(dtfft_transpose_t), intent(in) :: transpose_type
Transpose type
integer(kind=int32), intent(in) :: tile_size
Tile size
integer(kind=int32), intent(in) :: padding
Padding
integer(kind=int64), intent(in) :: base_storage
Base storage
Calls
Called by
Call graph
add calls create, get_true_transpose_type
compile_and_cache calls add
get_kernel calls compile_and_cache, get_transpose_kernel
get_transpose_kernel calls compile_and_cache
create calls get_kernel, create