add_line – dtFFT
add_line Subroutine
6 statements
Source File
private subroutine add_line(self, line)
Adds new line to CUDA code
Type Bound
kernel_codegen
Arguments
Type Intent Optional Attributes Name
class(kernel_codegen), intent(inout) :: self
Kernel code
character(len=*), intent(in) :: line
Line to add
Called by
Call graph
get_code_init calls add_line
get_neighbor_function_code calls add_line
get_transpose_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_unpack_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_unpack_pipelined_kernel_code calls add_line, get_code_init
get_kernel calls get_unpack_kernel_code, get_unpack_pipelined_kernel_code, get_transpose_kernel
get_transpose_kernel calls get_transpose_kernel_code
create calls get_kernel, create