allocate_plans – dtFFT
allocate_plans Subroutine
27 statements
Source File
public subroutine allocate_plans(plans, backend, backends)
Uses
iso_fortran_env
Allocates array of plans
Arguments
Type Intent Optional Attributes Name
type(reshape_container), intent(inout) :: plans(:)
Plans to allocate
type(dtfft_backend_t), intent(in), optional :: backend
Backend to use
type(dtfft_backend_t), intent(in), optional :: backends(:)
Backends to use
Calls
Called by
Call graph
allocate_plans calls mpi_abort, write_message
write_message calls mpi_comm_rank, mpi_finalized
create_reshape_plans calls allocate_plans
create calls allocate_plans, run_autotune_backend, autotune_grid_decomposition, create_reshape_plans, autotune_reshape_plan
execute_many calls allocate_plans, execute_single
run_execute_single calls allocate_plans
autotune_adaptive calls create_reshape_plans
autotune_reshape_plan calls create_reshape_plans, autotune_adaptive
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid