alloc_mem – dtFFT
alloc_mem Subroutine
87 statements
Source File
private subroutine alloc_mem(platform, helper, backend, comm, alloc_bytes, ptr, error_code)
Uses
iso_fortran_env
iso_c_binding
Allocates memory based on backend
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
type(backend_helper), intent(inout) :: helper
Backend helper
type(dtfft_backend_t), intent(in) :: backend
GPU backend
type(MPI_Comm), intent(in) :: comm
MPI communicator
integer(kind=int64), intent(in) :: alloc_bytes
Number of bytes to allocate
type(c_ptr), intent(out) :: ptr
Pointer to the allocated memory
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Called by
Call graph
alloc_mem calls fname, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_abort, mpi_allreduce, cudageterrorstring, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, write_message, temp
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_conf_log_enabled calls get_conf_internal
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
alloc_and_set_aux calls alloc_mem
mem_alloc calls alloc_mem
run_autotune_backend calls alloc_mem, alloc_and_set_aux
autotune_grid calls run_autotune_backend
create calls alloc_and_set_aux, run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid