alloc_and_set_aux – dtFFT
alloc_and_set_aux Subroutine
30 statements
Source File
private subroutine alloc_and_set_aux(platform, helper, backend, cart_comm, aux, plans, is_aux_alloc)
Uses
iso_fortran_env
Allocates auxiliary memory according to the backend and sets it to the plans
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
type(backend_helper), intent(inout) :: helper
Backend helper
type(dtfft_backend_t), intent(in) :: backend
GPU backend
type(MPI_Comm), intent(in) :: cart_comm
Cartesian communicator
type(c_ptr), intent(inout) :: aux
Allocatable auxiliary memory
type(reshape_container), intent(in) :: plans(:)
logical :: is_aux_alloc
Is auxiliary memory allocated
Calls
Called by
Call graph
alloc_and_set_aux calls mpi_abort, mpi_allreduce, alloc_mem, dtfft_get_error_string, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls mpi_abort, mpi_allreduce, fname, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, cudageterrorstring, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, write_message, temp
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls get_backend, is_backend_nvshmem
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_conf_log_enabled calls get_conf_internal
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_autotune calls alloc_and_set_aux
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid