alloc_fft_plans – dtFFT
alloc_fft_plans Subroutine
41 statements
Source File
private subroutine alloc_fft_plans(self, kinds)
Allocates abstract_executor with required FFT class and populates fft_mapping with similar FFT ids
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(dtfft_r2r_kind_t), intent(in), optional :: kinds(:)
Kinds of R2R transform
Calls
Called by
Call graph
alloc_fft_plans calls counts
create_private calls alloc_fft_plans
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal