autotune_mpi_datatypes – dtFFT
autotune_mpi_datatypes Subroutine
24 statements
Source File
private subroutine autotune_mpi_datatypes(self, pencils, cart_comm, comms, base_dtype, base_storage, a, b, forward_ids, backward_ids, elapsed_time)
Type Bound
transpose_plan_host
Arguments
Type Intent Optional Attributes Name
class(transpose_plan_host), intent(in) :: self
Host plan
type(pencil), intent(in) :: pencils(:)
Array of pencils
type(MPI_Comm), intent(in) :: cart_comm
3D Cartesian comm
type(MPI_Comm), intent(in) :: comms(:)
Array of 1d communicators
type(MPI_Datatype), intent(in) :: base_dtype
Basic MPI Datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store Basic MPI Datatype
real(kind=real32), intent(inout) :: a(:)
Work buffer
real(kind=real32), intent(inout) :: b(:)
Work buffer
integer(kind=int8), intent(inout) :: forward_ids(:)
Forward plan IDs
integer(kind=int8), intent(inout) :: backward_ids(:)
Backward plan IDs
real(kind=real64), intent(out) :: elapsed_time
Elapsed time
Calls
Called by
Call graph
autotune_mpi_datatypes calls autotune_transpose_id
autotune_transpose_id calls get_plan_execution_time
get_plan_execution_time calls int_to_str, mpi_allreduce, mpi_comm_size, mpi_wtime, create, destroy, double_to_str, execute, get_iters_from_env, get_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
create calls mpi_comm_size, mpi_allgather, create_handle, create_transpose_2d, create_transpose_xy, create_transpose_xz, create_transpose_yz, create_transpose_zx, get_transpose_type
destroy calls mpi_request_free, destroy_handle
execute calls mpi_alltoall_init, mpi_alltoallw_init, mpi_start, mpi_wait
get_iters_from_env calls get_env
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
astring_f2c calls string_f2c
create_handle calls destroy_handle
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create_transpose_2d calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_xy calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_xz calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_yz calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_zx calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
destroy_handle calls mpi_type_free
free_datatypes calls mpi_type_free
get_env_int32 calls get_log_enabled, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_log_enabled, write_message, get_env
autotune_grid calls autotune_mpi_datatypes
autotune_grid_decomposition calls autotune_grid
create_private calls autotune_grid, autotune_grid_decomposition