autotune_adaptive – dtFFT
autotune_adaptive Function
27 statements
Source File
private function autotune_adaptive(platform, backend, base_comm, comms, base_init_dtype, base_init_storage, base_dtype, base_storage, bricks, pencils, stream, buffer_size, helper, plan_id) result(execution_time)
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for
type(dtfft_backend_t), intent(in) :: backend
type(MPI_Comm), intent(in) :: base_comm
3D Cartesian comm
type(MPI_Comm), intent(in) :: comms(:)
1D comms
type(MPI_Datatype), intent(in) :: base_init_dtype
Base MPI datatype for real space data
integer(kind=int64), intent(in) :: base_init_storage
Number of bytes needed to store single real element
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI datatype for Fourier space data
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single complex element
type(pencil), intent(in) :: bricks(:)
Pencils describing brick data distribution
type(pencil), intent(in) :: pencils(:)
Array of pencil decompositions
type(dtfft_stream_t), intent(in) :: stream
Stream to use
integer(kind=int64), intent(in) :: buffer_size
Size of the buffer to use during autotune (in bytes)
type(backend_helper), intent(inout) :: helper
integer(kind=int8), intent(in) :: plan_id
Return Value real(kind=real32)
Calls
Called by
Call graph
autotune_adaptive calls create_reshape_plans, destroy_plans, destroy_string, execute_autotune, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
create_reshape_plans calls write_message, mpi_abort, allocate_plans, create, get_conf_reshape
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls get_conf_log_enabled, write_message, fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_allreduce, dtfft_get_backend_string, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, temp
allocate_plans calls write_message, mpi_abort
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create calls write_message, mpi_abort, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, autotune_reshape_plan
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls get_conf_log_enabled, write_message, fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls get_conf_log_enabled, write_message, to_str, mpi_allreduce, mpi_comm_size
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
autotune_reshape_plan calls autotune_adaptive