autotune_grid_decomposition – dtFFT
autotune_grid_decomposition Subroutine
124 statements
Source File
private subroutine autotune_grid_decomposition(platform, dims, base_comm, effort, transpose_mode, base_dtype, base_storage, stream, fmodes, bmodes, best_decomposition, backend, min_execution_time, best_backend, best_transpose_mode, fbacks, bbacks)
Runs through all possible grid decompositions and selects the best one based on the lowest average execution time
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
Platform to use
integer(kind=int32), intent(in) :: dims(:)
Global sizes of the transform requested
type(MPI_Comm), intent(in) :: base_comm
3D comm
type(dtfft_effort_t), intent(in) :: effort
Effort level for the plan creation
type(dtfft_transpose_mode_t), intent(in) :: transpose_mode
Transpose mode to use
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI_Datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(dtfft_stream_t), intent(in) :: stream
Stream to use
type(dtfft_transpose_mode_t), intent(inout) :: fmodes(:)
Best transpose modes for forward plan
type(dtfft_transpose_mode_t), intent(inout) :: bmodes(:)
Best transpose modes for backward plan
integer(kind=int32), intent(out) :: best_decomposition(:)
Best decomposition found
type(dtfft_backend_t), intent(in), optional :: backend
GPU Backend to test. Should be passed only when effort is DTFFT_ESTIMATE or DTFFT_MEASURE
real(kind=real32), intent(out), optional :: min_execution_time
Elapsed time for best plan selected
type(dtfft_backend_t), intent(out), optional :: best_backend
Best backend selected
type(dtfft_transpose_mode_t), intent(out), optional :: best_transpose_mode
Best transpose mode selected
type(dtfft_backend_t), intent(out), optional :: fbacks(:)
Best backends for forward plans
type(dtfft_backend_t), intent(out), optional :: bbacks(:)
Best backends for backward plans
Calls
Called by
Call graph
autotune_grid_decomposition calls mpi_comm_size, mpi_dims_create, autotune_grid, get_conf_log_enabled, get_correct_backend, write_message
autotune_grid calls get_conf_log_enabled, write_message, to_str, mpi_comm_free, create_pencils_and_comm, destroy, get_permutations, pop_nvtx_domain_range, push_nvtx_domain_range, run_autotune_backend
get_conf_log_enabled calls get_conf_internal
get_correct_backend calls get_conf_platform
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create_pencils_and_comm calls get_permutations, create_cart_comm, create
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
run_autotune_backend calls get_correct_backend, lbmodes, lbtimes, lfmodes, lftimes, create_helper, destroy_helper, execute_many, execute_single, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_fused_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, get_conf_rma_enabled, get_conf_transpose, is_backend_compressed, is_backend_fused, is_backend_mpi, is_backend_nccl, is_backend_nvshmem, is_backend_pipelined, is_backend_rma
astring_f2c calls string_f2c
create_cart_comm calls write_message, to_str, mpi_comm_free, mpi_abort, mpi_cart_create, mpi_cart_sub, mpi_comm_dup, create_subcomm_include_all
create_helper calls mpi_comm_size, mpi_comm_rank, destroy_helper, fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, ncclgeterrorstring
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create calls mpi_comm_size, destroy, mpi_allgather, check_if_even, get_local_size, write_message, mpi_abort, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, autotune_grid_decomposition
destroy_helper calls write_message, fname, ncclcommdestroy, mpi_abort, ncclgeterrorstring
execute_many calls get_conf_log_enabled, write_message, to_str, pop_nvtx_domain_range, push_nvtx_domain_range, execute_single, btimes, ftimes, allocate_plans, create, destroy_plans, dtfft_get_backend_string, execute_autotune, get_local_sizes
execute_single calls get_conf_log_enabled, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, dtfft_get_backend_string, execute_single_transpose_modes
get_conf_compression_enabled calls get_conf_internal
get_conf_datatype_enabled calls get_conf_internal
get_conf_fused_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
allocate_plans calls write_message, mpi_abort
check_if_even calls mpi_comm_size, mpi_allgather
create_subcomm_include_all calls mpi_comm_size, create_subcomm
destroy_plans calls destroy
execute_autotune calls fname, mpi_abort, execute, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
execute_single_transpose_modes calls run_execute_single
get_local_size calls mpi_comm_size, mpi_comm_rank, mpi_allgather
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls get_conf_log_enabled, write_message, to_str, is_backend_nccl, is_backend_nvshmem, fname, mpi_abort, dtfft_get_backend_string, ncclgeterrorstring, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_allreduce, mem_alloc_host, temp
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
cudageterrorstring calls string_c2f, cudageterrorstring_c
free_mem calls get_conf_log_enabled, write_message, to_str, is_backend_nccl, is_backend_nvshmem, fname, mpi_abort, ncclgeterrorstring, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls write_message, get_env, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
report_timings calls mpi_comm_size, get_conf_log_enabled, write_message, to_str, mpi_allreduce
run_execute_single calls get_conf_log_enabled, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, allocate_plans, create, destroy_plans, execute_autotune
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc