autotune_reshape_plan – dtFFT
autotune_reshape_plan Subroutine
90 statements
Source File
private subroutine autotune_reshape_plan(platform, base_comm, comms, base_init_dtype, base_init_storage, base_dtype, base_storage, bricks, pencils, stream, buffer_size, transpose_backend, best_backend, backends)
Runs autotune for all backends
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for
type(MPI_Comm), intent(in) :: base_comm
3D Cartesian comm
type(MPI_Comm), intent(in) :: comms(:)
1D comms
type(MPI_Datatype), intent(in) :: base_init_dtype
Base MPI datatype for real space data
integer(kind=int64), intent(in) :: base_init_storage
Number of bytes needed to store single real element
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI datatype for Fourier space data
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single complex element
type(pencil), intent(in) :: bricks(:)
Pencils describing brick data distribution
type(pencil), intent(in) :: pencils(:)
Array of pencil decompositions
type(dtfft_stream_t), intent(in) :: stream
Stream to use
integer(kind=int64), intent(in) :: buffer_size
Size of the buffer to use during autotune (in bytes)
type(dtfft_backend_t), intent(in) :: transpose_backend
Backend used in transpose plans
type(dtfft_backend_t), intent(inout) :: best_backend
Best backend selected
type(dtfft_backend_t), intent(out) :: backends(11:14)
Forward backends
Calls
Called by
Call graph
autotune_reshape_plan calls autotune_adaptive, create_helper, create_reshape_plans, destroy_helper, destroy_plans, dtfft_get_backend_string, execute_autotune, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_fused_enabled, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, get_conf_reshape, get_conf_rma_enabled, is_backend_compatible, is_backend_compressed, is_backend_fused, is_backend_mpi, is_backend_nccl, is_backend_nvshmem, is_backend_pipelined, is_backend_rma, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
autotune_adaptive calls create_reshape_plans, destroy_plans, execute_autotune, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, destroy_string
create_helper calls destroy_helper, fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, mpi_comm_rank, mpi_comm_size, ncclgeterrorstring
create_reshape_plans calls get_conf_reshape, write_message, mpi_abort, allocate_plans, create
destroy_helper calls write_message, fname, ncclcommdestroy, mpi_abort, ncclgeterrorstring
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
get_conf_compression_enabled calls get_conf_internal
get_conf_datatype_enabled calls get_conf_internal
get_conf_fused_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
is_backend_compatible calls is_backend_mpi, is_backend_nccl, is_backend_nvshmem
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, write_message, fname, mpi_abort, cudageterrorstring, ncclgeterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_allreduce, mem_alloc_host, temp
allocate_plans calls write_message, mpi_abort
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create calls write_message, mpi_abort, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, autotune_reshape_plan
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, write_message, fname, mpi_abort, ncclgeterrorstring, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, nvshmem_free, is_same_ptr
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
report_timings calls get_conf_log_enabled, write_message, mpi_comm_size, to_str, mpi_allreduce
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_aux_bytes_generic calls get_aux_bytes
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls write_message, get_env, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr