autotune_grid – dtFFT
autotune_grid Subroutine
39 statements
Source File
private subroutine autotune_grid(dims, transposed_dims, base_comm, comm_dims, base_storage, is_z_slab, stream, backend, best_time, best_backend)
Creates cartesian grid and runs various backends on it. Can return best backend and execution time
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Global sizes of the transform requested
integer(kind=int32), intent(in) :: transposed_dims(:,:)
Transposed dimensions
type(MPI_Comm), intent(in) :: base_comm
Basic communicator to create 3d grid from
integer(kind=int32), intent(in) :: comm_dims(:)
Number of processors in each dimension
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
logical, intent(in) :: is_z_slab
Is Z-slab optimization enabled
type(dtfft_stream_t), intent(in) :: stream
Stream to use
type(dtfft_backend_t), intent(in), optional :: backend
GPU Backend to test. Should be passed only when effort is DTFFT_ESTIMATE or DTFFT_MEASURE
real(kind=real32), intent(out), optional :: best_time
Elapsed time for best plan selected
type(dtfft_backend_t), intent(out), optional :: best_backend
Best backend selected for the grid
Calls
Called by
Call graph
autotune_grid calls to_str, mpi_comm_free, create_pencils_and_comm, destroy, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, run_autotune_backend, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create_pencils_and_comm calls lcounts, lstarts, create, create_cart_comm
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
run_autotune_backend calls to_str, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_allreduce, mpi_barrier, mpi_comm_size, alloc_and_set_aux, alloc_mem, create_helper, cudageterrorstring, destroy, dtfft_get_backend_string, dtfft_get_error_string, execute, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, get_conf_mpi_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, get_local_sizes, is_backend_mpi, is_backend_nccl, is_backend_nvshmem, is_backend_pipelined
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
alloc_and_set_aux calls mpi_abort, mpi_allreduce, alloc_mem, dtfft_get_error_string, get_aux_size
alloc_mem calls to_str, get_conf_log_enabled, write_message, mpi_abort, mpi_allreduce, cudageterrorstring, dtfft_get_backend_string, is_backend_nccl, is_backend_nvshmem, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, ncclgeterrorstring, temp
astring_f2c calls string_f2c
create calls destroy, check_if_even, get_local_size
create_cart_comm calls mpi_cart_create, mpi_cart_sub, mpi_comm_dup
create_helper calls to_str, mpi_abort, mpi_comm_rank, mpi_comm_size, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_allgather, mpi_bcast, destroy_helper, ncclgeterrorstring
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy calls destroy, to_str, mpi_abort, cudageterrorstring, cudafree, remove
execute calls execute, to_str, cudastreamsynchronize, mpi_abort, cudageterrorstring, cudamemcpyasync, culaunchkernel, get_contiguous_execution_blocks
free_mem calls to_str, get_conf_log_enabled, write_message, mpi_abort, is_backend_nccl, is_backend_nvshmem, cudafree, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
check_if_even calls mpi_comm_size, mpi_allgather
destroy_helper calls to_str, write_message, mpi_abort, ncclgeterrorstring, ncclcommdestroy
get_aux_size calls get_aux_size
get_local_size calls mpi_comm_rank, mpi_comm_size, mpi_allgather
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
get_env_base calls destroy_string
get_env_int32 calls write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env
remove calls is_null_ptr, is_same_ptr
autotune_grid_decomposition calls autotune_grid
create_cuda calls autotune_grid_decomposition