autotune_transpose_id – dtFFT
autotune_transpose_id Function
30 statements
Source File
private function autotune_transpose_id(create_kwargs, buffer_size, helper, from, to, transpose_name_id, forward_id, backward_id) result(elapsed_time)
Creates forward and backward transpose plans for backend DTFFT_BACKEND_MPI_DATATYPE based on source and target data distributions and, executes them DTFFT_MEASURE_ITERS times (4 * DTFFT_MEASURE_ITERS iterations total) + 4 * DTFFT_MEASURE_WARMUP_ITERS warmup iterations
Returns elapsed time for best plans selected
Arguments
Type Intent Optional Attributes Name
type(create_args), intent(inout) :: create_kwargs
integer(kind=int64), intent(in) :: buffer_size
type(backend_helper), intent(inout) :: helper
Backend helper
type(pencil), intent(in) :: from
Source meta
type(pencil), intent(in) :: to
Target meta
integer(kind=int8), intent(in) :: transpose_name_id
ID of transpose name (from -3 to 3, except 0)
integer(kind=int8), intent(out) :: forward_id
Best forward plan ID
integer(kind=int8), intent(out) :: backward_id
Best backward plan ID
Return Value real(kind=real32)
Elapsed time for best plans selected
Calls
Called by
Call graph
autotune_transpose_id calls get_plan_execution_time
get_plan_execution_time calls to_str, allocate_plans, create, destroy_plans, execute_autotune, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create calls create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, run_autotune_backend, autotune_grid_decomposition
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic
alloc_mem calls to_str, get_conf_log_enabled, write_message, fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_allreduce, dtfft_get_backend_string, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, temp
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls to_str, get_conf_log_enabled, write_message, fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls to_str, get_conf_log_enabled, write_message, mpi_allreduce, mpi_comm_size
get_aux_bytes_generic calls get_aux_bytes
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
run_autotune_datatypes calls autotune_transpose_id
run_autotune_backend calls run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid