bytes_to_floats – dtFFT
bytes_to_floats Function
16 statements
Source File
private elemental function bytes_to_floats(bytes) result(floats)
Converts number of bytes to number of floats needed to store them
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: bytes
Number of bytes
Return Value integer(kind=int32)
Number of floats
Called by
Call graph
execute calls bytes_to_floats, execute
execute_end calls execute
execute_fused calls execute
execute_mpi calls execute, execute_fused
execute_nccl calls execute
execute_test calls execute
test_pack_unpack calls execute
test_transpose calls execute
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test