check_module – dtFFT
check_module Function
12 statements
Source File
private function check_module(self, ndims, kernel_type, base_storage)
Basic check that this module provides kernels of given type
Type Bound
nvrtc_module
Arguments
Type Intent Optional Attributes Name
class(nvrtc_module), intent(in) :: self
This module
integer(kind=int32), intent(in) :: ndims
Number of dimensions
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
Return Value logical
Called by
Call graph
check_instance calls check
create_nvrtc_module calls check
get calls check
get_kernel calls create_nvrtc_module, get_kernel_instance
get_kernel_instance calls get
create calls get_kernel