check_compression_config – dtFFT
check_compression_config Function
13 statements
Source File
public pure function check_compression_config(config) result(error_code)
Checks if the given compression configuration is valid
Arguments
Type Intent Optional Attributes Name
type(dtfft_compression_config_t), intent(in) :: config
Compression configuration to check
Return Value integer(kind=int32)
Calls
Called by
Call graph
check_compression_config calls is_valid_compression_lib, is_valid_compression_mode
init calls check_compression_config
create calls init