check_instance – dtFFT
check_instance Function
17 statements
Source File
private function check_instance(self, ndims, kernel_type, base_storage, tile_size, block_rows)
Checks if kernel with given parameters is available in this module
Type Bound
nvrtc_module
Arguments
Type Intent Optional Attributes Name
class(nvrtc_module), intent(in) :: self
This module
integer(kind=int32), intent(in) :: ndims
Number of dimensions
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
integer(kind=int32), intent(in) :: tile_size
Size of shared memory tile, template parameter
integer(kind=int32), intent(in) :: block_rows
Number of rows processed by single thread, template parameter
Return Value logical
Calls
Called by
Call graph
check_instance calls check
create_nvrtc_module calls check
get calls check
get_kernel calls create_nvrtc_module, get_kernel_instance
get_kernel_instance calls get
create calls get_kernel