check_create_args – dtFFT
check_create_args Function
116 statements
Source File
private function check_create_args(self, dims, pencil, comm, precision, effort, executor, kinds)
Uses
iso_fortran_env
Check arguments provided by user and sets private variables
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
integer(kind=int32), intent(in), optional :: dims(:)
Global dimensions of transform
type(dtfft_pencil_t), intent(in), optional :: pencil
Pencil of local portion of data
type(MPI_Comm), intent(in), optional :: comm
Optional MPI Communicator
type(dtfft_precision_t), intent(in), optional :: precision
Precision of transform: DTFFT_SINGLE or DTFFT_DOUBLE
type(dtfft_effort_t), intent(in), optional :: effort
Effort level for the plan creation
type(dtfft_executor_t), intent(in), optional :: executor
Type of External FFT Executor
type(dtfft_r2r_kind_t), intent(in), optional :: kinds(:)
Kinds of R2R transform
Return Value integer(kind=int32)
Calls
Called by
Call graph
check_create_args calls mpi_abort, mpi_topo_test, get_conf_backend, get_conf_platform, init_internal, is_backend_nccl, is_backend_nvshmem, is_cuda_executor, is_host_executor, is_valid_comm_type, is_valid_dimension, is_valid_effort, is_valid_executor, is_valid_precision, is_valid_r2r_kind, write_message
get_conf_backend calls get_correct_backend
init_internal calls mpi_initialized, init_environment
write_message calls mpi_comm_rank, mpi_finalized
get_correct_backend calls get_conf_platform
init_environment calls access_modes, destroy, get_env, platforms, destroy_strings, get_backend_from_env, transpose_modes
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_strings calls destroy_string
get_backend_from_env calls write_message, get_env, destroy_strings, destroy_string, is_valid_backend
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls mpi_abort, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
create_private calls check_create_args
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal