check_if_even – dtFFT
check_if_even Function
16 statements
Source File
private function check_if_even(count, comm)
Checks if data is evenly distributed across processes
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: count
Local count
type(MPI_Comm), intent(in) :: comm
Grid communicator
Return Value logical
Calls
Called by
Call graph
check_if_even calls mpi_allgather, mpi_comm_size
create calls check_if_even
create_pencils_and_comm calls create
create_r2c_internal calls create
autotune_grid calls create_pencils_and_comm
create_cuda calls create_pencils_and_comm, autotune_grid_decomposition
create_private calls create_pencils_and_comm, autotune_grid, autotune_grid_decomposition
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
autotune_grid_decomposition calls autotune_grid