check_aux – dtFFT
check_aux Subroutine
44 statements
Source File
private subroutine check_aux(self, aux, called_by, aux_ptr, aux2_ptr)
Uses
iso_fortran_env
Checks if aux buffer was passed by user and if not will allocate one internally
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: aux
Optional auxiliary buffer.
integer(kind=int32), intent(in) :: called_by
Indicates which function called check_aux for correct allocation
type(c_ptr), intent(out) :: aux_ptr
Auxiliary buffer pointer
type(c_ptr), intent(out) :: aux2_ptr
Second Auxiliary buffer pointer (used transpose/reshape operations)
Calls
Called by
Call graph
check_aux calls to_str, is_null_ptr, mpi_abort, dtfft_get_error_string, get_alloc_bytes, get_aux_bytes, get_conf_log_enabled, is_aux_needed, mem_alloc_ptr, ptr_offset, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_alloc_bytes calls dtfft_get_error_string, write_message, get_alloc_size, get_element_size
get_aux_bytes calls dtfft_get_error_string, write_message, get_aux_size, get_element_size, get_aux_bytes_generic
get_conf_log_enabled calls get_conf_internal
is_aux_needed calls get_aux_bytes
mem_alloc_ptr calls is_null_ptr, dtfft_get_error_string, write_message, mem_alloc, mem_alloc_host
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_alloc_size calls get_local_sizes
get_aux_size calls dtfft_get_error_string, is_aux_needed, write_message, get_alloc_size, get_aux_bytes, get_aux_size_reshape
get_element_size calls dtfft_get_error_string, write_message
mem_alloc_host calls aligned_alloc
get_aux_bytes_generic calls get_aux_bytes
get_aux_size_reshape calls dtfft_get_error_string, write_message, get_element_size, get_aux_bytes_reshape
get_local_sizes calls dtfft_get_error_string, write_message, get_aux_bytes, mpi_allreduce, get_backend, get_local_sizes, get_local_sizes_internal, is_backend_nvshmem
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_local_sizes_internal calls get_local_sizes, counts, starts
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr