check_device_pointers – dtFFT
check_device_pointers Function
17 statements
Source File
private function check_device_pointers(in, out, backend, aux) result(error_code)
Checks if device pointers are provided by user
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: in
First pointer
type(c_ptr), intent(in) :: out
Second pointer
type(dtfft_backend_t), intent(in) :: backend
Backend. Required to check for nvshmem pointer
type(c_ptr), intent(in) :: aux
Optional auxiliary pointer.
Return Value integer(kind=int32)
Calls
Called by
Call graph
check_device_pointers calls is_device_ptr, is_null_ptr, is_backend_nvshmem, is_nvshmem_ptr
is_nvshmem_ptr calls is_null_ptr, nvshmem_my_pe, nvshmem_ptr
execute_ptr calls check_device_pointers
transpose_ptr calls check_device_pointers
dtfft_execute_c calls execute_ptr
dtfft_transpose_c calls transpose_ptr
execute calls execute_ptr
transpose calls transpose_ptr