cleanup – dtFFT
cleanup Subroutine
34 statements
Source File
private subroutine cleanup(self)
Uses
iso_c_binding
iso_fortran_env
Removes unused modules from cuda context
Type Bound
nvrtc_cache
Arguments
Type Intent Optional Attributes Name
class(nvrtc_cache), intent(inout) :: self
Cache instance
Calls
Called by
Call graph
cleanup calls to_str, is_null_ptr, mpi_abort, cudageterrorstring, get_conf_log_enabled, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
destroy_cuda calls cleanup