clean_unused_cache – dtFFT
clean_unused_cache Subroutine
28 statements
Source File
public subroutine clean_unused_cache()
Uses
iso_fortran_env
iso_c_binding
Removes unused modules from cuda context
Arguments
None
Calls
Called by
Call graph
clean_unused_cache calls int_to_str, is_null_ptr, mpi_abort, cudageterrorstring
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c, string_c2f
create_cuda calls clean_unused_cache
destroy calls clean_unused_cache
dtfft_destroy_c calls destroy