compile_and_cache – dtFFT
compile_and_cache Function
207 statements
Source File
private function compile_and_cache(comm, dims, transpose_type, kernel_type, base_storage, tile_size, has_inner_loop) result(kernel)
Uses
dtfft_interface_cuda
iso_fortran_env
iso_c_binding
Compiles kernel and caches it. Returns compiled kernel.
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: comm
MPI Communicator
integer(kind=int32), intent(in), target :: dims(:)
Global dimensions to process
type(dtfft_transpose_type_t), intent(in) :: transpose_type
Type of transposition to perform
integer(kind=int8), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int8), intent(in) :: base_storage
Number of bytes needed to store single element
integer(kind=int32), intent(in) :: tile_size
Tile size
logical, intent(in) :: has_inner_loop
If kernel has inner loop
Return Value type(c_ptr)
Compiled kernel to return
Calls
Called by
Call graph
compile_and_cache calls cudagetdevice, cumodulegetfunction, cumoduleloaddataex, get_cuda_architecture, int_to_str, nvrtccompileprogram, nvrtccreateprogram, nvrtcdestroyprogram, nvrtcgetcubin, nvrtcgetcubinsize, nvrtcgetprogramlog, mpi_abort, mpi_allreduce, mpi_comm_rank, cudageterrorstring, destroy_code, get_cached_kernel, get_transpose_kernel_code, get_true_transpose_type, get_unpack_kernel_code, get_unpack_pipelined_kernel_code, nvrtcgeterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range, to_cstr
int_to_str calls int_to_str_int32, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c
get_cached_kernel calls get_true_transpose_type
get_transpose_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_unpack_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_unpack_pipelined_kernel_code calls add_line, get_code_init
nvrtcgeterrorstring calls nvrtcgeterrorstring_c
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
to_cstr calls astring_f2c
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_code_init calls int_to_str, add_line
get_neighbor_function_code calls add_line
create calls compile_and_cache, create