compress – dtFFT
compress Function
48 statements
Source File
private function compress(self, dims, displ, in, out, stream)
Uses
iso_fortran_env
Compresses the input data and returns the compressed size
Type Bound
abstract_compressor
Arguments
Type Intent Optional Attributes Name
class(abstract_compressor), intent(inout) :: self
Compressor instance
integer(kind=int32), intent(in) :: dims(:)
Array dimensions
integer(kind=int32), intent(in) :: displ
Displacement in arrays
type(c_ptr), intent(in) :: in
Pointer to uncompressed data
type(c_ptr), intent(in) :: out
Pointer to compressed buffer
type(dtfft_stream_t), intent(in) :: stream
Stream handle
Return Value integer(kind=int64)
Calls
Called by
Call graph
compress calls compress_private, to_str, mpi_abort, is_same_ptr, pop_nvtx_domain_range, ptr_offset, push_nvtx_domain_range, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute calls compress, execute
execute_end calls execute
execute_fused calls execute
execute_mpi calls execute, execute_fused
execute_nccl calls execute
execute_test calls execute
test_pack_unpack calls execute
test_transpose calls execute
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test