compile_program – dtFFT
compile_program Function
93 statements
Source File
private function compile_program(code, prog_name, configs, props) result(prog)
Uses
iso_fortran_env
iso_c_binding
Compiles nvRTC program with given configurations
Arguments
Type Intent Optional Attributes Name
type(codegen_t), intent(in) :: code
CUDA code to compile
character(len=*), intent(in) :: prog_name
Basic kernel name
type(kernel_config), intent(in) :: configs(:)
Kernel configurations that this module should be compiled for
type(device_props), intent(in) :: props
GPU architecture properties
Return Value type(nvrtcProgram)
Resulting nvRTC program
Calls
Called by
Call graph
compile_program calls fname, to_str, mpi_abort, astring_f2c, destroy_strings, mem_alloc_host, nvrtcgeterrorstring, set_name_expression, string_c2f, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
destroy_strings calls destroy_string
mem_alloc_host calls aligned_alloc
nvrtcgeterrorstring calls string_c2f
set_name_expression calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
get_name_expression calls to_str, astring_f2c
create calls compile_program, get_kernel
create_nvrtc_module calls create
get_kernel calls create_nvrtc_module