convert_pointer – dtFFT
convert_pointer Function
6 statements
Source File
private function convert_pointer(in, size) result(out)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: in
integer(kind=int64), intent(in) :: size
Return Value real(kind=real32), pointer, (:)
Called by
Call graph
alloc_and_set_aux calls convert_pointer
execute_cuda calls convert_pointer
run_autotune_backend calls convert_pointer, alloc_and_set_aux
autotune_grid calls run_autotune_backend
create_cuda calls alloc_and_set_aux, run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid