count_bank_conflicts – dtFFT
count_bank_conflicts Function
62 statements
Source File
public pure function count_bank_conflicts(tile_size, block_rows, base_storage, padding) result(total_conflicts)
Counts bank conflicts for a given tile size, padding, element size, and block rows.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: tile_size
Size of the tile
integer(kind=int32), intent(in) :: block_rows
Number of rows in the block
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
integer(kind=int32), intent(in) :: padding
Padding added to the tile
Return Value integer(kind=int32)
Total number of bank conflicts
Called by
Call graph
estimate_bank_conflict_ratio calls count_bank_conflicts
estimate_optimal_padding calls count_bank_conflicts
evaluate_analytical_performance calls count_bank_conflicts, estimate_bank_conflict_ratio
generate_candidates calls estimate_optimal_padding
get_kernel calls evaluate_analytical_performance, generate_candidates
create calls get_kernel, create