create_helper – dtFFT
create_helper Subroutine
75 statements
Source File
private subroutine create_helper(self, platform, base_comm, comms, is_nccl_needed, pencils)
Uses
iso_fortran_env
iso_c_binding
Creates helper
Type Bound
backend_helper
Arguments
Type Intent Optional Attributes Name
class(backend_helper), intent(inout) :: self
Backend helper
type(dtfft_platform_t), intent(in) :: platform
Platform to use
type(MPI_Comm), intent(in) :: base_comm
MPI communicator
type(MPI_Comm), intent(in) :: comms(:)
1D Communicators
logical, intent(in) :: is_nccl_needed
If nccl communicator will be needed
type(pencil), intent(in), target :: pencils(:)
Pencils
Calls
Called by
Call graph
create_helper calls fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, mpi_comm_rank, mpi_comm_size, destroy_helper, ncclgeterrorstring
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_helper calls fname, mpi_abort, ncclgeterrorstring, ncclcommdestroy, write_message
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls get_env, mpi_abort, write_message
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, write_message, destroy_string
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
autotune_reshape_plan calls create_helper
create calls create_helper, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
run_autotune_backend calls create_helper
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid