create_1d_comm – dtFFT
create_1d_comm Subroutine
38 statements
Source File
private subroutine create_1d_comm(lbounds, all_lbounds, fixed_dims, comm, new_comm, all_counts)
Creates a new 1D communicator based on the fixed dimensions of the current pencil
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: lbounds(:)
Local starts of the current pencil
integer(kind=int32), intent(in) :: all_lbounds(:,:)
Local starts of all processes
integer(kind=int32), intent(in) :: fixed_dims(:)
Indices of fixed coordinates
type(MPI_Comm), intent(in) :: comm
Original MPI communicator
type(MPI_Comm), intent(out) :: new_comm
New 1D MPI communicator
integer(kind=int32), intent(in) :: all_counts(:,:)
Calls
Called by
Call graph
create_1d_comm calls mpi_comm_rank, mpi_comm_size, create_subcomm, get_varying_dim, sort_by_varying_dim
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
create_pencil_init calls create_1d_comm