create – dtFFT
create Subroutine
135 statements
Source File
private subroutine create(self, comm, send, recv, kwargs)
Creates reshape_handle_datatype class
Type Bound
reshape_handle_datatype
Arguments
Type Intent Optional Attributes Name
class(reshape_handle_datatype), intent(inout) :: self
Reshape handle
type(MPI_Comm), intent(in) :: comm
MPI Communicator
type(pencil), intent(in) :: send
Send pencil
type(pencil), intent(in) :: recv
Recv pencil
type(create_args), intent(in) :: kwargs
Additional arguments
Calls
Call graph
create calls mpi_allgather, mpi_comm_size, create_back_permutation, create_forw_permutation, create_handle, create_reshape_12, create_reshape_21, create_reshape_23, create_reshape_32, create_transpose_2d, create_transpose_xz, create_transpose_zx, destroy, get_float_buffer_size
create_back_permutation calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_forw_permutation calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_handle calls destroy_handle
create_reshape_12 calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_reshape_21 calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_reshape_23 calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_indexed_block, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_reshape_32 calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_indexed_block, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_2d calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_xz calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_zx calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
destroy calls mpi_request_free, destroy_handle
get_float_buffer_size calls get_local_sizes
destroy_handle calls mpi_type_free
free_datatypes calls mpi_type_free