create_pencil_init – dtFFT
create_pencil_init Function
164 statements
Source File
private function create_pencil_init(self, pencil, comm) result(error_code)
Uses
iso_fortran_env
Creates and validates pencil passed by user to plan constructors
Type Bound
pencil_init
Arguments
Type Intent Optional Attributes Name
class(pencil_init), intent(inout) :: self
Internal pencil representation based on dtfft_pencil_t
type(dtfft_pencil_t), intent(in) :: pencil
Pencil passed by user to plan constructors
type(MPI_Comm), intent(in) :: comm
MPI Communicator passed to plan constructors
Return Value integer(kind=int32)
Error code
Calls
Call graph
create_pencil_init calls to_str, mpi_abort, mpi_allgather, mpi_allreduce, mpi_comm_rank, mpi_comm_size, check_continuity, check_overlap, create_1d_comm, dtfft_get_error_string, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create_1d_comm calls mpi_comm_rank, mpi_comm_size, create_subcomm, get_varying_dim, sort_by_varying_dim
write_message calls mpi_comm_rank, mpi_finalized
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl