create – dtFFT
create Subroutine
92 statements
Source File
private subroutine create(self, ndims, kernel_type, base_storage, configs, props)
Uses
iso_fortran_env
iso_c_binding
Creates module with given parameters, compiles nvRTC program and loads it as CUDA module
Type Bound
nvrtc_module
Arguments
Type Intent Optional Attributes Name
class(nvrtc_module), intent(inout) :: self
This module
integer(kind=int32), intent(in) :: ndims
Number of dimensions, used only for forward permutation
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(kernel_config), intent(in) :: configs(:)
Kernel configurations that this module should be compiled for
type(device_props), intent(in) :: props
GPU architecture properties
Calls
Called by
Call graph
create calls fname, mem_free_host, mpi_abort, compile_program, cudageterrorstring, destroy, get_code, get_conf_log_enabled, mem_alloc_host, nvrtcgeterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, get_kernel
compile_program calls fname, mpi_abort, mem_alloc_host, nvrtcgeterrorstring, to_str, astring_f2c, destroy_strings, set_name_expression, string_c2f
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy calls fname, mpi_abort, cudageterrorstring, nvrtcgeterrorstring, is_null_ptr
get_code calls add_line, is_unpack_kernel
get_conf_log_enabled calls get_conf_internal
mem_alloc_host calls aligned_alloc
nvrtcgeterrorstring calls string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
destroy_strings calls destroy_string
set_name_expression calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
get_name_expression calls to_str, astring_f2c
create_nvrtc_module calls create
get_kernel calls create_nvrtc_module