create_subcomm – dtFFT
create_subcomm Subroutine
12 statements
Source File
public subroutine create_subcomm(old_comm, processes, new_comm)
Creates communicator with selected processes from old_comm
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: old_comm
Communicator to create group from
integer(kind=int32), intent(in) :: processes(:)
Ranks of processes in old_comm to include in new group
type(MPI_Comm), intent(out) :: new_comm
New communicator
Calls
Called by
Call graph
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
create_1d_comm calls create_subcomm
create_subcomm_include_all calls create_subcomm
create_cart_comm calls create_subcomm_include_all
create_pencil_init calls create_1d_comm
create_pencils_and_comm calls create_cart_comm
autotune_grid calls create_pencils_and_comm
create calls create_pencils_and_comm, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid