create – dtFFT
create Function
80 statements
Source File
private function create(self, config, platform, base_type)
Uses
iso_c_binding
iso_fortran_env
Initializes the ZFP compressor with given configuration
Type Bound
compressor_zfp
Arguments
Type Intent Optional Attributes Name
class(compressor_zfp), intent(inout) :: self
Compressor instance
type(dtfft_compression_config_t), intent(in) :: config
Compression settings
type(dtfft_platform_t), intent(in) :: platform
Target platform (CPU or CUDA)
type(MPI_Datatype), intent(in) :: base_type
MPI data type
Return Value integer(kind=int32)
Calls
Call graph
create calls fname, cudaeventcreatewithflags, mpi_abort, cudageterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr