create_subcomm_include_all – dtFFT
create_subcomm_include_all Subroutine
13 statements
Source File
public subroutine create_subcomm_include_all(old_comm, new_comm)
Creates communicator including all processes from old_comm
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: old_comm
Communicator to create group from
type(MPI_Comm), intent(out) :: new_comm
New communicator
Calls
Called by
Call graph
create_subcomm_include_all calls mpi_comm_size, create_subcomm
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
create_cart_comm calls create_subcomm_include_all
create_pencils_and_comm calls create_cart_comm
autotune_grid calls create_pencils_and_comm
create calls create_pencils_and_comm, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid