create – dtFFT
create Function
272 statements
Source File
private function create(self, platform, dims, base_comm, effort, base_dtype, base_storage, cart_comm, comms, pencils, ipencil) result(error_code)
Creates transposition plan
Type Bound
transpose_plan
Arguments
Type Intent Optional Attributes Name
class(transpose_plan), intent(inout) :: self
Transposition class
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for
integer(kind=int32), intent(in) :: dims(:)
Global sizes of the transform requested
type(MPI_Comm), intent(in) :: base_comm
Base communicator
type(dtfft_effort_t), intent(in) :: effort
dtFFT planner type of effort
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI_Datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(MPI_Comm), intent(out) :: cart_comm
Cartesian communicator
type(MPI_Comm), intent(out) :: comms(:)
Array of 1d communicators
type(pencil), intent(out) :: pencils(:)
Data distributing meta
type(pencil_init), intent(in), optional :: ipencil
Pencil passed by user
Return Value integer(kind=int32)
Error code
Calls
Call graph
create calls backs, to_str, mpi_cart_get, mpi_cartdim_get, mpi_comm_size, mpi_dims_create, mpi_topo_test, mpi_wtime, allocate_plans, autotune_grid_decomposition, create_helper, create_pencils_and_comm, dtfft_get_backend_string, get_conf_backend, get_conf_log_enabled, get_conf_transpose, get_conf_transpose_mode, get_conf_y_slab_enabled, get_conf_z_slab_enabled, get_local_sizes, init, is_backend_nccl, pop_nvtx_domain_range, push_nvtx_domain_range, run_autotune_backend, write_message, temp_coords, temp_dims, temp_periods, mpi_allgather, check_if_even, destroy, get_local_size, mpi_abort, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
allocate_plans calls write_message, mpi_abort
autotune_grid_decomposition calls mpi_comm_size, mpi_dims_create, get_conf_log_enabled, write_message, autotune_grid, get_correct_backend
create_helper calls mpi_comm_size, fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, mpi_comm_rank, destroy_helper, ncclgeterrorstring
create_pencils_and_comm calls create, create_cart_comm, get_permutations
get_conf_backend calls get_correct_backend
get_conf_log_enabled calls get_conf_internal
get_conf_y_slab_enabled calls get_conf_internal
get_conf_z_slab_enabled calls get_conf_internal
init calls is_backend_nccl, write_message, create, destroy, mpi_abort, check_compression_config, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_stream, is_backend_compressed, is_backend_nvshmem, load_cuda, load_nvrtc
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
run_autotune_backend calls create_helper, get_conf_transpose, is_backend_nccl, lbmodes, lbtimes, lfmodes, lftimes, destroy_helper, execute_many, execute_single, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_fused_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, get_conf_rma_enabled, get_correct_backend, is_backend_compressed, is_backend_fused, is_backend_mpi, is_backend_nvshmem, is_backend_pipelined, is_backend_rma
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
astring_f2c calls string_f2c
autotune_grid calls to_str, create_pencils_and_comm, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, run_autotune_backend, write_message, get_permutations, mpi_comm_free, destroy
check_compression_config calls is_valid_compression_lib, is_valid_compression_mode
create_cart_comm calls to_str, write_message, mpi_abort, mpi_cart_create, mpi_cart_sub, mpi_comm_dup, mpi_comm_free, create_subcomm_include_all
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
destroy_helper calls write_message, fname, mpi_abort, ncclgeterrorstring, ncclcommdestroy
execute_many calls to_str, allocate_plans, dtfft_get_backend_string, get_conf_log_enabled, get_local_sizes, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, execute_single, btimes, ftimes, create, destroy_plans, execute_autotune
execute_single calls dtfft_get_backend_string, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, execute_single_transpose_modes
get_conf_compression_enabled calls get_conf_internal
get_conf_datatype_enabled calls get_conf_internal
get_conf_fused_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_conf_stream calls fname, mpi_abort, cudastreamcreate, cudageterrorstring
get_correct_backend calls get_conf_platform
load_cuda calls destroy_strings, dynamic_load
load_nvrtc calls destroy_strings, dynamic_load
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
check_if_even calls mpi_comm_size, mpi_allgather
create_subcomm_include_all calls mpi_comm_size, create_subcomm
cudageterrorstring calls string_c2f, cudageterrorstring_c
destroy_plans calls destroy
destroy_strings calls destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
execute_autotune calls mpi_wtime, fname, mpi_abort, cudageterrorstring, execute, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_barrier, alloc_and_set_aux, alloc_mem, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
execute_single_transpose_modes calls run_execute_single
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls write_message, get_env, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
get_local_size calls mpi_comm_size, mpi_allgather, mpi_comm_rank
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls to_str, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, write_message, fname, mpi_abort, is_backend_nvshmem, ncclgeterrorstring, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_allreduce, mem_alloc_host, temp
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
free_mem calls to_str, get_conf_log_enabled, is_backend_nccl, write_message, fname, mpi_abort, is_backend_nvshmem, ncclgeterrorstring, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
load_library calls astring_f2c, is_null_ptr, dlopen, dl_error
load_symbol calls write_message, mpi_abort, astring_f2c, is_null_ptr, dlsym, dl_error
report_timings calls to_str, mpi_comm_size, get_conf_log_enabled, write_message, mpi_allreduce
run_execute_single calls allocate_plans, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, create, destroy_plans, execute_autotune
unload_library calls dlclose, dl_error
dl_error calls write_message, string_c2f, dlerror
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc