create_device_pointer – dtFFT
create_device_pointer Subroutine
26 statements
Source File
private subroutine create_device_pointer(ptr, values)
Uses
iso_fortran_env
iso_c_binding
Allocates memory on a device and copies values to it.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(inout) :: ptr
Device pointer
integer(kind=c_int), intent(in), target :: values(:)
Values to copy
Calls
Called by
Call graph
create_device_pointer calls cudamalloc, cudamemcpy, int_to_str, mpi_abort, cudageterrorstring
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c, string_c2f
create calls create_device_pointer, create