create_transpose_XY – dtFFT
create_transpose_XY Subroutine
50 statements
Source File
private subroutine create_transpose_XY(self, n_neighbors, i, send, send_counts, recv, recv_counts, datatype_id, base_type, base_storage)
Creates three-dimensional X –> Y, Y –> X transposition datatypes
Type Bound
transpose_handle_host
Arguments
Type Intent Optional Attributes Name
class(transpose_handle_host), intent(inout) :: self
Transposition class
integer(kind=int32), intent(in) :: n_neighbors
Size of 1d comm
integer(kind=int32), intent(in) :: i
Counter
class(pencil), intent(in) :: send
Information about send buffer
integer(kind=int32), intent(in) :: send_counts(:)
Rank i is sending this counts
class(pencil), intent(in) :: recv
Information about send buffer
integer(kind=int32), intent(in) :: recv_counts(:)
Rank i is recieving this counts
integer(kind=int8), intent(in) :: datatype_id
Id of transpose plan to use
type(MPI_Datatype), intent(in) :: base_type
Base MPI_Datatype
integer(kind=int8), intent(in) :: base_storage
Number of bytes needed to store single element
Calls
Called by
Call graph
create_transpose_xy calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
free_datatypes calls mpi_type_free
create calls create_transpose_xy
get_plan_execution_time calls create
autotune_grid calls get_plan_execution_time, autotune_mpi_datatypes
autotune_transpose_id calls get_plan_execution_time
autotune_grid_decomposition calls autotune_grid
autotune_mpi_datatypes calls autotune_transpose_id
create_private calls autotune_grid, autotune_grid_decomposition