create_reshape_plans – dtFFT
create_reshape_plans Subroutine
79 statements
Source File
private subroutine create_reshape_plans(plans, backend, platform, helper, effort, force_effort, base_init_dtype, base_init_storage, base_dtype, base_storage, bricks, pencils, backends, plan_id)
Uses
iso_fortran_env
Creates and allocates all reshape operation plans
This subroutine allocates and initializes plans for all four reshape operations: - X_BRICKS_TO_PENCILS: brick to pencil in X dimension (real space) - X_PENCILS_TO_BRICKS: pencil to brick in X dimension (real space) - Z_PENCILS_TO_BRICKS: pencil to brick in Z dimension (Fourier space) - Z_BRICKS_TO_PENCILS: brick to pencil in Z dimension (Fourier space)
Arguments
Type Intent Optional Attributes Name
type(reshape_container), intent(inout), allocatable :: plans(:)
Array of reshape plan containers to be allocated and initialized
type(dtfft_backend_t), intent(in) :: backend
Communication backend to use for reshape operations
type(dtfft_platform_t), intent(in) :: platform
Execution platform (HOST or CUDA)
type(backend_helper), intent(inout) :: helper
Backend helper for communication setup
type(dtfft_effort_t), intent(in) :: effort
dtFFT planner effort level
logical, intent(in) :: force_effort
type(MPI_Datatype), intent(in) :: base_init_dtype
Base MPI datatype for real space data
integer(kind=int64), intent(in) :: base_init_storage
Number of bytes needed to store single real element
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI datatype for Fourier space data
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single complex element
type(pencil), intent(in), target :: bricks(:)
Pencils describing brick data distribution
type(pencil), intent(in), target :: pencils(:)
Array of pencil decompositions
type(dtfft_backend_t), intent(in), optional :: backends(11:14)
Adaptive backends
integer(kind=int32), intent(in), optional :: plan_id
Single plan id to create
Calls
Called by
Call graph
create_reshape_plans calls mpi_abort, allocate_plans, create, get_conf_reshape, write_message
allocate_plans calls mpi_abort, write_message
create calls mpi_abort, write_message, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, create_reshape_plans, autotune_reshape_plan
write_message calls mpi_comm_rank, mpi_finalized
autotune_adaptive calls create_reshape_plans
autotune_reshape_plan calls create_reshape_plans, autotune_adaptive