create – dtFFT
create Subroutine
37 statements
Source File
private subroutine create(self, effort, base_storage, force_effort)
Uses
iso_fortran_env
iso_c_binding
Creates kernel
Type Bound
kernel_device
Arguments
Type Intent Optional Attributes Name
class(kernel_device), intent(inout) :: self
Device kernel class
type(dtfft_effort_t), intent(in) :: effort
Effort level for generating transpose kernels
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
logical, intent(in), optional :: force_effort
Should effort be forced or not
Calls
Call graph
create calls fname, cudagetdevice, get_device_props, mpi_abort, cudageterrorstring, destroy, get_kernel, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, mem_free_host, compile_program, get_code, mem_alloc_host, nvrtcgeterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy calls destroy_private, fname, mpi_abort, cudageterrorstring, is_null_ptr, nvrtcgeterrorstring
get_kernel calls fname, mpi_abort, cudageterrorstring, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudafree, cudamalloc, cudastreamsynchronize, to_str, create_nvrtc_module, culaunchkernel, evaluate_analytical_performance, generate_candidates, get_conf_configs_to_test, get_conf_forced_kernel_optimization, get_conf_kernel_optimization_enabled, get_conf_log_enabled, get_conf_measure_iters, get_conf_measure_warmup_iters, get_conf_stream, get_kernel_args, get_kernel_instance, get_kernel_launch_params, get_kernel_string, is_unpack_kernel, pop_nvtx_domain_range, push_nvtx_domain_range, sort_candidates_by_score, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create_nvrtc_module calls to_str, get_conf_log_enabled, get_kernel_string, write_message, check, add, create
evaluate_analytical_performance calls count_bank_conflicts, estimate_bank_conflict_ratio, estimate_coalescing, estimate_occupancy
generate_candidates calls estimate_memory_pressure, estimate_optimal_padding, find_valid_combination
get_conf_configs_to_test calls get_conf_internal
get_conf_forced_kernel_optimization calls get_conf_internal
get_conf_kernel_optimization_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_stream calls fname, mpi_abort, cudageterrorstring, cudastreamcreate
get_kernel_instance calls to_str, get_conf_log_enabled, get_kernel_string, write_message, is_null_ptr, get
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
is_null_ptr calls is_null_ptr, is_null_funptr
add calls to_str, get_conf_log_enabled, write_message, create
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
estimate_bank_conflict_ratio calls count_bank_conflicts
estimate_optimal_padding calls count_bank_conflicts
get calls fname, mpi_abort, cudageterrorstring, check, get_mangled_name
check_instance calls check
compile_program calls fname, mpi_abort, to_str, string_c2f, astring_f2c, mem_alloc_host, nvrtcgeterrorstring, destroy_strings, set_name_expression
get_code calls is_unpack_kernel, add_line
get_mangled_name calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression
mem_alloc_host calls aligned_alloc
nvrtcgeterrorstring calls string_c2f
destroy_strings calls destroy_string
get_name_expression calls to_str, astring_f2c
set_name_expression calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression