create – dtFFT
create Subroutine
73 statements
Source File
private subroutine create(self, dims, effort, base_storage, kernel_type, neighbor_data, force_effort, with_compression, with_decompression)
Uses
iso_fortran_env
Creates kernel
Type Bound
abstract_kernel
Arguments
Type Intent Optional Attributes Name
class(abstract_kernel), intent(inout) :: self
Abstract kernel
integer(kind=int32), intent(in) :: dims(:)
Local dimensions to process
type(dtfft_effort_t), intent(in) :: effort
Effort level for generating transpose kernels
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int32), intent(in), optional :: neighbor_data(:,:)
Optional pointers for unpack kernels
logical, intent(in), optional :: force_effort
Should effort be forced or not
logical, intent(in), optional :: with_compression
Enable compression after executing kernel
logical, intent(in), optional :: with_decompression
Enable decompression before executing kernel
Calls
Called by
Call graph
create calls create_private, mpi_abort, destroy, get_kernel_string, is_pack_kernel, is_unpack_kernel, write_message, create
destroy calls destroy_private, destroy_string
write_message calls mpi_comm_rank, mpi_finalized
execute_test calls create
test_device_kernels calls execute_test