create_handle – dtFFT
create_handle Subroutine
8 statements
Source File
private subroutine create_handle(self, n)
Creates reshape handle
Type Bound
handle_t
Arguments
Type Intent Optional Attributes Name
class(handle_t), intent(inout) :: self
Reshape handle
integer(kind=int32), intent(in) :: n
Number of datatypes to be created
Calls
Called by
Call graph
create_handle calls destroy_handle
destroy_handle calls mpi_type_free
create calls create_handle