create_cart_comm – dtFFT
create_cart_comm Subroutine
55 statements
Source File
private subroutine create_cart_comm(old_comm, comm_dims, comm, local_comms, ipencil)
Uses
iso_fortran_env
Creates cartesian communicator
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: old_comm
Communicator to create cartesian from
integer(kind=int32), intent(in) :: comm_dims(:)
Dims in cartesian communicator
type(MPI_Comm), intent(out) :: comm
Cartesian communicator
type(MPI_Comm), intent(out) :: local_comms(:)
1d communicators in cartesian communicator
type(pencil_init), intent(in), optional :: ipencil
Pencil passed by user
Calls
Called by
Call graph
create_cart_comm calls to_str, mpi_abort, mpi_cart_create, mpi_cart_sub, mpi_comm_dup, mpi_comm_free, create_subcomm_include_all, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create_subcomm_include_all calls mpi_comm_size, create_subcomm
write_message calls mpi_comm_rank, mpi_finalized
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
create_pencils_and_comm calls create_cart_comm
autotune_grid calls create_pencils_and_comm
create calls create_pencils_and_comm, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid