create – dtFFT
create Subroutine
114 statements
Source File
private subroutine create(self, comm, dims, base_storage, transpose_type, kernel_type, pointers)
Creates kernel
Type Bound
nvrtc_kernel
Arguments
Type Intent Optional Attributes Name
class(nvrtc_kernel), intent(inout) :: self
nvRTC Compiled kernel class
type(MPI_Comm), intent(in) :: comm
MPI Communicator
integer(kind=int32), intent(in), target :: dims(0:)
Global dimensions to process
integer(kind=int8), intent(in) :: base_storage
Number of bytes needed to store single element
type(dtfft_transpose_type_t), intent(in) :: transpose_type
Type of transposition to perform
integer(kind=int8), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int32), intent(in), optional :: pointers(:,:)
Optional pointers to unpack kernels
Calls
Called by
Call graph
create calls mpi_comm_rank, mpi_comm_size, compile_and_cache, create_device_pointer, destroy, get_contiguous_execution_blocks, get_tile_size, create
compile_and_cache calls mpi_comm_rank, cudagetdevice, cumoduleloaddataex, get_cuda_architecture, cumodulegetfunction, int_to_str, mpi_abort, mpi_allreduce, nvrtccompileprogram, nvrtccreateprogram, nvrtcdestroyprogram, nvrtcgetcubin, nvrtcgetcubinsize, nvrtcgetprogramlog, astring_f2c, cudageterrorstring, destroy_code, get_cached_kernel, get_transpose_kernel_code, get_true_transpose_type, get_unpack_kernel_code, get_unpack_pipelined_kernel_code, nvrtcgeterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range, to_cstr
create_device_pointer calls cudamalloc, cudamemcpy, int_to_str, mpi_abort, cudageterrorstring
destroy calls cudafree, int_to_str, mpi_abort, cudageterrorstring, mark_unused
int_to_str calls int_to_str_int32, int_to_str_int8
astring_f2c calls string_f2c
get_cached_kernel calls get_true_transpose_type
get_transpose_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_unpack_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_unpack_pipelined_kernel_code calls add_line, get_code_init
push_nvtx_domain_range calls astring_f2c, create_nvtx_domain
to_cstr calls astring_f2c
create_nvtx_domain calls astring_f2c
get_code_init calls int_to_str, add_line
get_neighbor_function_code calls add_line