create_custom_comm – dtFFT
create_custom_comm Subroutine
17 statements
Source File
private subroutine create_custom_comm(old_comm, new_size, group_type, new_comm)
Creates custom MPI communicator by splitting processes into groups
This subroutine divides processes from an existing communicator into groups based on the specified group type: neighbor groups or strided groups.
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: old_comm
Original MPI communicator to split
integer(kind=int32), intent(in) :: new_size
Size of each group in the new communicator
integer(kind=int32), intent(in) :: group_type
Type of grouping: NEIGHBOR_GROUP (consecutive ranks) or STRIDED_GROUP (interleaved ranks)
type(MPI_Comm), intent(out) :: new_comm
Newly created MPI communicator
Calls
Called by
Call graph
create_custom_comm calls mpi_comm_rank, mpi_comm_size, mpi_comm_split
create calls create_custom_comm