create_nvrtc_module – dtFFT
create_nvrtc_module Subroutine
53 statements
Source File
public subroutine create_nvrtc_module(ndims, kernel_type, base_storage, configs, props)
Creates and adds a new nvrtc module to the cache if it does not already exist
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: ndims
Number of dimensions (2 or 3)
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(kernel_config), intent(in) :: configs(:)
Array of kernel configurations to build
type(device_props), intent(in) :: props
GPU architecture properties
Calls
Called by
Call graph
create_nvrtc_module calls to_str, check, add, create, destroy_string, get_conf_log_enabled, get_kernel_string, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
add calls to_str, get_conf_log_enabled, write_message, create
create calls get_conf_log_enabled, get_kernel_string, write_message, fname, mem_free_host, mpi_abort, compile_program, cudageterrorstring, destroy, get_code, mem_alloc_host, nvrtcgeterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range, get_kernel
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
check_instance calls check
compile_program calls to_str, write_message, fname, mpi_abort, mem_alloc_host, nvrtcgeterrorstring, astring_f2c, destroy_strings, set_name_expression, string_c2f
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy calls destroy_string, write_message, fname, mpi_abort, cudageterrorstring, nvrtcgeterrorstring, is_null_ptr
get_code calls write_message, mpi_abort, add_line, is_pack_kernel, is_transpose_kernel, is_unpack_kernel
mem_alloc_host calls aligned_alloc
nvrtcgeterrorstring calls string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
destroy_strings calls destroy_string
set_name_expression calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
get_name_expression calls to_str, astring_f2c
get_kernel calls create_nvrtc_module