create_nccl – dtFFT
create_nccl Subroutine
22 statements
Source File
private subroutine create_nccl(self, helper, base_storage)
Uses
iso_fortran_env
Creates NCCL backend
Type Bound
backend_nccl
Arguments
Type Intent Optional Attributes Name
class(backend_nccl), intent(inout) :: self
NCCL backend
type(backend_helper), intent(in) :: helper
Backend helper
integer(kind=int64), intent(in) :: base_storage
Number of bytes to store single element (unused)
Calls
Call graph
create_nccl calls mpi_abort, is_backend_nccl, write_message
write_message calls mpi_comm_rank, mpi_finalized