create_pencils_and_comm – dtFFT
create_pencils_and_comm Subroutine
42 statements
Source File
private subroutine create_pencils_and_comm(dims, old_comm, comm_dims, comm, local_comms, pencils, ipencil)
Creates cartesian communicator
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Global dimensions
type(MPI_Comm), intent(in) :: old_comm
Communicator to create cartesian from
integer(kind=int32), intent(in) :: comm_dims(:)
Dims in cartesian communicator
type(MPI_Comm), intent(out) :: comm
Cartesian communicator
type(MPI_Comm), intent(out) :: local_comms(:)
1d communicators in cartesian communicator
type(pencil), intent(out) :: pencils(:)
Data distributing meta
type(pencil_init), intent(in), optional :: ipencil
Pencil passed by user
Calls
Called by
Call graph
create_pencils_and_comm calls create_cart_comm, create, get_permutations
create_cart_comm calls to_str, mpi_abort, mpi_cart_create, mpi_cart_sub, mpi_comm_dup, mpi_comm_free, create_subcomm_include_all, write_message
create calls mpi_allgather, mpi_comm_size, check_if_even, destroy, get_local_size, create_pencils_and_comm, autotune_grid_decomposition
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
check_if_even calls mpi_allgather, mpi_comm_size
create_subcomm_include_all calls mpi_comm_size, create_subcomm
get_local_size calls mpi_allgather, mpi_comm_size, mpi_comm_rank
write_message calls mpi_comm_rank, mpi_finalized
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
autotune_grid calls create_pencils_and_comm
autotune_grid_decomposition calls autotune_grid