create_private – dtFFT
create_private Function
75 statements
Source File
private function create_private(self, dims, transposed_dims, base_comm, comm_dims, effort, base_dtype, base_storage, is_custom_cart_comm, cart_comm, comms, pencils, ipencil) result(error_code)
Creates transposition plans
Type Bound
transpose_plan_host
Arguments
Type Intent Optional Attributes Name
class(transpose_plan_host), intent(inout) :: self
Transposition class
integer(kind=int32), intent(in) :: dims(:)
Global sizes of the transform requested
integer(kind=int32), intent(in) :: transposed_dims(:,:)
Transposed sizes of the transform requested
type(MPI_Comm), intent(in) :: base_comm
Base communicator
integer(kind=int32), intent(in) :: comm_dims(:)
Number of MPI Processes in all directions
type(dtfft_effort_t), intent(in) :: effort
How thoroughly dtFFT searches for the optimal plan
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI_Datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
logical, intent(in) :: is_custom_cart_comm
Is custom Cartesian communicator provided by user
type(MPI_Comm), intent(out) :: cart_comm
Cartesian communicator
type(MPI_Comm), intent(out) :: comms(:)
Array of 1d communicators
type(pencil), intent(out) :: pencils(:)
Pencils
type(pencil_init), intent(in), optional :: ipencil
Return Value integer(kind=int32)
Error code
Calls
Call graph
create_private calls back_ids, dummy_decomp, dummy_timer, forw_ids, to_str, mpi_comm_size, autotune_grid, autotune_grid_decomposition, create_pencils_and_comm, create, get_conf_log_enabled, get_datatype_from_env, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
autotune_grid calls to_str, create_pencils_and_comm, get_conf_log_enabled, write_message, mpi_comm_free, autotune_mpi_datatypes, destroy, get_local_sizes, get_plan_execution_time, pop_nvtx_domain_range, push_nvtx_domain_range
autotune_grid_decomposition calls to_str, mpi_comm_size, autotune_grid, get_conf_log_enabled, write_message
create_pencils_and_comm calls lcounts, lstarts, create, create_cart_comm
create calls mpi_comm_size, mpi_allgather, create_handle, create_transpose_2d, create_transpose_xy, create_transpose_xz, create_transpose_yz, create_transpose_zx, get_transpose_type, destroy, check_if_even, get_local_size
get_conf_log_enabled calls get_conf_internal
get_datatype_from_env calls get_env
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
autotune_mpi_datatypes calls autotune_transpose_id
create_cart_comm calls mpi_cart_create, mpi_cart_sub, mpi_comm_dup
create_handle calls destroy_handle
create_transpose_2d calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_xy calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_xz calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_yz calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
create_transpose_zx calls mpi_type_commit, mpi_type_contiguous, mpi_type_create_hvector, mpi_type_create_resized, mpi_type_vector, free_datatypes
get_plan_execution_time calls to_str, mpi_comm_size, create, get_conf_log_enabled, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, mpi_allreduce, mpi_wtime, destroy, execute, get_conf_measure_iters, get_conf_measure_warmup_iters
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
autotune_transpose_id calls get_plan_execution_time
check_if_even calls mpi_comm_size, mpi_allgather
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
destroy_handle calls mpi_type_free
destroy calls destroy_handle, mpi_request_free
execute calls mpi_alltoall_init, mpi_alltoallw_init, mpi_start, mpi_wait
free_datatypes calls mpi_type_free
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_env_base calls destroy_string
get_env_int32 calls write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env
get_local_size calls mpi_comm_size, mpi_allgather, mpi_comm_rank