create_cuda – dtFFT
create_cuda Function
90 statements
Source File
private function create_cuda(self, dims, transposed_dims, base_comm, comm_dims, effort, base_dtype, base_storage, is_custom_cart_comm, cart_comm, comms, pencils, ipencil)
Creates CUDA transpose plan
Type Bound
transpose_plan_cuda
Arguments
Type Intent Optional Attributes Name
class(transpose_plan_cuda), intent(inout) :: self
GPU transpose plan
integer(kind=int32), intent(in) :: dims(:)
Global sizes of the transform requested
integer(kind=int32), intent(in) :: transposed_dims(:,:)
Transposed dimensions
type(MPI_Comm), intent(in) :: base_comm
Base communicator
integer(kind=int32), intent(in) :: comm_dims(:)
Number of processors in each dimension
type(dtfft_effort_t), intent(in) :: effort
How thoroughly dtFFT searches for the optimal plan
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI_Datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
logical, intent(in) :: is_custom_cart_comm
is custom Cartesian communicator provided by user
type(MPI_Comm), intent(out) :: cart_comm
Cartesian communicator
type(MPI_Comm), intent(out) :: comms(:)
Array of 1d communicators
type(pencil), intent(out) :: pencils(:)
Data distributing meta
type(pencil_init), intent(in), optional :: ipencil
Return Value integer(kind=int32)
Calls
Call graph
create_cuda calls to_str, mpi_comm_size, mpi_wtime, alloc_and_set_aux, autotune_grid_decomposition, create_helper, create_pencils_and_comm, dtfft_get_backend_string, get_conf_backend, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_stream, is_backend_nccl, load_cuda, load_nvrtc, run_autotune_backend, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
alloc_and_set_aux calls mpi_abort, mpi_allreduce, alloc_mem, dtfft_get_error_string, get_aux_size
autotune_grid_decomposition calls mpi_comm_size, autotune_grid
create_helper calls to_str, mpi_comm_size, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, mpi_comm_rank, destroy_helper, ncclgeterrorstring
create_pencils_and_comm calls lcounts, lstarts, create, create_cart_comm
get_conf_log_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_stream calls to_str, cudastreamcreate, mpi_abort, cudageterrorstring
load_cuda calls destroy_strings, dynamic_load
load_nvrtc calls destroy_strings, dynamic_load
run_autotune_backend calls to_str, mpi_comm_size, alloc_and_set_aux, create_helper, dtfft_get_backend_string, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nvshmem_enabled, is_backend_nccl, write_message, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_allreduce, mpi_barrier, alloc_mem, cudageterrorstring, destroy, dtfft_get_error_string, execute, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, get_conf_pipelined_enabled, get_local_sizes, is_backend_mpi, is_backend_nvshmem, is_backend_pipelined, pop_nvtx_domain_range, push_nvtx_domain_range
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
alloc_mem calls to_str, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, write_message, mpi_abort, mpi_allreduce, cudageterrorstring, is_backend_nvshmem, ncclgeterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, temp
autotune_grid calls to_str, create_pencils_and_comm, get_conf_log_enabled, run_autotune_backend, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, mpi_comm_free, destroy
create calls check_if_even, destroy, get_local_size
create_cart_comm calls mpi_cart_create, mpi_cart_sub, mpi_comm_dup
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy_helper calls to_str, write_message, mpi_abort, ncclgeterrorstring, ncclcommdestroy
destroy_strings calls destroy_string
destroy calls destroy, to_str, mpi_abort, cudageterrorstring, cudafree, remove
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
execute calls execute, to_str, cudastreamsynchronize, mpi_abort, cudageterrorstring, cudamemcpyasync, culaunchkernel, get_contiguous_execution_blocks
free_mem calls to_str, get_conf_log_enabled, is_backend_nccl, write_message, mpi_abort, is_backend_nvshmem, ncclgeterrorstring, cudafree, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr
get_aux_size calls get_aux_size
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
is_null_ptr calls is_null_ptr, is_null_funptr
astring_f2c calls string_f2c
check_if_even calls mpi_comm_size, mpi_allgather
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_env_base calls destroy_string
get_env_int32 calls write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env
get_local_size calls mpi_comm_size, mpi_allgather, mpi_comm_rank
load_library calls is_null_ptr, astring_f2c, dlopen, dl_error
load_symbol calls is_null_ptr, astring_f2c, dlsym, dl_error
unload_library calls dlclose, dl_error
dl_error calls write_message, string_c2f, dlerror
remove calls is_null_ptr, is_same_ptr