create_generic_c2c – dtFFT
create_generic_c2c Subroutine
55 statements
Source File
private subroutine create_generic_c2c(self, dims, comm, precision, effort, executor, error_code)
C2C Generic Plan Constructor Rank of FFT transform
Type Bound
dtfft_core_c2c
Arguments
Type Intent Optional Attributes Name
class(dtfft_core_c2c), intent(inout) :: self
C2C Plan
integer(kind=int32), intent(in) :: dims(:)
Global dimensions of transform
type(MPI_Comm), intent(in), optional :: comm
Communicator
type(dtfft_precision_t), intent(in), optional :: precision
Presicion of Transform
type(dtfft_effort_t), intent(in), optional :: effort
How thoroughly dtFFT searches for the optimal plan
type(dtfft_executor_t), intent(in), optional :: executor
Type of External FFT Executor
integer(kind=int32), intent(out), optional :: error_code
Optional Error Code returned to user
Calls
Call graph
create_generic_c2c calls create, pencils, create_c2c_internal, dtfft_get_error_string, get_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
create_c2c_internal calls create, pencils, fft_mapping, create_private
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create_private calls mpi_comm_rank, cudagetdevice, cudagetdevicecount, int_to_str, local_devices, mpi_abort, mpi_allgather, mpi_comm_free, mpi_comm_size, mpi_comm_split_type, alloc_fft_plans, check_create_args, count_unique, create, cudageterrorstring, get_user_gpu_backend, get_user_stream
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
check_create_args calls mpi_topo_test, get_user_platform, init_internal, is_cuda_executor, is_host_executor, is_valid_comm_type, is_valid_dimension, is_valid_effort, is_valid_executor, is_valid_precision, is_valid_r2r_kind
create calls get_log_enabled, write_message, int_to_str, mpi_comm_size, create_private, mpi_cart_get, mpi_cartdim_get, mpi_dims_create, mpi_topo_test, get_local_sizes, get_user_platform, get_z_slab, temp_coords, temp_dims, temp_periods
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_user_gpu_backend calls get_backend_from_env
get_user_stream calls int_to_str, mpi_abort, cudageterrorstring, cudastreamcreate
get_user_platform calls get_platform_from_env
get_z_slab calls get_z_slab_from_env
init_internal calls backends, get_env, mpi_initialized, platforms, destroy_strings
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
get_env_int32 calls get_log_enabled, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_log_enabled, write_message, get_env