create – dtFFT
create Function
241 statements
Source File
private function create(self, platform, dims, base_comm, effort, base_dtype, base_storage, cart_comm, comms, pencils, ipencil) result(error_code)
Creates transposition plan
Type Bound
transpose_plan
Arguments
Type Intent Optional Attributes Name
class(transpose_plan), intent(inout) :: self
Transposition class
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for
integer(kind=int32), intent(in) :: dims(:)
Global sizes of the transform requested
type(MPI_Comm), intent(in) :: base_comm
Base communicator
type(dtfft_effort_t), intent(in) :: effort
dtFFT planner type of effort
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI_Datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(MPI_Comm), intent(out) :: cart_comm
Cartesian communicator
type(MPI_Comm), intent(out) :: comms(:)
Array of 1d communicators
type(pencil), intent(out) :: pencils(:)
Data distributing meta
type(pencil_init), intent(in), optional :: ipencil
Pencil passed by user
Return Value integer(kind=int32)
Error code
Calls
Call graph
create calls to_str, mpi_cart_get, mpi_cartdim_get, mpi_comm_size, mpi_dims_create, mpi_topo_test, mpi_wtime, alloc_and_set_aux, allocate_plans, autotune_grid_decomposition, create_helper, create_pencils_and_comm, dtfft_get_backend_string, get_conf_backend, get_conf_datatype_enabled, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_stream, get_conf_z_slab_enabled, get_datatype_from_env, get_local_sizes, is_backend_nccl, load_cuda, load_nvrtc, run_autotune_backend, write_message, temp_coords, temp_dims, temp_periods, check_if_even, destroy, get_local_size, create_private, get_transpose_type
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
alloc_and_set_aux calls mpi_abort, mpi_allreduce, alloc_mem, dtfft_get_error_string, get_aux_size_generic
autotune_grid_decomposition calls mpi_comm_size, autotune_grid
create_helper calls mpi_comm_size, fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, mpi_comm_rank, destroy_helper, ncclgeterrorstring
create_pencils_and_comm calls lcounts, lstarts, create_cart_comm, create
get_conf_backend calls get_correct_backend
get_conf_datatype_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_stream calls fname, cudastreamcreate, mpi_abort, cudageterrorstring
get_conf_z_slab_enabled calls get_conf_internal
get_datatype_from_env calls get_env
load_cuda calls destroy_strings, dynamic_load
load_nvrtc calls destroy_strings, dynamic_load
run_autotune_backend calls mpi_comm_size, mpi_wtime, alloc_and_set_aux, allocate_plans, create_helper, dtfft_get_backend_string, get_conf_datatype_enabled, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nvshmem_enabled, get_local_sizes, is_backend_nccl, write_message, execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, alloc_mem, cudageterrorstring, destroy_helper, destroy_plans, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, get_conf_pipelined_enabled, is_backend_mpi, is_backend_nvshmem, is_backend_pipelined, pop_nvtx_domain_range, push_nvtx_domain_range, report_timings, run_autotune_datatypes
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
alloc_mem calls to_str, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, write_message, fname, mpi_abort, mpi_allreduce, cudageterrorstring, is_backend_nvshmem, ncclgeterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mem_alloc_host, temp
autotune_grid calls to_str, create_pencils_and_comm, get_conf_log_enabled, run_autotune_backend, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, mpi_comm_free, destroy
create_cart_comm calls to_str, mpi_cart_create, mpi_cart_sub, mpi_comm_dup, mpi_comm_free, create_subcomm_include_all
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy_helper calls write_message, fname, mpi_abort, ncclgeterrorstring, ncclcommdestroy
destroy_plans calls destroy
destroy_strings calls destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
free_mem calls to_str, get_conf_log_enabled, is_backend_nccl, write_message, fname, mpi_abort, is_backend_nvshmem, ncclgeterrorstring, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr
get_aux_size_generic calls get_aux_size
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_correct_backend calls get_conf_platform
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
report_timings calls to_str, mpi_comm_size, get_conf_log_enabled, write_message, mpi_allreduce
run_autotune_datatypes calls to_str, get_conf_log_enabled, write_message, autotune_transpose_id
is_null_ptr calls is_null_ptr, is_null_funptr
astring_f2c calls string_f2c
autotune_transpose_id calls get_plan_execution_time
check_if_even calls mpi_comm_size, mpi_allgather
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create_subcomm_include_all calls mpi_comm_size, create_subcomm
get_env_base calls destroy_string
get_env_int32 calls write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
get_local_size calls mpi_comm_size, mpi_allgather, mpi_comm_rank
load_library calls is_null_ptr, astring_f2c, dlopen, dl_error
load_symbol calls is_null_ptr, astring_f2c, dlsym, dl_error
mem_alloc_host calls aligned_alloc
string_c2f calls is_null_ptr
unload_library calls dlclose, dl_error
create_subcomm calls mpi_comm_create, mpi_comm_group, mpi_group_free, mpi_group_incl
dl_error calls write_message, string_c2f, dlerror
get_plan_execution_time calls to_str, mpi_wtime, get_conf_log_enabled, write_message, mpi_barrier, get_conf_measure_iters, get_conf_measure_warmup_iters, pop_nvtx_domain_range, push_nvtx_domain_range, report_timings, create, destroy, execute
destroy calls mpi_request_free, destroy_handle
execute calls mpi_comm_size, mpi_alltoall_init, mpi_alltoallw_init, mpi_startall, execute_end
destroy_handle calls mpi_type_free
execute_end calls mpi_waitall