create_r2c_internal – dtFFT
create_r2c_internal Function
36 statements
Source File
private function create_r2c_internal(self, dims, pencil, comm, precision, effort, executor)
Private method that combines common logic for R2C plan creation
Type Bound
dtfft_plan_r2c_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_r2c_t), intent(inout) :: self
R2C Plan
integer(kind=int32), intent(in), optional :: dims(:)
Global dimensions of transform
type(dtfft_pencil_t), intent(in), optional :: pencil
Local pencil of data to be transformed
type(MPI_Comm), intent(in), optional :: comm
Communicator
type(dtfft_precision_t), intent(in), optional :: precision
Presicion of Transform
type(dtfft_effort_t), intent(in), optional :: effort
Effort level for the plan creation
type(dtfft_executor_t), intent(in), optional :: executor
Type of External FFT Executor
Return Value integer(kind=int32)
Calls
Called by
Call graph
create_r2c_internal calls create, create_c2c_core, pop_nvtx_domain_range, push_nvtx_domain_range
create_c2c_core calls create_private, create
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create_private calls create, counts, destroy, fixed_dims, fname, from_bricks, cudagetdevice, cudagetdevicecount, local_devices, mpi_abort, mpi_allgather, mpi_comm_free, mpi_comm_rank, mpi_comm_size, mpi_comm_split_type, alloc_fft_plans, check_create_args, count_unique, cudageterrorstring, get_backend, get_conf_stream, get_y_slab, get_z_slab, write_message
create calls pop_nvtx_domain_range, push_nvtx_domain_range, create_private, to_str, is_null_ptr, mpi_abort, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
alloc_fft_plans calls counts, mpi_abort, write_message
check_create_args calls mpi_abort, write_message, mpi_topo_test, get_conf_backend, get_conf_platform, init_internal, is_backend_nccl, is_backend_nvshmem, is_cuda_executor, is_host_executor, is_valid_comm_type, is_valid_dimension, is_valid_effort, is_valid_executor, is_valid_precision, is_valid_r2r_kind
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_conf_stream calls fname, mpi_abort, cudageterrorstring, cudastreamcreate
write_message calls mpi_comm_rank, mpi_finalized
get_conf_backend calls get_correct_backend
init_internal calls mpi_initialized, init_environment
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
get_correct_backend calls get_conf_platform
init_environment calls destroy, access_modes, get_env, platforms, destroy_strings, get_backend_from_env, transpose_modes
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_strings calls destroy_string
get_backend_from_env calls write_message, get_env, destroy_strings, destroy_string, is_valid_backend
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls mpi_abort, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal