create – dtFFT
create Function
110 statements
Source File
private function create(self, platform, ipencil, pencils, comm, local_comms, base_dtype, base_storage, effort, backend, base_init_dtype, base_init_storage, bricks, is_final_enabled) result(error_code)
Creates reshape plan
This function initializes the reshape plan by creating communicators for brick layouts, setting up grid decompositions, and allocating reshape operation plans.
Type Bound
reshape_plan
Arguments
Type Intent Optional Attributes Name
class(reshape_plan), intent(inout) :: self
Reshape plan to be initialized
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for (HOST or CUDA)
type(pencil_init), intent(in) :: ipencil
Pencil decomposition passed by user
type(pencil), intent(in) :: pencils(:)
Array of pencil decompositions for different layouts
type(MPI_Comm), intent(in) :: comm
Global MPI communicator
type(MPI_Comm), intent(in) :: local_comms(:)
Local MPI communicators for each dimension
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI datatype for complex data
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single complex element
type(dtfft_effort_t), intent(in) :: effort
dtFFT planner effort level (ESTIMATE, MEASURE, PATIENT, EXHAUSTIVE)
type(dtfft_backend_t), intent(in) :: backend
Communication backend used for transpose plans
type(MPI_Datatype), intent(in) :: base_init_dtype
Base MPI datatype for real data
integer(kind=int64), intent(in) :: base_init_storage
Number of bytes needed to store single real element
type(pencil), intent(out) :: bricks(:)
Pencils describing brick data distribution
logical, intent(out) :: is_final_enabled
Flag indicating if final reshape in Fourier space is enabled
Return Value integer(kind=int32)
Error code: DTFFT_SUCCESS on success
Calls
Call graph
create calls final_comms, final_sizes, to_str, mpi_allreduce, mpi_comm_free, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_wtime, autotune_reshape_plan, create_custom_comm, create_reshape_plans, create, dtfft_get_backend_string, get_compatible, get_conf_fourier_reshape_enabled, get_conf_log_enabled, get_conf_reshape, get_conf_reshape_backend, get_local_sizes, init, is_backend_compatible, is_backend_nccl, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, mpi_allgather, check_if_even, destroy, get_local_size, mpi_abort, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
autotune_reshape_plan calls create_reshape_plans, dtfft_get_backend_string, get_conf_log_enabled, get_conf_reshape, is_backend_compatible, is_backend_nccl, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, autotune_adaptive, create_helper, destroy_helper, destroy_plans, execute_autotune, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_fused_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, get_conf_rma_enabled, is_backend_compressed, is_backend_fused, is_backend_mpi, is_backend_nvshmem, is_backend_pipelined, is_backend_rma
create_custom_comm calls mpi_comm_rank, mpi_comm_size, mpi_comm_split
create_reshape_plans calls get_conf_reshape, write_message, mpi_abort, allocate_plans, create
get_compatible calls is_backend_nccl, is_backend_mpi, is_backend_nvshmem
get_conf_fourier_reshape_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_reshape_backend calls get_correct_backend
init calls is_backend_nccl, write_message, create, destroy, mpi_abort, check_compression_config, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_stream, is_backend_compressed, is_backend_nvshmem, load_cuda, load_nvrtc
is_backend_compatible calls is_backend_nccl, is_backend_mpi, is_backend_nvshmem
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
allocate_plans calls write_message, mpi_abort
astring_f2c calls string_f2c
autotune_adaptive calls create_reshape_plans, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, destroy_plans, execute_autotune, destroy_string
check_compression_config calls is_valid_compression_lib, is_valid_compression_mode
check_if_even calls mpi_comm_size, mpi_allgather
create_helper calls mpi_comm_rank, mpi_comm_size, mpi_abort, mpi_allgather, destroy_helper, fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_bcast, ncclgeterrorstring
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
destroy_helper calls write_message, mpi_abort, fname, ncclcommdestroy, ncclgeterrorstring
destroy_plans calls destroy
execute_autotune calls mpi_wtime, mpi_abort, execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_barrier, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
get_conf_compression_enabled calls get_conf_internal
get_conf_datatype_enabled calls get_conf_internal
get_conf_fused_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_conf_stream calls mpi_abort, fname, cudastreamcreate, cudageterrorstring
get_correct_backend calls get_conf_platform
get_local_size calls mpi_comm_rank, mpi_comm_size, mpi_allgather
load_cuda calls destroy_strings, dynamic_load
load_nvrtc calls destroy_strings, dynamic_load
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
alloc_and_set_aux calls mpi_allreduce, mpi_abort, alloc_mem, dtfft_get_error_string, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls to_str, mpi_allreduce, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, write_message, mpi_abort, is_backend_nvshmem, fname, cudageterrorstring, ncclgeterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mem_alloc_host, temp
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy_strings calls destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
free_mem calls to_str, get_conf_log_enabled, is_backend_nccl, write_message, mpi_abort, is_backend_nvshmem, fname, ncclgeterrorstring, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
report_timings calls to_str, mpi_allreduce, mpi_comm_size, get_conf_log_enabled, write_message
is_null_ptr calls is_null_ptr, is_null_funptr
get_aux_bytes_generic calls get_aux_bytes
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls write_message, mpi_abort, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string
is_nvshmem_generic calls is_backend_nvshmem, get_backend
load_library calls astring_f2c, is_null_ptr, dlopen, dl_error
load_symbol calls write_message, mpi_abort, astring_f2c, is_null_ptr, dlsym, dl_error
mem_alloc_host calls aligned_alloc
string_c2f calls is_null_ptr
unload_library calls dlclose, dl_error
dl_error calls write_message, string_c2f, dlerror