create_host – dtFFT
create_host Subroutine
94 statements
Source File
private subroutine create_host(self, effort, base_storage, force_effort)
Creates host kernel
Type Bound
kernel_host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(inout) :: self
Host kernel class
type(dtfft_effort_t), intent(in) :: effort
Effort level for generating transpose kernels
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
logical, intent(in), optional :: force_effort
Should effort be forced or not
Calls
Call graph
create_host calls mem_free_host, to_str, execute_benchmark, get_conf_access_mode, get_conf_kernel_autotune_enabled, get_conf_log_enabled, get_conf_measure_iters, get_conf_measure_warmup_iters, get_host_kernel_string, is_pack_kernel, is_unpack_kernel, mem_alloc_host, pop_nvtx_domain_range, push_nvtx_domain_range, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64, select_kernel, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
execute_benchmark calls pop_nvtx_domain_range, push_nvtx_domain_range, write_message, mpi_abort, mpi_wtime
get_conf_kernel_autotune_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
mem_alloc_host calls aligned_alloc
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
select_access_mode_f128 calls to_str, execute_benchmark, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
select_access_mode_f32 calls to_str, execute_benchmark, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
select_access_mode_f64 calls to_str, execute_benchmark, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
select_kernel calls to_str, write_message, mpi_abort
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c