cudaGetErrorString – dtFFT
cudaGetErrorString Function
5 statements
Source File
public function cudaGetErrorString(errcode) result(string)
Helper function that returns a string describing the given nvrtcResult code If the error code is not recognized, “unrecognized error code” is returned.
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: errcode
CUDA Runtime Compilation API result code.
Return Value character(len=:), allocatable
Result string
Calls
Called by
Call graph
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
alloc_mem calls cudageterrorstring
create_private calls cudageterrorstring, get_conf_stream
create calls cudageterrorstring, destroy, get_kernel, get_conf_stream, init, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
destroy_stream calls cudageterrorstring
destroy calls cudageterrorstring, destroy_stream
execute_autotune calls cudageterrorstring, alloc_mem, alloc_and_set_aux
execute_mpi calls cudageterrorstring, execute_self_copy, execute_fused, execute_p2p_scheduled
execute_self_copy calls cudageterrorstring
execute_test calls cudageterrorstring
execute calls cudageterrorstring, execute_self_copy, execute
get calls cudageterrorstring
get_conf_stream calls cudageterrorstring
get_kernel calls cudageterrorstring, get_conf_stream, create_nvrtc_module, get_kernel_instance
output calls cudageterrorstring
post_sync calls cudageterrorstring
pre_sync calls cudageterrorstring
sync calls cudageterrorstring
wait calls cudageterrorstring
test_device_kernels calls cudageterrorstring, execute_test
alloc_and_set_aux calls alloc_mem
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
create_c2c_core calls create_private
create_nvrtc_module calls create
create_r2r_internal calls create_private
execute_fused calls execute_self_copy
execute_many calls execute_autotune, execute_single
execute_nccl calls execute_self_copy
execute_p2p_scheduled calls execute_self_copy
get_kernel_instance calls get
init calls get_conf_stream
mem_alloc calls alloc_mem
run_execute_single calls execute_autotune
test_pack_unpack calls destroy
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
dtfft_destroy_c calls destroy
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
test_compression calls test_pack_unpack
autotune_grid calls run_autotune_backend
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid