cufftGetErrorString – dtFFT
cufftGetErrorString Function
42 statements
Source File
public function cufftGetErrorString(error_code) result(string)
Returns a string representation of the cuFFT error code.
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int32_t), intent(in) :: error_code
cuFFT error code
Return Value character(len=:), allocatable
String representation of the cuFFT error code
Called by
Call graph
create calls cufftgeterrorstring
destroy calls cufftgeterrorstring
execute calls cufftgeterrorstring