cuLaunchKernel – dtFFT
cuLaunchKernel Function
24 statements
Source File
public function cuLaunchKernel(func, in, out, blocks, threads, stream, kernelParams) result(cuResult)
Launches a CUDA kernel
Arguments
Type Intent Optional Attributes Name
type(CUfunction), intent(in) :: func
Function CUfunction or Kernel CUkernel to launch
type(c_ptr), intent(in), target :: in
Input pointer
type(c_ptr), intent(in), target :: out
Output pointer
type(dim3), intent(in) :: blocks
Grid in blocks
type(dim3), intent(in) :: threads
Thread block
type(dtfft_stream_t), intent(in) :: stream
Stream identifier
type(kernelArgs), intent(in), target :: kernelParams
Input parameters of kernel func
Return Value integer(kind=c_int)
Driver result code
Called by
Call graph
execute calls culaunchkernel, execute
get_kernel calls culaunchkernel
create calls get_kernel, create
execute_mpi calls execute
execute_nccl calls execute
execute_cuda calls execute
run_autotune_backend calls execute
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid