decompress – dtFFT
decompress Subroutine
31 statements
Source File
private subroutine decompress(self, dims, in, out, stream)
Uses
iso_fortran_env
Decompresses the input data using ZFP
Type Bound
compressor_zfp
Arguments
Type Intent Optional Attributes Name
class(compressor_zfp), intent(inout) :: self
Compressor instance
integer(kind=int32), intent(in) :: dims(:)
Array dimensions
type(c_ptr), intent(in) :: in
Pointer to compressed data
type(c_ptr), intent(in) :: out
Pointer to output buffer
type(dtfft_stream_t), intent(in) :: stream
Stream handle
Calls
Call graph
decompress calls stream_close, stream_open, zfp_decompress, zfp_field_free, zfp_field_set_pointer, zfp_stream_close, zfp_stream_rewind, zfp_stream_set_bit_stream, mpi_abort, init, ptr_offset, write_message
init calls zfp_stream_open, zfp_stream_set_execution, zfp_stream_set_reversible, zfp_create_field, zfp_field_set_stride, zfp_stream_set_accuracy, zfp_stream_set_precision, zfp_stream_set_rate
write_message calls mpi_comm_rank, mpi_finalized
zfp_create_field calls zfp_field_2d, zfp_field_3d
zfp_field_set_stride calls zfp_field_dimensionality, zfp_field_set_stride_2d, zfp_field_set_stride_3d
zfp_stream_set_accuracy calls zfp_stream_set_accuracy_interface
zfp_stream_set_precision calls zfp_stream_set_precision_interface
zfp_stream_set_rate calls zfp_field_dimensionality, zfp_field_type, zfp_stream_set_rate_interface