destroy – dtFFT
destroy Subroutine
9 statements
Source File
private subroutine destroy(self)
Destroys CUDA Transpose Handle
Type Bound
transpose_handle_cuda
Arguments
Type Intent Optional Attributes Name
class(transpose_handle_cuda), intent(inout) :: self
CUDA Transpose Handle
Calls
Called by
Call graph
destroy calls destroy, cudafree, int_to_str, mpi_abort, cudageterrorstring, mark_unused
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c, string_c2f
mark_unused calls is_same_ptr
destroy_cuda calls destroy
run_autotune_backend calls destroy
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid