destroy – dtFFT
destroy Subroutine
18 statements
Source File
private subroutine destroy(self)
Uses
iso_fortran_env
iso_c_binding
Cleans up the compressor resources
Type Bound
compressor_zfp
Arguments
Type Intent Optional Attributes Name
class(compressor_zfp), intent(inout) :: self
Compressor instance
Calls
Call graph
destroy calls fname, cudaeventdestroy, mpi_abort, cudageterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr