destroy – dtFFT
destroy Subroutine
37 statements
Source File
private subroutine destroy(self)
Uses
iso_fortran_env
iso_c_binding
Destroys module and frees resources
Type Bound
nvrtc_module
Arguments
Type Intent Optional Attributes Name
class(nvrtc_module), intent(inout) :: self
Calls
Called by
Call graph
destroy calls fname, is_null_ptr, mpi_abort, cudageterrorstring, nvrtcgeterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
nvrtcgeterrorstring calls string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
create calls destroy, get_kernel
create_nvrtc_module calls create
get_kernel calls create_nvrtc_module