destroy_handle – dtFFT
destroy_handle Subroutine
13 statements
Source File
private subroutine destroy_handle(self)
Destroys transposition handle
Type Bound
handle_t
Arguments
Type Intent Optional Attributes Name
class(handle_t), intent(inout) :: self
Transposition handle
Calls
Called by
Call graph
destroy_handle calls mpi_type_free
create_handle calls destroy_handle
destroy calls destroy_handle, destroy
create calls create_handle
get_plan_execution_time calls destroy, create
autotune_grid calls get_plan_execution_time, autotune_mpi_datatypes
autotune_transpose_id calls get_plan_execution_time
create_private calls create, autotune_grid, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid
autotune_mpi_datatypes calls autotune_transpose_id