destroy_string – dtFFT
destroy_string Subroutine
4 statements
Source File
private subroutine destroy_string(self)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(inout) :: self
Called by
Call graph
autotune_adaptive calls destroy_string
create_nvrtc_module calls destroy_string, create
destroy_strings calls destroy_string
destroy calls destroy_string, destroy
get_backend_from_env calls destroy_string, destroy_strings, get_env
get_env_base calls destroy_string
get_env_string calls destroy_string, get_env
test_transpose calls destroy_string
get_env calls get_env_base, get_env_string, get_env_int32, get_env_int8, get_env_logical
autotune_reshape_plan calls autotune_adaptive, create_helper
compile_program calls destroy_strings
create calls destroy, compile_program, get_kernel, create, autotune_reshape_plan, init, create_helper, run_autotune_backend, autotune_grid_decomposition, load_vkfft
execute_test calls destroy, create
get_kernel calls create_nvrtc_module
init_environment calls destroy_strings, get_backend_from_env, get_env
load calls destroy_strings
load_cuda calls destroy_strings
load_nvrtc calls destroy_strings
test_compression calls test_transpose, init_internal
create_helper calls get_env
get_env_int32 calls get_env
get_env_int8 calls get_env
get_env_logical calls get_env
init calls load_cuda, load_nvrtc
init_internal calls init_environment
load_vkfft calls load
test_device_kernels calls execute_test, load_cuda, load_nvrtc, init_internal
check_create_args calls init_internal
dtfft_set_config calls init_internal
run_autotune_backend calls create_helper
autotune_grid calls run_autotune_backend
create_private calls check_create_args
dtfft_set_config_c calls dtfft_set_config
autotune_grid_decomposition calls autotune_grid
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal