destroy – dtFFT
destroy Subroutine
25 statements
Source File
private subroutine destroy(self)
Destroys Generic Transpose Handle
Type Bound
reshape_handle_generic
Arguments
Type Intent Optional Attributes Name
class(reshape_handle_generic), intent(inout) :: self
Generic Transpose Handle
Calls
Called by
Call graph
destroy calls destroy, destroy_private, destroy_string
create calls destroy