destroy_helper – dtFFT
destroy_helper Subroutine
28 statements
Source File
private subroutine destroy_helper(self)
Uses
iso_c_binding
iso_fortran_env
Destroys helper
Type Bound
backend_helper
Arguments
Type Intent Optional Attributes Name
class(backend_helper), intent(inout) :: self
Backend helper
Calls
Called by
Call graph
destroy_helper calls fname, ncclcommdestroy, mpi_abort, ncclgeterrorstring, write_message
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
autotune_reshape_plan calls destroy_helper, create_helper
create_helper calls destroy_helper
destroy calls destroy_helper, destroy
run_autotune_backend calls destroy_helper, create_helper
autotune_grid calls run_autotune_backend
create calls create_helper, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
autotune_grid_decomposition calls autotune_grid