destroy – dtFFT
destroy Subroutine
64 statements
Source File
private subroutine destroy(self, error_code)
Destroys plan, frees all memory
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional Error Code returned to user
Calls
Called by
Call graph
destroy calls destroy, mpi_comm_free, mpi_finalized, mem_free, clean_unused_cache, destroy_stream, dtfft_get_error_string, get_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
clean_unused_cache calls int_to_str, is_null_ptr, mpi_abort, cudageterrorstring
destroy_stream calls cudastreamdestroy, int_to_str, mpi_abort, cudageterrorstring
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_finalized, mpi_comm_rank
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
mem_free_c32_1d calls mem_free
mem_free_c32_2d calls mem_free
mem_free_c32_3d calls mem_free
mem_free_c64_1d calls mem_free
mem_free_c64_2d calls mem_free
mem_free_c64_3d calls mem_free
mem_free_ptr calls dtfft_get_error_string, get_log_enabled, write_message, mem_free_host, mem_free
mem_free_r32_1d calls mem_free
mem_free_r32_2d calls mem_free
mem_free_r32_3d calls mem_free
mem_free_r64_1d calls mem_free
mem_free_r64_2d calls mem_free
mem_free_r64_3d calls mem_free
dtfft_destroy_c calls destroy