destroy – dtFFT
destroy Subroutine
5 statements
Source File
private subroutine destroy(self)
Destroys pencil
Type Bound
pencil
Arguments
Type Intent Optional Attributes Name
class(pencil), intent(inout) :: self
Pencil
Called by
Call graph
autotune_grid calls destroy, create_pencils_and_comm
create calls destroy
create_private calls destroy, autotune_grid, autotune_grid_decomposition, create_pencils_and_comm
autotune_grid_decomposition calls autotune_grid
create_c2c_core calls create_private
create_pencils_and_comm calls create
create_r2c_internal calls create, create_c2c_core
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_cuda calls autotune_grid_decomposition, create_pencils_and_comm
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal