destroy – dtFFT
destroy Subroutine
24 statements
Source File
private subroutine destroy(self)
Uses
iso_c_binding
iso_fortran_env
Destroys kernel
Type Bound
nvrtc_kernel
Arguments
Type Intent Optional Attributes Name
class(nvrtc_kernel), intent(inout) :: self
nvRTC Compiled kernel class
Calls
Called by
Call graph
destroy calls cudafree, to_str, mpi_abort, cudageterrorstring, remove, destroy
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
remove calls is_null_ptr, is_same_ptr
create calls destroy, create
destroy_cuda calls destroy
run_autotune_backend calls destroy
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid