destroy_strings – dtFFT
destroy_strings Subroutine
9 statements
Source File
public subroutine destroy_strings(strings)
Destroys array of string objects
Arguments
Type Intent Optional Attributes Name
type(string), intent(inout), allocatable :: strings(:)
Array of strings
Calls
Called by
Call graph
destroy_strings calls destroy_string
compile_program calls destroy_strings
get_backend_from_env calls destroy_strings
init_environment calls destroy_strings, get_backend_from_env
load calls destroy_strings
load_cuda calls destroy_strings
load_nvrtc calls destroy_strings
create calls compile_program, init, load_vkfft, get_kernel
init calls load_cuda, load_nvrtc
init_internal calls init_environment
load_vkfft calls load
test_device_kernels calls load_cuda, load_nvrtc, init_internal
check_create_args calls init_internal
create_nvrtc_module calls create
dtfft_set_config calls init_internal
test_compression calls init_internal
create_private calls check_create_args
dtfft_set_config_c calls dtfft_set_config
get_kernel calls create_nvrtc_module
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal