destroy_stream – dtFFT
destroy_stream Subroutine
15 statements
Source File
public subroutine destroy_stream()
Uses
iso_c_binding
iso_fortran_env
Destroy the default stream if it was created
Arguments
None
Calls
Called by
Call graph
destroy_stream calls cudastreamdestroy, to_str, mpi_abort, cudageterrorstring
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy calls destroy_stream
dtfft_destroy_c calls destroy