destroy – dtFFT
destroy Subroutine
15 statements
Source File
private subroutine destroy(self)
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(inout) :: self
Calls
Called by
Call graph
destroy calls destroy_helper, destroy_plans, destroy
destroy_helper calls fname, ncclcommdestroy, mpi_abort, ncclgeterrorstring, write_message
destroy_plans calls destroy
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr