destroy_cuda – dtFFT
destroy_cuda Subroutine
20 statements
Source File
private subroutine destroy_cuda(self)
Destroys transposition plans
Type Bound
transpose_plan_cuda
Arguments
Type Intent Optional Attributes Name
class(transpose_plan_cuda), intent(inout) :: self
Transposition class
Calls
Call graph
destroy_cuda calls cleanup, destroy, mem_free
cleanup calls to_str, is_null_ptr, mpi_abort, cudageterrorstring, get_conf_log_enabled, write_message
destroy calls destroy, to_str, mpi_abort, cudageterrorstring, cudafree, remove
mem_free calls free_mem
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls to_str, mpi_abort, get_conf_log_enabled, write_message, cudafree, ncclcommderegister, ncclmemfree, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
remove calls is_null_ptr, is_same_ptr