destroy_plans – dtFFT
destroy_plans Subroutine
10 statements
Source File
public subroutine destroy_plans(plans)
Destroys array of plans
Arguments
Type Intent Optional Attributes Name
type(reshape_container), intent(inout) :: plans(:)
Plans to destroy
Calls
Called by
Call graph
destroy_plans calls destroy
autotune_adaptive calls destroy_plans
autotune_reshape_plan calls destroy_plans, autotune_adaptive
destroy calls destroy_plans, destroy
execute_many calls destroy_plans, execute_single
run_execute_single calls destroy_plans
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid