DftiErrorMessage – dtFFT
DftiErrorMessage Function
5 statements
Source File
public function DftiErrorMessage(error_code) result(string)
Generates an error message.
Arguments
Type Intent Optional Attributes Name
integer(kind=c_long), intent(in) :: error_code
Completion status of a function.
Return Value character(len=:), allocatable
Error message
Calls
Called by
Call graph
dftierrormessage calls dftierrormessage_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
destroy calls dftierrormessage
execute calls dftierrormessage
make_plan calls dftierrormessage
mem_alloc calls dftierrormessage
mem_free calls dftierrormessage
create calls make_plan