dl_error – dtFFT
dl_error Subroutine
7 statements
Source File
private subroutine dl_error(message)
Writes error message to the error unit
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
Message to write
Calls
Called by
Call graph
dl_error calls dlerror, string_c2f, write_message
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
load_library calls dl_error
load_symbol calls dl_error
unload_library calls dl_error
dynamic_load calls load_library, load_symbol, unload_library
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
create calls load_cuda, load_nvrtc, load_vkfft
load_vkfft calls load