double_to_str – dtFFT
double_to_str Function
7 statements
Source File
public function double_to_str(n) result(string)
Convert double to string
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: n
Double to convert
Return Value character(len=:), allocatable
Resulting string
Called by
Call graph
autotune_grid calls double_to_str, get_plan_execution_time, autotune_mpi_datatypes, run_autotune_backend
create_cuda calls double_to_str, run_autotune_backend, autotune_grid_decomposition
get_plan_execution_time calls double_to_str
run_autotune_backend calls double_to_str
autotune_grid_decomposition calls autotune_grid
autotune_transpose_id calls get_plan_execution_time
create_private calls autotune_grid, autotune_grid_decomposition
autotune_mpi_datatypes calls autotune_transpose_id