dtfft_get_pencil_c – dtFFT
dtfft_get_pencil_c Function
15 statements
Source File
private function dtfft_get_pencil_c(plan_ptr, dim, pencil) result(error_code) bind(C)
Returns pencil decomposition info, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_int32_t), intent(in) :: dim
Dimension requested
type(dtfft_pencil_c) :: pencil
Pencil pointer
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_pencil_c calls is_null_ptr, get_pencil, pencil_f2c
get_pencil calls make_public, dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized