dtfft_destroy_c – dtFFT
dtfft_destroy_c Function
14 statements
Source File
private function dtfft_destroy_c(plan_ptr) result(error_code) bind(C)
Destroys dtFFT Plan, C/C++ interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: plan_ptr
C pointer to Fortran plan
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_destroy_c calls is_null_ptr, destroy
destroy calls destroy, mpi_comm_free, mpi_finalized, mem_free, clean_unused_cache, destroy_stream, dtfft_get_error_string, get_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
clean_unused_cache calls is_null_ptr, int_to_str, mpi_abort, cudageterrorstring
destroy_stream calls cudastreamdestroy, int_to_str, mpi_abort, cudageterrorstring
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_finalized, mpi_comm_rank
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
mem_free_c32_1d calls mem_free
mem_free_c32_2d calls mem_free
mem_free_c32_3d calls mem_free
mem_free_c64_1d calls mem_free
mem_free_c64_2d calls mem_free
mem_free_c64_3d calls mem_free
mem_free_ptr calls dtfft_get_error_string, get_log_enabled, write_message, mem_free_host, mem_free
mem_free_r32_1d calls mem_free
mem_free_r32_2d calls mem_free
mem_free_r32_3d calls mem_free
mem_free_r64_1d calls mem_free
mem_free_r64_2d calls mem_free
mem_free_r64_3d calls mem_free