dtfft_set_config – dtFFT
dtfft_set_config Subroutine
73 statements
Source File
public subroutine dtfft_set_config(config, error_code)
Sets configuration parameters
Arguments
Type Intent Optional Attributes Name
type(dtfft_config_t), intent(in) :: config
Configuration to set
integer(kind=int32), intent(out), optional :: error_code
Error code
Calls
Called by
Call graph
dtfft_set_config calls cudastreamquery, is_null_ptr, get_correct_backend, init_internal, is_valid_access_mode, is_valid_backend, is_valid_platform, is_valid_transpose_mode
get_correct_backend calls get_conf_platform
init_internal calls mpi_initialized, init_environment
init_environment calls access_modes, destroy, get_env, platforms, destroy_strings, get_backend_from_env, transpose_modes
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_strings calls destroy_string
get_backend_from_env calls is_valid_backend, get_env, destroy_strings, destroy_string, write_message
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls get_env, write_message, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, destroy_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_set_config_c calls dtfft_set_config