dtfft_get_aux_size_reshape_c – dtFFT
dtfft_get_aux_size_reshape_c Function
12 statements
Source File
private function dtfft_get_aux_size_reshape_c(plan_ptr, aux_size) result(error_code) bind(C)
Returns size of auxiliary buffer for reshape in elements, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_size_t), intent(out) :: aux_size
Size of auxiliary buffer for reshape in elements
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_aux_size_reshape_c calls is_null_ptr, get_aux_size_reshape
get_aux_size_reshape calls dtfft_get_error_string, get_aux_bytes_reshape, get_element_size, write_message
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_element_size calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes calls get_aux_bytes_generic
get_aux_bytes_generic calls get_aux_bytes