dtfft_get_backend_string – dtFFT
dtfft_get_backend_string Function
44 statements
Source File
public function dtfft_get_backend_string(backend) result(string)
Gets the string description of a backend
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: backend
Backend ID
Return Value character(len=:), allocatable
Backend string
Called by
Call graph
alloc_mem calls dtfft_get_backend_string
autotune_reshape_plan calls dtfft_get_backend_string, execute_autotune, autotune_adaptive
create calls dtfft_get_backend_string, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
dtfft_get_backend_string_c calls dtfft_get_backend_string
execute_many calls dtfft_get_backend_string, execute_single, execute_autotune
execute_single calls dtfft_get_backend_string, execute_single_transpose_modes
report calls dtfft_get_backend_string, report_backends
report_backends calls dtfft_get_backend_string
alloc_and_set_aux calls alloc_mem
dtfft_report_c calls report
execute_autotune calls alloc_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
run_autotune_backend calls execute_many, execute_single
autotune_adaptive calls execute_autotune
autotune_grid calls run_autotune_backend
run_execute_single calls execute_autotune
autotune_grid_decomposition calls autotune_grid
execute_single_transpose_modes calls run_execute_single