dtfft_mem_alloc_c – dtFFT
dtfft_mem_alloc_c Function
13 statements
Source File
private function dtfft_mem_alloc_c(plan_ptr, alloc_bytes, ptr) result(error_code) bind(C)
Allocates memory for dtFFT Plan, C/C++ interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_size_t), value :: alloc_bytes
Number of bytes to allocate
type(c_ptr) :: ptr
Allocated pointer
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_mem_alloc_c calls is_null_ptr, mem_alloc
mem_alloc_c32_1d calls mem_alloc
mem_alloc_c32_2d calls mem_alloc
mem_alloc_c32_3d calls mem_alloc
mem_alloc_c64_1d calls mem_alloc
mem_alloc_c64_2d calls mem_alloc
mem_alloc_c64_3d calls mem_alloc
mem_alloc_ptr calls is_null_ptr, mem_alloc_host, mem_alloc, dtfft_get_error_string, get_log_enabled, write_message
mem_alloc_r32_1d calls mem_alloc
mem_alloc_r32_2d calls mem_alloc
mem_alloc_r32_3d calls mem_alloc
mem_alloc_r64_1d calls mem_alloc
mem_alloc_r64_2d calls mem_alloc
mem_alloc_r64_3d calls mem_alloc
write_message calls mpi_comm_rank, mpi_finalized