dtfft_report_c – dtFFT
dtfft_report_c Function
11 statements
Source File
private function dtfft_report_c(plan_ptr) result(error_code) bind(C)
Reports dtFFT Plan, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_report_c calls is_null_ptr, report
report calls comm_dims, to_str, dtfft_get_backend_string, dtfft_get_error_string, dtfft_get_executor_string, dtfft_get_precision_string, get_backend, get_grid, get_grid_str, report_backends, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_grid_str calls to_str
report_backends calls dtfft_get_backend_string, write_message, get_backend, mpi_abort
write_message calls mpi_comm_rank, mpi_finalized