dtfft_get_local_sizes_c – dtFFT
dtfft_get_local_sizes_c Function
16 statements
Source File
private function dtfft_get_local_sizes_c(plan_ptr, in_starts, in_counts, out_starts, out_counts, alloc_size) result(error_code) bind(C)
Returns local sizes, counts in real and Fourier spaces and number of elements to be allocated for in and out buffers, C/C++ interface. It is necessary for R2C transform to allocate out buffer with alloc_size number of elements. Total number of bytes to be allocated : - C2C: 2 * alloc_size * sizeof(double/float) - R2R: alloc_size * sizeof(double/float) - R2C: alloc_size * sizeof(double/float)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_int32_t), intent(out), optional :: in_starts(3)
Starts of local portion of data in ‘real’ space
integer(kind=c_int32_t), intent(out), optional :: in_counts(3)
Counts of local portion of data in ‘real’ space
integer(kind=c_int32_t), intent(out), optional :: out_starts(3)
Starts of local portion of data in ‘fourier’ space
integer(kind=c_int32_t), intent(out), optional :: out_counts(3)
Counts of local portion of data in ‘fourier’ space
integer(kind=c_size_t), intent(out), optional :: alloc_size
Minimum data needs to be allocated
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_code_t defines API call result codes.
Calls
Call graph
dtfft_get_local_sizes_c calls get_local_sizes
get_local_sizes calls mpi_allreduce, dtfft_get_error_string, get_gpu_backend, get_local_sizes, get_log_enabled, is_backend_nvshmem, write_message
get_gpu_backend calls get_gpu_backend
write_message calls mpi_comm_rank, mpi_finalized