dtfft_get_platform_c – dtFFT
dtfft_get_platform_c Function
12 statements
Source File
private function dtfft_get_platform_c(plan_ptr, platform) result(error_code) bind(C)
Returns selected dtfft_platform_t during autotuning
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
type(dtfft_platform_t), intent(out) :: platform
The enumerated type dtfft_platform_t
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_platform_c calls is_null_ptr, get_platform
get_platform calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized