dtfft_get_error_string – dtFFT
dtfft_get_error_string Function
138 statements
Source File
public pure function dtfft_get_error_string(error_code) result(error_string)
Gets the string description of an error code
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: error_code
Error code
Return Value character(len=:), allocatable
Error string
Called by
Call graph
alloc_and_set_aux calls dtfft_get_error_string
check_aux calls dtfft_get_error_string, get_alloc_bytes, get_aux_bytes, mem_alloc_ptr
create_c2c calls dtfft_get_error_string
create_c2c_pencil calls dtfft_get_error_string
create_pencil_init calls dtfft_get_error_string
create_r2c calls dtfft_get_error_string
create_r2c_pencil calls dtfft_get_error_string
create_r2r calls dtfft_get_error_string
create_r2r_pencil calls dtfft_get_error_string
destroy calls dtfft_get_error_string, mem_free_ptr
dtfft_get_error_string_c calls dtfft_get_error_string
execute_autotune calls dtfft_get_error_string, alloc_and_set_aux
get_alloc_bytes calls dtfft_get_error_string, get_element_size, get_alloc_size
get_aux_bytes calls dtfft_get_error_string, get_alloc_bytes
get_aux_bytes_reshape calls dtfft_get_error_string
get_aux_bytes_transpose calls dtfft_get_error_string
get_aux_size calls dtfft_get_error_string, get_aux_bytes, get_element_size
get_aux_size_reshape calls dtfft_get_error_string, get_aux_bytes_reshape, get_element_size
get_aux_size_transpose calls dtfft_get_error_string, get_aux_bytes_transpose, get_element_size
get_backend calls dtfft_get_error_string
get_dims calls dtfft_get_error_string
get_element_size calls dtfft_get_error_string
get_executor calls dtfft_get_error_string
get_grid_dims calls dtfft_get_error_string
get_local_sizes calls dtfft_get_error_string
get_pencil calls dtfft_get_error_string
get_platform calls dtfft_get_error_string
get_precision calls dtfft_get_error_string
get_reshape_backend calls dtfft_get_error_string
get_stream_ptr calls dtfft_get_error_string
get_y_slab_enabled calls dtfft_get_error_string
get_z_slab_enabled calls dtfft_get_error_string
mem_alloc_ptr calls dtfft_get_error_string
mem_free_ptr calls dtfft_get_error_string
report calls dtfft_get_error_string
report_compression calls dtfft_get_error_string
reshape_end calls dtfft_get_error_string
transpose_end calls dtfft_get_error_string
transpose_private calls dtfft_get_error_string, check_aux
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
dtfft_destroy_c calls destroy
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_aux_bytes_c calls get_aux_bytes
dtfft_get_aux_bytes_reshape_c calls get_aux_bytes_reshape
dtfft_get_aux_bytes_transpose_c calls get_aux_bytes_transpose
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_aux_size_reshape_c calls get_aux_size_reshape
dtfft_get_aux_size_transpose_c calls get_aux_size_transpose
dtfft_get_backend_c calls get_backend
dtfft_get_dims_c calls get_dims
dtfft_get_element_size_c calls get_element_size
dtfft_get_executor_c calls get_executor
dtfft_get_grid_dims_c calls get_grid_dims
dtfft_get_local_sizes_c calls get_local_sizes
dtfft_get_pencil_c calls get_pencil
dtfft_get_platform_c calls get_platform
dtfft_get_precision_c calls get_precision
dtfft_get_reshape_backend_c calls get_reshape_backend
dtfft_get_y_slab_enabled_c calls get_y_slab_enabled
dtfft_get_z_slab_enabled_c calls get_z_slab_enabled
dtfft_mem_alloc_c calls mem_alloc_ptr
dtfft_mem_free_c calls mem_free_ptr
dtfft_report_c calls report
dtfft_report_compression_c calls report_compression
dtfft_reshape_end_c calls reshape_end
dtfft_transpose_end_c calls transpose_end
execute_many calls execute_autotune, execute_single
execute_ptr calls check_aux
get_alloc_size calls get_local_sizes
mem_alloc_c32_1d calls mem_alloc_ptr
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_c32_3d calls mem_alloc_ptr
mem_alloc_c64_1d calls mem_alloc_ptr
mem_alloc_c64_2d calls mem_alloc_ptr
mem_alloc_c64_3d calls mem_alloc_ptr
mem_alloc_r32_1d calls mem_alloc_ptr
mem_alloc_r32_2d calls mem_alloc_ptr
mem_alloc_r32_3d calls mem_alloc_ptr
mem_alloc_r64_1d calls mem_alloc_ptr
mem_alloc_r64_2d calls mem_alloc_ptr
mem_alloc_r64_3d calls mem_alloc_ptr
mem_free_c32_1d calls mem_free_ptr
mem_free_c32_2d calls mem_free_ptr
mem_free_c32_3d calls mem_free_ptr
mem_free_c64_1d calls mem_free_ptr
mem_free_c64_2d calls mem_free_ptr
mem_free_c64_3d calls mem_free_ptr
mem_free_r32_1d calls mem_free_ptr
mem_free_r32_2d calls mem_free_ptr
mem_free_r32_3d calls mem_free_ptr
mem_free_r64_1d calls mem_free_ptr
mem_free_r64_2d calls mem_free_ptr
mem_free_r64_3d calls mem_free_ptr
reshape_private calls check_aux
run_execute_single calls execute_autotune
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
dtfft_execute_c calls execute_ptr
dtfft_get_alloc_size_c calls get_alloc_size
dtfft_get_stream_c calls get_stream
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_single_transpose_modes calls run_execute_single
execute calls execute_ptr
get_stream_int64 calls get_stream
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
run_autotune_backend calls execute_many, execute_single
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
autotune_grid calls run_autotune_backend
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
execute_single calls execute_single_transpose_modes
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
autotune_grid_decomposition calls autotune_grid