dtfft_mem_free_c – dtFFT
dtfft_mem_free_c Function
12 statements
Source File
private function dtfft_mem_free_c(plan_ptr, ptr) result(error_code) bind(C)
Frees memory for dtFFT Plan, C/C++ interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
type(c_ptr), value :: ptr
Pointer to deallocate
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_mem_free_c calls is_null_ptr, mem_free
mem_free_c32_1d calls mem_free
mem_free_c32_2d calls mem_free
mem_free_c32_3d calls mem_free
mem_free_c64_1d calls mem_free
mem_free_c64_2d calls mem_free
mem_free_c64_3d calls mem_free
mem_free_ptr calls mem_free_host, mem_free, dtfft_get_error_string, get_log_enabled, write_message
mem_free_r32_1d calls mem_free
mem_free_r32_2d calls mem_free
mem_free_r32_3d calls mem_free
mem_free_r64_1d calls mem_free
mem_free_r64_2d calls mem_free
mem_free_r64_3d calls mem_free
write_message calls mpi_comm_rank, mpi_finalized