dtfft_get_aux_bytes_c – dtFFT
dtfft_get_aux_bytes_c Function
12 statements
Source File
private function dtfft_get_aux_bytes_c(plan_ptr, aux_bytes) result(error_code) bind(C)
Returns minimum number of bytes required for auxiliary buffer, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_size_t), intent(out) :: aux_bytes
Number of bytes required for auxiliary buffer
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_aux_bytes_c calls is_null_ptr, get_aux_bytes
get_aux_bytes calls dtfft_get_error_string, get_aux_size, get_element_size, write_message, get_aux_bytes_generic
get_aux_size calls dtfft_get_error_string, write_message, get_alloc_size, get_aux_bytes, get_aux_size_reshape, is_aux_needed
get_element_size calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
get_alloc_size calls get_local_sizes
get_aux_size_reshape calls dtfft_get_error_string, get_element_size, write_message, get_aux_bytes_reshape
is_aux_needed calls get_aux_bytes
get_aux_bytes_generic calls get_aux_bytes
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_local_sizes calls dtfft_get_error_string, write_message, get_aux_bytes, mpi_allreduce, get_backend, get_local_sizes_internal, get_local_sizes, is_backend_nvshmem
get_local_sizes_internal calls get_local_sizes, counts, starts