dtfft_transpose_end_c – dtFFT
dtfft_transpose_end_c Function
12 statements
Source File
private function dtfft_transpose_end_c(plan_ptr, request) result(error_code) bind(C)
Finishes asynchronous transposition, C interface.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: plan_ptr
C pointer to Fortran plan
type(dtfft_request_t), intent(inout) :: request
Async transpose handle
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_transpose_end_c calls is_null_ptr, transpose_end
transpose_end calls dtfft_get_error_string, execute_end, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
execute_end calls is_null_ptr, pop_nvtx_domain_range, push_nvtx_domain_range, execute_end
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c