dtfft_get_stream_c – dtFFT
dtfft_get_stream_c Function
12 statements
Source File
private function dtfft_get_stream_c(plan_ptr, stream) result(error_code) bind(C)
Returns Stream associated with plan
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
type(dtfft_stream_t), intent(out) :: stream
CUDA stream
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_code_t defines API call result codes.
Calls
Call graph
dtfft_get_stream_c calls is_null_ptr, get_stream
get_stream_int64 calls get_stream, get_cuda_stream
get_stream_ptr calls dtfft_get_error_string, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized