dtfft_report_compression_c – dtFFT
dtfft_report_compression_c Function
11 statements
Source File
private function dtfft_report_compression_c(plan_ptr) result(error_code) bind(C)
Reports compression information for dtFFT Plan, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_report_compression_c calls is_null_ptr, report_compression
report_compression calls dtfft_get_error_string, get_backend, is_backend_compressed, report_compression, write_message, mpi_abort
write_message calls mpi_comm_rank, mpi_finalized