dtfft_get_executor_c – dtFFT
dtfft_get_executor_c Function
12 statements
Source File
private function dtfft_get_executor_c(plan_ptr, executor) result(error_code) bind(C)
Returns executor type used in plan, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
type(dtfft_executor_t), intent(out) :: executor
The enumerated type dtfft_executor_t
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_executor_c calls is_null_ptr, get_executor
get_executor calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized