dtfft_set_config_c – dtFFT
dtfft_set_config_c Function
5 statements
Source File
private function dtfft_set_config_c(config) result(error_code) bind(C)
Sets dtFFT configuration, C interface
Arguments
Type Intent Optional Attributes Name
type(dtfft_config_t), intent(in) :: config
Configuration to set
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_set_config_c calls dtfft_set_config
dtfft_set_config calls cudastreamquery, is_null_ptr, get_correct_backend, init_internal, is_valid_access_mode, is_valid_backend, is_valid_platform, is_valid_transpose_mode
get_correct_backend calls get_conf_platform
init_internal calls mpi_initialized, init_environment
init_environment calls access_modes, destroy, get_env, platforms, destroy_strings, get_backend_from_env, transpose_modes
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_strings calls destroy_string
get_backend_from_env calls is_valid_backend, get_env, destroy_strings, destroy_string, write_message
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls get_env, write_message, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, destroy_string, write_message
write_message calls mpi_comm_rank, mpi_finalized