dtfft_get_y_slab_enabled_c – dtFFT
dtfft_get_y_slab_enabled_c Function
12 statements
Source File
private function dtfft_get_y_slab_enabled_c(plan_ptr, is_y_slab_enabled) result(error_code) bind(C)
Checks if dtFFT Plan is using Y-slab optimization
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: plan_ptr
C pointer to Fortran plan
logical(kind=c_bool), intent(out) :: is_y_slab_enabled
Is plan internally using Y-slab optimization
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_y_slab_enabled_c calls is_null_ptr, get_y_slab_enabled
get_y_slab_enabled calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized