dtfft_get_aux_bytes_transpose_c – dtFFT
dtfft_get_aux_bytes_transpose_c Function
12 statements
Source File
private function dtfft_get_aux_bytes_transpose_c(plan_ptr, aux_bytes) result(error_code) bind(C)
Returns minimum number of bytes required for auxiliary buffer for transpose, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_size_t), intent(out) :: aux_bytes
Number of bytes required for auxiliary buffer for transpose
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_aux_bytes_transpose_c calls is_null_ptr, get_aux_bytes_transpose
get_aux_bytes_transpose calls dtfft_get_error_string, get_aux_bytes, write_message
get_aux_bytes calls get_aux_bytes_generic
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes_generic calls get_aux_bytes