dtfft_get_grid_dims_c – dtFFT
dtfft_get_grid_dims_c Function
18 statements
Source File
private function dtfft_get_grid_dims_c(plan_ptr, ndims, grid_dims) result(error_code) bind(C)
Returns grid decomposition dimensions of plan, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_int8_t), intent(out) :: ndims
Number of dimensions
type(c_ptr), intent(out) :: grid_dims
Array of dimensions
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_grid_dims_c calls is_null_ptr, get_grid_dims
get_grid_dims calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized