dtfft_get_element_size_c – dtFFT
dtfft_get_element_size_c Function
12 statements
Source File
private function dtfft_get_element_size_c(plan_ptr, element_size) result(error_code) bind(C)
Returns size of element in bytes, C/C++ interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_size_t), intent(out) :: element_size
Size of element in bytes
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_element_size_c calls is_null_ptr, get_element_size
get_element_size calls dtfft_get_error_string, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized