dtfft_get_alloc_size_c – dtFFT
dtfft_get_alloc_size_c Function
12 statements
Source File
private function dtfft_get_alloc_size_c(plan_ptr, alloc_size) result(error_code) bind(C)
Returns minimum number of bytes to be allocated for in and out buffers, C interface
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: plan_ptr
C pointer to Fortran plan
integer(kind=c_size_t), intent(out) :: alloc_size
Minimum data needs to be allocated
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_get_alloc_size_c calls is_null_ptr, get_alloc_size
get_alloc_size calls get_local_sizes
get_local_sizes calls mpi_allreduce, dtfft_get_error_string, get_aux_bytes, get_backend, get_local_sizes_internal, get_local_sizes, is_backend_nvshmem, write_message
get_aux_bytes calls get_aux_bytes_generic
get_local_sizes_internal calls get_local_sizes, counts, starts
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes_generic calls get_aux_bytes