dtfft_reshape_start_c – dtFFT
dtfft_reshape_start_c Function
16 statements
Source File
private function dtfft_reshape_start_c(plan_ptr, in, out, reshape_type, aux, request) result(error_code) bind(C)
Starts asynchronous reshape, returns reshape handle, C interface.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: plan_ptr
C pointer to Fortran plan
type(c_ptr), intent(in), value :: in
Incomming pointer, not NULL
type(c_ptr), intent(in), value :: out
Outgoing buffer, not NULL
type(dtfft_reshape_t), intent(in) :: reshape_type
Type of reshape
type(c_ptr), intent(in), value :: aux
Aux buffer, can be NULL
type(dtfft_request_t), intent(out) :: request
Async reshape handle
Return Value integer(kind=c_int32_t)
The enumerated type dtfft_error_t defines API call result codes.
Calls
Call graph
dtfft_reshape_start_c calls is_null_ptr, reshape_start_ptr
reshape_start_ptr calls pop_nvtx_domain_range, push_nvtx_domain_range, reshape_private
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
reshape_private calls check_aux, execute
astring_f2c calls string_f2c
check_aux calls is_null_ptr, to_str, mpi_abort, dtfft_get_error_string, get_alloc_bytes, get_aux_bytes, get_conf_log_enabled, is_aux_needed, mem_alloc_ptr, ptr_offset, write_message
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute calls is_null_ptr, pop_nvtx_domain_range, push_nvtx_domain_range, execute, is_same_ptr
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_alloc_bytes calls dtfft_get_error_string, write_message, get_alloc_size, get_element_size
get_aux_bytes calls dtfft_get_error_string, write_message, get_aux_size, get_element_size, get_aux_bytes_generic
get_conf_log_enabled calls get_conf_internal
is_aux_needed calls get_aux_bytes
mem_alloc_ptr calls is_null_ptr, dtfft_get_error_string, write_message, mem_alloc, mem_alloc_host
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_alloc_size calls get_local_sizes
get_aux_size calls dtfft_get_error_string, is_aux_needed, write_message, get_alloc_size, get_aux_bytes, get_aux_size_reshape
get_element_size calls dtfft_get_error_string, write_message
mem_alloc_host calls aligned_alloc
get_aux_bytes_generic calls get_aux_bytes
get_aux_size_reshape calls dtfft_get_error_string, write_message, get_element_size, get_aux_bytes_reshape
get_local_sizes calls dtfft_get_error_string, write_message, get_aux_bytes, mpi_allreduce, get_backend, get_local_sizes_internal, get_local_sizes, is_backend_nvshmem
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_local_sizes_internal calls get_local_sizes, counts, starts