dynamic_load – dtFFT
dynamic_load Function
23 statements
Source File
public function dynamic_load(name, symbol_names, handle, symbols) result(error_code)
Dynamically loads library and its symbols
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of library to load
type(string), intent(in) :: symbol_names(:)
Names of functions to load
type(c_ptr), intent(out) :: handle
Loaded handle
type(c_funptr), intent(out) :: symbols(:)
Function pointers
Return Value integer(kind=int32)
Error code
Calls
Called by
Call graph
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
is_null_ptr calls is_null_ptr, is_null_funptr
load_library calls is_null_ptr, dlopen, astring_f2c, dl_error
load_symbol calls is_null_ptr, dlsym, mpi_abort, astring_f2c, dl_error, write_message
unload_library calls dlclose, dl_error
astring_f2c calls string_f2c
dl_error calls write_message, dlerror, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
string_c2f calls is_null_ptr
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
init calls load_cuda, load_nvrtc
load_vkfft calls load
test_device_kernels calls load_cuda, load_nvrtc
create calls init, load_vkfft