estimate_coalescing – dtFFT
estimate_coalescing Function
131 statements
Source File
private function estimate_coalescing(dims, tile_dim, other_dim, kernel_type, config, base_storage, neighbor_data) result(score)
Uses
iso_fortran_env
Estimate memory coalescing efficiency for a given kernel configuration and transpose type
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Local dimensions of the input data
integer(kind=int32), intent(in) :: tile_dim
Tile dimension
integer(kind=int32), intent(in) :: other_dim
Other dimension (not tiled)
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel
type(kernel_config), intent(in) :: config
Kernel configuration
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
integer(kind=int32), intent(in), optional :: neighbor_data(:)
Neighboring data dimensions for pipelined kernels
Return Value real(kind=real32)
Coalescing score
Calls
Called by
Call graph
estimate_coalescing calls mpi_abort, write_message
write_message calls mpi_comm_rank, mpi_finalized
evaluate_analytical_performance calls estimate_coalescing
get_kernel calls evaluate_analytical_performance
create calls get_kernel