execute_autotune – dtFFT
execute_autotune Function
202 statements
Source File
public function execute_autotune(plans, comm, backend, platform, helper, stream, buffer_size, report_space_count) result(execution_time)
Uses
iso_fortran_env
iso_c_binding
Executes autotuning for given plans and returns execution time in milliseconds
Arguments
Type Intent Optional Attributes Name
type(reshape_container), intent(inout) :: plans(:)
Allocated plans
type(MPI_Comm), intent(in) :: comm
Communicator
type(dtfft_backend_t), intent(in) :: backend
Backend to use
type(dtfft_platform_t), intent(in) :: platform
Platform used
type(backend_helper), intent(inout) :: helper
Helper to use
type(dtfft_stream_t), intent(in) :: stream
Stream to use
integer(kind=int64), intent(in) :: buffer_size
integer(kind=int32), intent(in), optional :: report_space_count
Return Value real(kind=real32)
Execution time
Calls
Called by
Call graph
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_allreduce, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, write_message, temp
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, nvshmem_free, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring, write_message
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls to_str, mpi_allreduce, mpi_comm_size, get_conf_log_enabled, write_message
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_aux_bytes_generic calls get_aux_bytes
get_conf_log_enabled calls get_conf_internal
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid