execute_f128 – dtFFT
execute_f128 Subroutine
77 statements
Source File
private subroutine execute_f128(self, in, out, neighbor)
Executes kernel based on its type and access mode, complex(real64) version
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(in) :: self
Host kernel class
type(c_ptr), intent(in) :: in
Source host-allocated buffer
type(c_ptr), intent(in) :: out
Target host-allocated buffer
integer(kind=int32), intent(in), optional :: neighbor
Source rank for pipelined unpacking
Calls
Call graph
execute_f128 calls copy_f128, pack_backward_read_f128, pack_backward_write_f128, pack_f128, pack_forward_read_f128, pack_forward_write_f128, pack_pipelined_f128, permute_backward_end_pipelined_read_f128, permute_backward_end_pipelined_write_f128, permute_backward_end_read_f128, permute_backward_end_write_f128, permute_backward_read_f128, permute_backward_start_read_f128, permute_backward_start_write_f128, permute_backward_write_f128, permute_forward_read_f128, permute_forward_write_f128, unpack_backward_pipelined_read_f128, unpack_backward_pipelined_write_f128, unpack_backward_read_f128, unpack_backward_write_f128, unpack_f128, unpack_forward_pipelined_read_f128, unpack_forward_pipelined_write_f128, unpack_forward_read_f128, unpack_forward_write_f128, unpack_pipelined_f128
pack_f128 calls pack_pipelined_f128
permute_backward_end_read_f128 calls permute_backward_end_pipelined_read_f128
permute_backward_end_write_f128 calls permute_backward_end_pipelined_write_f128
unpack_backward_read_f128 calls unpack_backward_pipelined_read_f128
unpack_backward_write_f128 calls unpack_backward_pipelined_write_f128
unpack_f128 calls unpack_pipelined_f128
unpack_forward_read_f128 calls unpack_forward_pipelined_read_f128
unpack_forward_write_f128 calls unpack_forward_pipelined_write_f128