execute_fused – dtFFT
execute_fused Subroutine
88 statements
Source File
private subroutine execute_fused(self, in, out, stream, aux)
Executes FUSED backends (p2p/rma)
Type Bound
backend_mpi
Arguments
Type Intent Optional Attributes Name
class(backend_mpi), intent(inout) :: self
MPI Backend
real(kind=real32), intent(inout), target, contiguous :: in(:)
Send pointer
real(kind=real32), intent(inout), target, contiguous :: out(:)
Recv pointer
type(dtfft_stream_t), intent(in) :: stream
Main execution CUDA stream
real(kind=real32), intent(inout), target, contiguous :: aux(:)
Aux pointer
Calls
Called by
Call graph
execute_fused calls mpi_comm_rank, mpi_irecv, mpi_isend, mpi_waitall, mpi_waitsome, execute_self_copy, execute, ptr_offset
execute_self_copy calls fname, cudaeventrecord, cudamemcpyasync, cudastreamwaitevent, mpi_abort, cudageterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range
execute calls execute_private, mpi_abort, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, sync
compress calls ptr_offset, mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, compress_private, to_str, is_same_ptr
cudageterrorstring calls cudageterrorstring_c, string_c2f
decompress calls ptr_offset, mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, decompress_private, is_same_ptr
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_mpi calls execute_fused