execute_f128_block_64 – dtFFT
execute_f128_block_64 Subroutine
55 statements
Source File
private subroutine execute_f128_block_64(self, in, out, neighbor)
Executes the given kernel on host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(in) :: self
Host kernel class
real(kind=real32), intent(in), target :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout), target :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in), optional :: neighbor
Source rank for pipelined unpacking
Calls
Call graph
execute_f128_block_64 calls pack_f128_block_64, permute_backward_end_pipelined_read_f128_block_64, permute_backward_end_pipelined_write_f128_block_64, permute_backward_end_read_f128_block_64, permute_backward_end_write_f128_block_64, permute_backward_read_f128_block_64, permute_backward_start_read_f128_block_64, permute_backward_start_write_f128_block_64, permute_backward_write_f128_block_64, permute_forward_read_f128_block_64, permute_forward_write_f128_block_64, unpack_f128_block_64, unpack_pipelined_f128_block_64
pack_f128_block_64 calls pack_pipelined_f128_block_64
permute_backward_end_read_f128_block_64 calls permute_backward_end_pipelined_read_f128_block_64
permute_backward_end_write_f128_block_64 calls permute_backward_end_pipelined_write_f128_block_64
unpack_f128_block_64 calls unpack_pipelined_f128_block_64