execute_self_copy – dtFFT
execute_self_copy Subroutine
57 statements
Source File
private subroutine execute_self_copy(self, in, out, stream)
Uses
iso_c_binding
iso_fortran_env
Executes self copy
Type Bound
abstract_backend
Arguments
Type Intent Optional Attributes Name
class(abstract_backend), intent(inout) :: self
Abstract backend
real(kind=real32), intent(in) :: in(:)
Send pointer
real(kind=real32), intent(inout) :: out(:)
Recv pointer
type(dtfft_stream_t), intent(in) :: stream
CUDA stream
Calls
Called by
Call graph
execute_self_copy calls fname, cudaeventrecord, cudamemcpyasync, cudastreamwaitevent, mpi_abort, cudageterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range
cudageterrorstring calls cudageterrorstring_c, string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_fused calls execute_self_copy
execute_mpi calls execute_self_copy, execute_fused, execute_p2p_scheduled
execute_nccl calls execute_self_copy
execute_p2p_scheduled calls execute_self_copy
execute calls execute_self_copy, execute