execute_ptr – dtFFT
execute_ptr Subroutine
18 statements
Source File
private subroutine execute_ptr(self, in, out, execute_type, aux, error_code)
Executes plan using type(c_ptr) pointers instead of buffers
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: in
Incoming pointer. Note that values of this pointer will be modified in GPU build
type(c_ptr), intent(in) :: out
Resulting pointer
type(dtfft_execute_t), intent(in) :: execute_type
Type of execution.
type(c_ptr), intent(in) :: aux
Auxiliary buffer. Not optional. If not required, c_null_ptr must be passed. Size of buffer must be greater than value returned by alloc_size parameter of get_local_sizes subroutine
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
execute_ptr calls check_aux, execute_private, is_same_ptr, pop_nvtx_domain_range, push_nvtx_domain_range
check_aux calls to_str, is_null_ptr, mpi_abort, dtfft_get_error_string, get_alloc_bytes, get_aux_bytes, get_conf_log_enabled, is_aux_needed, mem_alloc_ptr, ptr_offset, write_message
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute_2d calls execute
execute_2d_reshape calls execute
execute_generic calls execute
execute_generic_reshape calls execute
execute_z_slab calls execute_generic, execute
execute_z_slab_reshape calls execute
get_alloc_bytes calls dtfft_get_error_string, write_message, get_alloc_size, get_element_size
get_aux_bytes calls dtfft_get_error_string, write_message, get_aux_size, get_element_size, get_aux_bytes_generic
get_conf_log_enabled calls get_conf_internal
is_aux_needed calls get_aux_bytes
mem_alloc_ptr calls is_null_ptr, dtfft_get_error_string, write_message, mem_alloc, mem_alloc_host
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
execute calls is_same_ptr, pop_nvtx_domain_range, push_nvtx_domain_range, is_null_ptr, execute, execute_ptr
get_alloc_size calls get_local_sizes
get_aux_size calls dtfft_get_error_string, is_aux_needed, write_message, get_alloc_size, get_aux_bytes, get_aux_size_reshape
get_element_size calls dtfft_get_error_string, write_message
mem_alloc_host calls aligned_alloc
get_aux_bytes_generic calls get_aux_bytes
get_aux_size_reshape calls dtfft_get_error_string, write_message, get_element_size, get_aux_bytes_reshape
get_local_sizes calls dtfft_get_error_string, write_message, get_aux_bytes, mpi_allreduce, get_backend, get_local_sizes, get_local_sizes_internal, is_backend_nvshmem
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_local_sizes_internal calls get_local_sizes, counts, starts
dtfft_execute_c calls execute_ptr