execute_f128_block_16 – dtFFT
execute_f128_block_16 Subroutine
53 statements
Source File
private subroutine execute_f128_block_16(self, in, out, neighbor)
Executes the given kernel on host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(in) :: self
Host kernel class
real(kind=real32), intent(in), target :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout), target :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in), optional :: neighbor
Source rank for pipelined unpacking
Calls
Call graph
execute_f128_block_16 calls permute_backward_end_pipelined_read_f128_block_16, permute_backward_end_pipelined_write_f128_block_16, permute_backward_end_read_f128_block_16, permute_backward_end_write_f128_block_16, permute_backward_read_f128_block_16, permute_backward_start_read_f128_block_16, permute_backward_start_write_f128_block_16, permute_backward_write_f128_block_16, permute_forward_read_f128_block_16, permute_forward_write_f128_block_16, unpack_f128_block_16, unpack_pipelined_f128_block_16
permute_backward_end_read_f128_block_16 calls permute_backward_end_pipelined_read_f128_block_16
permute_backward_end_write_f128_block_16 calls permute_backward_end_pipelined_write_f128_block_16
unpack_f128_block_16 calls unpack_pipelined_f128_block_16