execute_many – dtFFT
execute_many Function
58 statements
Source File
private function execute_many(cart_comm, create_kwargs, pencils, helper, is_z_slab, is_y_slab, effort, stream, fmodes, bmodes)
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: cart_comm
3D Cartesian comm
type(create_args), intent(inout) :: create_kwargs
Create arguments
type(pencil), intent(in) :: pencils(:)
Layouts
type(backend_helper), intent(inout) :: helper
logical, intent(in) :: is_z_slab
Is Z-slab optimization enabled
logical, intent(in) :: is_y_slab
Is Y-slab optimization enabled
type(dtfft_effort_t), intent(in) :: effort
Effort level for the plan creation
type(dtfft_stream_t), intent(in) :: stream
Stream to use
type(dtfft_transpose_mode_t), intent(inout) :: fmodes(:)
Best transpose modes for forward plan
type(dtfft_transpose_mode_t), intent(inout) :: bmodes(:)
Best transpose modes for backward plan
Return Value real(kind=real32)
Calls
Called by
Call graph
execute_many calls btimes, ftimes, to_str, allocate_plans, create, destroy_plans, dtfft_get_backend_string, execute_autotune, execute_single, get_conf_log_enabled, get_local_sizes, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
allocate_plans calls write_message, mpi_abort
create calls write_message, create_private, mpi_abort, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, run_autotune_backend, autotune_grid_decomposition
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
execute_single calls dtfft_get_backend_string, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, execute_single_transpose_modes
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls to_str, dtfft_get_backend_string, get_conf_log_enabled, write_message, fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_allreduce, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, temp
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
execute_single_transpose_modes calls run_execute_single
free_mem calls to_str, get_conf_log_enabled, write_message, fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls to_str, get_conf_log_enabled, write_message, mpi_allreduce, mpi_comm_size
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
run_execute_single calls allocate_plans, create, destroy_plans, execute_autotune, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
run_autotune_backend calls execute_many
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid