execute_end – dtFFT
execute_end Subroutine
14 statements
Source File
private subroutine execute_end(self, kwargs, error_code)
Ends execution of transposition
Type Bound
reshape_handle_generic
Arguments
Type Intent Optional Attributes Name
class(reshape_handle_generic), intent(inout) :: self
Generic Transpose Handle
type(execute_args), intent(inout) :: kwargs
Additional arguments
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Call graph
execute_end calls execute_end, execute
execute calls execute_private, mpi_abort, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, sync
compress calls mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, compress_private, to_str, is_same_ptr, ptr_offset
decompress calls mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, decompress_private, is_same_ptr, ptr_offset
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c