execute – dtFFT
execute Subroutine
12 statements
Source File
private subroutine execute(self, in, out, execute_type, aux, error_code)
Executes plan
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(*), intent(inout), target :: in(..)
Incoming buffer of any rank and kind
type(*), intent(inout), target :: out(..)
Resulting buffer of any rank and kind
type(dtfft_execute_t), intent(in) :: execute_type
Type of execution.
type(*), intent(inout), optional, target :: aux(..)
Optional auxiliary buffer. Size of buffer must be greater than value returned by alloc_size parameter of get_local_sizes subroutine
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Call graph
execute calls execute_ptr, pop_nvtx_domain_range, push_nvtx_domain_range, execute_private
execute_ptr calls is_null_ptr, check_aux, check_device_pointers, dtfft_get_error_string, execute_private, get_backend, is_same_ptr, is_valid_execute_type, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
check_aux calls is_null_ptr, dtfft_get_error_string, write_message, to_str, mpi_abort, get_alloc_size, get_conf_log_enabled, get_element_size, mem_alloc_ptr
check_device_pointers calls is_null_ptr, is_device_ptr, is_backend_nvshmem, is_nvshmem_ptr
execute_private calls execute
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_alloc_size calls get_local_sizes
get_conf_log_enabled calls get_conf_internal
get_element_size calls dtfft_get_error_string, write_message
is_nvshmem_ptr calls is_null_ptr, nvshmem_my_pe, nvshmem_ptr
mem_alloc_ptr calls is_null_ptr, dtfft_get_error_string, write_message, mem_alloc, mem_alloc_host
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_local_sizes calls dtfft_get_error_string, get_backend, write_message, is_backend_nvshmem, counts, mpi_allreduce, get_aux_size, get_local_sizes, starts
mem_alloc_host calls aligned_alloc