execute_test – dtFFT
execute_test Subroutine
161 statements
Source File
subroutine execute_test(dims, kernel_type)
Uses
iso_fortran_env
iso_c_binding
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
type(kernel_type_t), intent(in) :: kernel_type
Calls
Called by
Call graph
execute_test calls fname, cudadevicesynchronize, cudafree, cudamalloc, cudamemcpy, mem_free_host, to_str, mpi_abort, create, cudageterrorstring, destroy, execute, get_kernel_string, mem_alloc_host, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create calls mpi_abort, destroy, get_kernel_string, write_message, create_private, is_pack_kernel, is_unpack_kernel
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy calls destroy_private, destroy_string
execute calls mpi_abort, write_message, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, sync
mem_alloc_host calls aligned_alloc
write_message calls mpi_comm_rank, mpi_finalized
compress calls to_str, mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, compress_private, is_same_ptr, ptr_offset
decompress calls mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, decompress_private, is_same_ptr, ptr_offset
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
test_device_kernels calls execute_test