execute – dtFFT
execute Subroutine
143 statements
Source File
private subroutine execute(self, in, out, stream, neighbor, aux, csize, csizes, skip_compression, skip_rank, sync)
Uses
iso_fortran_env
Executes kernel
Type Bound
abstract_kernel
Arguments
Type Intent Optional Attributes Name
class(abstract_kernel), intent(inout) :: self
Abstract kernel
type(c_ptr), intent(in) :: in
Source buffer, can be device or host pointer
type(c_ptr), intent(in) :: out
Target buffer, can be device or host pointer
type(dtfft_stream_t), intent(in) :: stream
Stream to execute on, used only for device pointers
integer(kind=int32), intent(in), optional :: neighbor
Source rank for pipelined unpacking
type(c_ptr), intent(in), optional :: aux
Target buffer, can be device or host pointer
integer(kind=int32), intent(inout), optional :: csize
Compressed buffer size
integer(kind=int32), intent(inout), optional :: csizes(:)
Multiple compression sizes. This should only be used with CUDA backends
logical, intent(in), optional :: skip_compression
Skip compression/decompression stage. Should be used when packing/unpacking from itself.
integer(kind=int32), intent(in), optional :: skip_rank
Skip compression/decompression for specific rank when neighbor is not specified.
logical, intent(in), optional :: sync
Sync stream after packing/compression. Should be used only for fused backends
Calls
Called by
Call graph
execute calls execute_private, mpi_abort, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, sync, execute
compress calls mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, compress_private, to_str, is_same_ptr, ptr_offset
decompress calls mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, decompress_private, is_same_ptr, ptr_offset
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute_end calls execute
execute_fused calls execute
execute_mpi calls execute, execute_fused
execute_nccl calls execute
execute_test calls execute
test_device_kernels calls execute_test