execute – dtFFT
execute Subroutine
47 statements
Source File
private subroutine execute(self, in, out, reshape_type, exec_type, aux, error_code)
Uses
iso_fortran_env
Executes reshape plan
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(inout) :: self
Transposition class
type(c_ptr), intent(in) :: in
Incoming buffer
type(c_ptr), intent(in) :: out
Resulting buffer
integer(kind=int32), intent(in) :: reshape_type
Type of reshape to execute
type(async_exec_t), intent(in) :: exec_type
Type of execution (sync/async)
type(c_ptr), intent(in) :: aux
Optional auxiliary buffer
integer(kind=int32), intent(out), optional :: error_code
Error code
Calls
Called by
Call graph
execute calls execute, get_backend, is_null_ptr, mpi_abort, is_backend_compressed, is_backend_fused, is_backend_pipelined, is_same_ptr, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, execute_ptr
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute_2d calls execute
execute_2d_reshape calls execute
execute_generic calls execute
execute_generic_reshape calls execute
execute_z_slab calls execute, execute_generic
execute_z_slab_reshape calls execute
reshape_private calls execute
transpose_private calls execute
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_ptr calls execute_private
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
dtfft_execute_c calls execute_ptr