execute_f64_block_16 – dtFFT
execute_f64_block_16 Subroutine
73 statements
Source File
private subroutine execute_f64_block_16(self, in, out, neighbor)
Executes the given kernel on host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(in) :: self
Host kernel class
type(c_ptr), intent(in) :: in
Source host-allocated buffer
type(c_ptr), intent(in) :: out
Target host-allocated buffer
integer(kind=int32), intent(in), optional :: neighbor
Source rank for pipelined unpacking
Calls
Call graph
execute_f64_block_16 calls pack_backward_read_f64_block_16, pack_backward_write_f64_block_16, pack_f64_block_16, pack_forward_read_f64_block_16, pack_forward_write_f64_block_16, pack_pipelined_f64_block_16, permute_backward_end_pipelined_read_f64_block_16, permute_backward_end_pipelined_write_f64_block_16, permute_backward_end_read_f64_block_16, permute_backward_end_write_f64_block_16, permute_backward_read_f64_block_16, permute_backward_start_read_f64_block_16, permute_backward_start_write_f64_block_16, permute_backward_write_f64_block_16, permute_forward_read_f64_block_16, permute_forward_write_f64_block_16, unpack_backward_pipelined_read_f64_block_16, unpack_backward_pipelined_write_f64_block_16, unpack_backward_read_f64_block_16, unpack_backward_write_f64_block_16, unpack_f64_block_16, unpack_forward_pipelined_read_f64_block_16, unpack_forward_pipelined_write_f64_block_16, unpack_forward_read_f64_block_16, unpack_forward_write_f64_block_16, unpack_pipelined_f64_block_16
pack_f64_block_16 calls pack_pipelined_f64_block_16
permute_backward_end_read_f64_block_16 calls permute_backward_end_pipelined_read_f64_block_16
permute_backward_end_write_f64_block_16 calls permute_backward_end_pipelined_write_f64_block_16
unpack_backward_read_f64_block_16 calls unpack_backward_pipelined_read_f64_block_16
unpack_backward_write_f64_block_16 calls unpack_backward_pipelined_write_f64_block_16
unpack_f64_block_16 calls unpack_pipelined_f64_block_16
unpack_forward_read_f64_block_16 calls unpack_forward_pipelined_read_f64_block_16
unpack_forward_write_f64_block_16 calls unpack_forward_pipelined_write_f64_block_16