execute_private – dtFFT
execute_private Subroutine
28 statements
Source File
private subroutine execute_private(self, in, out, execute_type, aux, inplace, aux2)
Executes plan with specified auxiliary buffer
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: in
Source pointer
type(c_ptr), intent(in) :: out
Target pointer
type(dtfft_execute_t), intent(in) :: execute_type
Type of execution.
type(c_ptr), intent(in) :: aux
Auxiliary pointer.
logical, intent(in) :: inplace
Inplace execution flag
type(c_ptr), intent(in) :: aux2
Second Auxiliary pointer.
Calls
Called by
Call graph
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
execute_2d calls execute
execute_2d_reshape calls execute
execute_generic calls execute
execute_generic_reshape calls execute
execute_z_slab calls execute_generic, execute
execute_z_slab_reshape calls execute
execute calls execute, get_backend, is_null_ptr, mpi_abort, is_backend_compressed, is_backend_fused, is_backend_pipelined, is_same_ptr, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, execute_ptr
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute_ptr calls execute_private
dtfft_execute_c calls execute_ptr