execute – dtFFT
execute Subroutine
60 statements
Source File
private subroutine execute(self, in, out, execute_type, aux, error_code)
Executes plan
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(*), intent(inout), target :: in(..)
Incoming buffer of any rank and kind
type(*), intent(inout), target :: out(..)
Resulting buffer of any rank and kind
type(dtfft_execute_t), intent(in) :: execute_type
Type of execution.
type(*), intent(inout), optional, target :: aux(..)
Optional auxiliary buffer. Size of buffer must be greater than value returned by alloc_size parameter of get_local_sizes subroutine
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
execute calls check_aux, check_device_pointers, dtfft_get_error_string, execute_private, get_backend, get_log_enabled, is_same_ptr, is_valid_execute_type, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
check_aux calls dtfft_get_error_string, mpi_abort, mem_alloc, get_alloc_size, get_element_size
check_device_pointers calls is_device_ptr, is_null_ptr, is_backend_nvshmem, is_nvshmem_ptr
execute_private calls execute
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_alloc_size calls get_local_sizes
get_element_size calls dtfft_get_error_string, get_log_enabled, write_message
is_nvshmem_ptr calls is_null_ptr, nvshmem_my_pe, nvshmem_ptr
get_local_sizes calls dtfft_get_error_string, get_log_enabled, write_message, is_backend_nvshmem, counts, mpi_allreduce, get_backend, get_local_sizes, starts
mem_alloc_c32_1d calls mem_alloc
mem_alloc_c32_2d calls mem_alloc
mem_alloc_c32_3d calls mem_alloc
mem_alloc_c64_1d calls mem_alloc
mem_alloc_c64_2d calls mem_alloc
mem_alloc_c64_3d calls mem_alloc
mem_alloc_ptr calls dtfft_get_error_string, get_log_enabled, write_message, is_null_ptr, mem_alloc_host, mem_alloc
mem_alloc_r32_1d calls mem_alloc
mem_alloc_r32_2d calls mem_alloc
mem_alloc_r32_3d calls mem_alloc
mem_alloc_r64_1d calls mem_alloc
mem_alloc_r64_2d calls mem_alloc
mem_alloc_r64_3d calls mem_alloc
get_backend calls get_backend
dtfft_execute_c calls execute