execute_mpi – dtFFT
execute_mpi Subroutine
80 statements
Source File
private subroutine execute_mpi(self, in, out, stream, aux, error_code)
Uses
iso_fortran_env
iso_c_binding
Executes MPI backend
Type Bound
backend_mpi
Arguments
Type Intent Optional Attributes Name
class(backend_mpi), intent(inout) :: self
MPI Backend
real(kind=real32), intent(inout), target, contiguous :: in(:)
Send pointer
real(kind=real32), intent(inout), target, contiguous :: out(:)
Recv pointer
type(dtfft_stream_t), intent(in) :: stream
Main execution CUDA stream
real(kind=real32), intent(inout), target, contiguous :: aux(:)
Aux pointer
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Call graph
execute_mpi calls fname, cudastreamsynchronize, mpi_abort, mpi_waitall, mpi_waitsome, mpi_win_fence, cudageterrorstring, execute_a2a, execute_fused, execute_p2p, execute_p2p_scheduled, execute_self_copy, execute
cudageterrorstring calls cudageterrorstring_c, string_c2f
execute_a2a calls mpi_alltoall_init, mpi_alltoallv_init, mpi_start
execute_fused calls mpi_waitall, mpi_waitsome, execute_self_copy, execute, mpi_comm_rank, mpi_irecv, mpi_isend, ptr_offset
execute_p2p calls mpi_recv_init, mpi_send_init, mpi_startall
execute_p2p_scheduled calls execute_self_copy, mpi_sendrecv
execute_self_copy calls fname, mpi_abort, cudageterrorstring, cudaeventrecord, cudamemcpyasync, cudastreamwaitevent, pop_nvtx_domain_range, push_nvtx_domain_range
execute calls mpi_abort, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, sync
compress calls mpi_abort, pop_nvtx_domain_range, ptr_offset, push_nvtx_domain_range, write_message, compress_private, to_str, is_same_ptr
decompress calls mpi_abort, pop_nvtx_domain_range, ptr_offset, push_nvtx_domain_range, write_message, decompress_private, is_same_ptr
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c