execute – dtFFT
execute Subroutine
9 statements
Source File
private subroutine execute(self, in, out, transpose_type)
Executes single transposition
Type Bound
abstract_transpose_plan
Arguments
Type Intent Optional Attributes Name
class(abstract_transpose_plan), intent(inout) :: self
Transposition class
type(*), intent(inout) :: in(..)
Incoming buffer of any rank and kind
type(*), intent(inout) :: out(..)
Resulting buffer of any rank and kind
type(dtfft_transpose_type_t), intent(in) :: transpose_type
Type of transpose
Calls
Called by
Call graph
execute calls execute_private, pop_nvtx_domain_range, push_nvtx_domain_range
push_nvtx_domain_range calls astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c
execute_private calls execute
transpose calls execute
dtfft_execute_c calls execute