execute_p2p_scheduled – dtFFT
execute_p2p_scheduled Subroutine
16 statements
Source File
private subroutine execute_p2p_scheduled(self, in, out)
Executes Scheduled Point-to-Point MPI backend
Type Bound
backend_mpi
Arguments
Type Intent Optional Attributes Name
class(backend_mpi), intent(inout) :: self
MPI Backend
real(kind=real32), intent(in) :: in(:)
Data to be sent
real(kind=real32), intent(inout) :: out(:)
Data to be received
Calls
Called by
Call graph
execute_p2p_scheduled calls mpi_sendrecv, execute_self_copy
execute_self_copy calls fname, cudaeventrecord, cudamemcpyasync, cudastreamwaitevent, mpi_abort, cudageterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range
cudageterrorstring calls cudageterrorstring_c, string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_mpi calls execute_p2p_scheduled