execute_nccl – dtFFT
execute_nccl Subroutine
107 statements
Source File
private subroutine execute_nccl(self, in, out, stream, aux, error_code)
Uses
iso_fortran_env
iso_c_binding
Executes NCCL backend
Type Bound
backend_nccl
Arguments
Type Intent Optional Attributes Name
class(backend_nccl), intent(inout) :: self
NCCL backend
real(kind=real32), intent(inout), target, contiguous :: in(:)
Send pointer
real(kind=real32), intent(inout), target, contiguous :: out(:)
Recv pointer
type(dtfft_stream_t), intent(in) :: stream
Main execution CUDA stream
real(kind=real32), intent(inout), target, contiguous :: aux(:)
Aux pointer
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Call graph
execute_nccl calls crecvs, csends, fname, ncclgroupend, ncclgroupstart, ncclrecv, ncclsend, mpi_abort, mpi_alltoall, execute_self_copy, execute, ncclgeterrorstring
execute_self_copy calls fname, mpi_abort, cudaeventrecord, cudamemcpyasync, cudastreamwaitevent, cudageterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range
execute calls mpi_abort, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, sync
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
compress calls mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, compress_private, to_str, is_same_ptr, ptr_offset
cudageterrorstring calls string_c2f, cudageterrorstring_c
decompress calls mpi_abort, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, decompress_private, is_same_ptr, ptr_offset
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c