execute – dtFFT
execute Subroutine
49 statements
Source File
private subroutine execute(self, in, out, stream, source)
Uses
iso_fortran_env
iso_c_binding
Executes kernel on stream
Type Bound
nvrtc_kernel
Arguments
Type Intent Optional Attributes Name
class(nvrtc_kernel), intent(inout) :: self
nvRTC Compiled kernel class
real(kind=real32), intent(in), target :: in(:)
Source pointer
real(kind=real32), intent(in), target :: out(:)
Target pointer
type(dtfft_stream_t), intent(in) :: stream
CUDA Stream
integer(kind=int32), intent(in), optional :: source
Source rank for pipelined unpacking
Calls
Called by
Call graph
execute calls cudamemcpyasync, int_to_str, mpi_abort, mpi_comm_rank, cudageterrorstring, culaunchkernel, get_contiguous_execution_blocks, execute
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c, string_c2f
culaunchkernel calls run_cuda_kernel
execute_mpi calls execute
execute_nccl calls execute
execute_cuda calls execute
run_autotune_backend calls execute
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid