execute_end – dtFFT
execute_end Subroutine
13 statements
Source File
private subroutine execute_end(self, kwargs, error_code)
Ends execution of transposition
Type Bound
transpose_handle_datatype
Arguments
Type Intent Optional Attributes Name
class(transpose_handle_datatype), intent(inout) :: self
Transpose handle
type(execute_args), intent(inout) :: kwargs
Additional arguments
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Called by
Call graph
execute_end calls mpi_waitall
execute calls execute_end
get_plan_execution_time calls execute
autotune_transpose_id calls get_plan_execution_time
run_autotune_datatypes calls autotune_transpose_id
run_autotune_backend calls run_autotune_datatypes
autotune_grid calls run_autotune_backend
create calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid