execute_private – dtFFT
execute_private Subroutine
67 statements
Source File
private subroutine execute_private(self, in, out, execute_type, aux, inplace)
Executes plan with specified auxiliary buffer
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: in
Source pointer
type(c_ptr), intent(in) :: out
Target pointer
type(dtfft_execute_t), intent(in) :: execute_type
Type of execution.
type(c_ptr), intent(in) :: aux
Auxiliary pointer.
logical, intent(in) :: inplace
Inplace execution flag
Calls
Called by
Call graph
execute_private calls execute
execute calls execute_private, pop_nvtx_domain_range, push_nvtx_domain_range, execute_ptr
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute_ptr calls execute_private
dtfft_execute_c calls execute_ptr