execute_host – dtFFT
execute_host Subroutine
75 statements
Source File
private subroutine execute_host(self, in, out, stream, neighbor)
Executes host kernel
Type Bound
kernel_host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(inout) :: self
Host kernel class
real(kind=real32), intent(in), target :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout), target :: out(:)
Target host-allocated buffer
type(dtfft_stream_t), intent(in) :: stream
Stream to execute on, unused here
integer(kind=int32), intent(in), optional :: neighbor
Source rank for pipelined unpacking
Calls
Call graph
execute_host calls inbuf, outbuf, permute_backward_end_f128, permute_backward_end_f32, permute_backward_end_f64, permute_backward_end_pipelined_f128, permute_backward_end_pipelined_f32, permute_backward_end_pipelined_f64, permute_backward_f128, permute_backward_f32, permute_backward_f64, permute_backward_start_f128, permute_backward_start_f32, permute_backward_start_f64, permute_forward_f128, permute_forward_f32, permute_forward_f64, unpack_f128, unpack_f32, unpack_f64, unpack_pipelined_f128, unpack_pipelined_f32, unpack_pipelined_f64
permute_backward_end_f128 calls permute_backward_end_pipelined_f128
permute_backward_end_f32 calls permute_backward_end_pipelined_f32
permute_backward_end_f64 calls permute_backward_end_pipelined_f64
unpack_f128 calls unpack_pipelined_f128
unpack_f32 calls unpack_pipelined_f32
unpack_f64 calls unpack_pipelined_f64