execute_benchmark – dtFFT
execute_benchmark Subroutine
31 statements
Source File
private subroutine execute_benchmark(self, in, out, n_warmup_iters, n_iters, execution_time)
Uses
iso_fortran_env
Executes benchmark for the given kernel
Type Bound
kernel_host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(inout) :: self
Host kernel class
type(c_ptr), intent(in) :: in
Source host-allocated buffer
type(c_ptr), intent(in) :: out
Target host-allocated buffer
integer(kind=int32), intent(in) :: n_warmup_iters
Number of warmup iterations to perform before testing kernel
integer(kind=int32), intent(in) :: n_iters
Number of iterations to perform when testing kernel
real(kind=real64), intent(out) :: execution_time
Execution time of the selected access
Calls
Called by
Call graph
execute_benchmark calls mpi_abort, mpi_wtime, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create_host calls execute_benchmark, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64
select_access_mode_f128 calls execute_benchmark
select_access_mode_f32 calls execute_benchmark
select_access_mode_f64 calls execute_benchmark