execute_cuda – dtFFT
execute_cuda Subroutine
11 statements
Source File
private subroutine execute_cuda(self, in, out, transpose_type)
Executes single transposition
Type Bound
transpose_plan_cuda
Arguments
Type Intent Optional Attributes Name
class(transpose_plan_cuda), intent(inout) :: self
Transposition class
real(kind=real32), intent(inout) :: in(:)
Incoming buffer
real(kind=real32), intent(inout) :: out(:)
Resulting buffer
type(dtfft_transpose_t), intent(in) :: transpose_type
Type of transpose to execute
Calls
Call graph
execute_cuda calls execute
execute calls execute, cudamemcpyasync, int_to_str, mpi_abort, mpi_comm_rank, cudageterrorstring, culaunchkernel, get_contiguous_execution_blocks
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c, string_c2f
culaunchkernel calls run_cuda_kernel