execute_single_transpose_modes – dtFFT
execute_single_transpose_modes Subroutine
39 statements
Source File
private subroutine execute_single_transpose_modes(base_backend, effort, create_kwargs, helper, from, to, transpose_name_id, fmode, bmode, forward_time, backward_time)
Creates forward and backward transpose plans for backend, specified by create_kwargs, based on source and target data distributions and, executes them DTFFT_MEASURE_ITERS times (4 * DTFFT_MEASURE_ITERS iterations total) + 4 * DTFFT_MEASURE_WARMUP_ITERS warmup iterations
Returns elapsed time for best plans selected
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: base_backend
type(dtfft_effort_t), intent(in) :: effort
type(create_args), intent(inout) :: create_kwargs
type(backend_helper), intent(inout) :: helper
Backend helper
type(pencil), intent(in) :: from
Source meta
type(pencil), intent(in) :: to
Target meta
integer(kind=int8), intent(in) :: transpose_name_id
ID of transpose name (from -3 to 3, except 0)
type(dtfft_transpose_mode_t), intent(out) :: fmode
Best forward plan ID
type(dtfft_transpose_mode_t), intent(out) :: bmode
Best backward plan ID
real(kind=real32), intent(out) :: forward_time
Forward plan execution time
real(kind=real32), intent(out) :: backward_time
Backward plan execution time
Calls
Called by
Call graph
execute_single_transpose_modes calls run_execute_single
run_execute_single calls allocate_plans, create, destroy_plans, execute_autotune, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
allocate_plans calls write_message, mpi_abort
create calls write_message, create_private, mpi_abort, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, run_autotune_backend, autotune_grid_decomposition
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls get_conf_log_enabled, write_message, fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_allreduce, dtfft_get_backend_string, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, temp
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls get_conf_log_enabled, write_message, fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls get_conf_log_enabled, write_message, to_str, mpi_allreduce, mpi_comm_size
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_single calls execute_single_transpose_modes
execute_many calls execute_single
run_autotune_backend calls execute_single, execute_many
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid