execute_single – dtFFT
execute_single Subroutine
40 statements
Source File
private subroutine execute_single(base_backend, effort, create_kwargs, helper, pencils, is_z_slab, is_y_slab, fmodes, bmodes, ftimes, btimes, phase_created)
Executes autotuning over all single transpose plans and returns best transpose modes and their execution times
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: base_backend
Backend to test
type(dtfft_effort_t), intent(in) :: effort
Effort level for the plan creation
type(create_args), intent(inout) :: create_kwargs
Create arguments
type(backend_helper), intent(inout) :: helper
Base MPI_Datatype
type(pencil), intent(in) :: pencils(:)
Pencils metadata
logical, intent(in) :: is_z_slab
Is Z-slab optimization enabled
logical, intent(in) :: is_y_slab
Is Y-slab optimization enabled
type(dtfft_transpose_mode_t), intent(inout) :: fmodes(:)
Best transpose modes for forward plan
type(dtfft_transpose_mode_t), intent(inout) :: bmodes(:)
Best transpose modes for backward plan
real(kind=real32), intent(out) :: ftimes(:)
Elapsed time for best forward plans selected in [ms]
real(kind=real32), intent(out) :: btimes(:)
Elapsed time for best backward plans selected in [ms]
logical, intent(in), optional :: phase_created
Whether caliper phase was created
Calls
Called by
Call graph
execute_single calls dtfft_get_backend_string, execute_single_transpose_modes, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
execute_single_transpose_modes calls run_execute_single
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
run_execute_single calls get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, allocate_plans, create, destroy_plans, execute_autotune
allocate_plans calls write_message, mpi_abort
create calls write_message, create_private, mpi_abort, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, run_autotune_backend, autotune_grid_decomposition
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls dtfft_get_backend_string, get_conf_log_enabled, write_message, fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_allreduce, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, temp
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls get_conf_log_enabled, write_message, fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls get_conf_log_enabled, write_message, to_str, mpi_allreduce, mpi_comm_size
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_many calls execute_single
run_autotune_backend calls execute_single, execute_many
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid