float_to_string – dtFFT
float_to_string Function
7 statements
Source File
private function float_to_string(n) result(str)
Convert double to string
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: n
Double to convert
Return Value character(len=:), allocatable
Resulting string
Called by
Call graph
to_str calls float_to_string
add calls to_str
alloc_mem calls to_str
autotune_grid calls to_str, create_pencils_and_comm, run_autotune_backend
check_aux calls to_str
compile_program calls to_str, set_name_expression
compress calls to_str
create_cart_comm calls to_str
create_host calls to_str, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64, select_kernel
create_nvrtc_module calls to_str, add, create
create_pencil_init calls to_str
create calls to_str, autotune_grid_decomposition, create_pencils_and_comm, run_autotune_backend, autotune_reshape_plan, get_kernel, make_plan, compile_program
destroy calls to_str
execute_many calls to_str, execute_autotune, execute_single
execute_test calls to_str, execute
execute calls to_str, compress, execute_ptr, execute
free_mem calls to_str
get_grid_str calls to_str
get_kernel calls to_str, create_nvrtc_module, get_kernel_instance
get_kernel_instance calls to_str, get
get_name_expression calls to_str
make_plan calls to_str
mem_alloc calls to_str, alloc_mem
mem_free calls to_str, free_mem
report calls to_str, get_grid_str
report_compression calls to_str
report_timings calls to_str
select_access_mode_f128 calls to_str
select_access_mode_f32 calls to_str
select_access_mode_f64 calls to_str
select_kernel calls to_str
test_transpose calls to_str, execute
alloc_and_set_aux calls alloc_mem
autotune_grid_decomposition calls autotune_grid
create_pencils_and_comm calls create_cart_comm
dtfft_report_c calls report
execute_autotune calls alloc_mem, free_mem, report_timings, alloc_and_set_aux
execute_ptr calls check_aux
get_mangled_name calls get_name_expression
reshape_private calls check_aux
run_autotune_backend calls execute_many, execute_single
set_name_expression calls get_name_expression
transpose_private calls check_aux
test_compression calls test_transpose, test_pack_unpack
test_device_kernels calls execute_test
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
dtfft_execute_c calls execute_ptr
execute_end calls execute
execute_fused calls execute
execute_mpi calls execute, execute_fused
execute_nccl calls execute
get calls get_mangled_name
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
run_execute_single calls execute_autotune
test_pack_unpack calls execute
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_single_transpose_modes calls run_execute_single
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
execute_single calls execute_single_transpose_modes