free_datatypes – dtFFT
free_datatypes Subroutine
11 statements
Source File
private subroutine free_datatypes(t1, t2, t3, t4)
Frees temporary datatypes
Arguments
Type Intent Optional Attributes Name
type(MPI_Datatype), intent(inout), optional :: t1
Temporary datatype
type(MPI_Datatype), intent(inout), optional :: t2
Temporary datatype
type(MPI_Datatype), intent(inout), optional :: t3
Temporary datatype
type(MPI_Datatype), intent(inout), optional :: t4
Temporary datatype
Calls
Called by
Call graph
free_datatypes calls mpi_type_free
create_transpose_2d calls free_datatypes
create_transpose_xy calls free_datatypes
create_transpose_xz calls free_datatypes
create_transpose_yz calls free_datatypes
create_transpose_zx calls free_datatypes
create calls create_transpose_2d, create_transpose_xy, create_transpose_xz, create_transpose_yz, create_transpose_zx
get_plan_execution_time calls create
autotune_grid calls get_plan_execution_time, autotune_mpi_datatypes
autotune_transpose_id calls get_plan_execution_time
autotune_grid_decomposition calls autotune_grid
autotune_mpi_datatypes calls autotune_transpose_id
create_private calls autotune_grid, autotune_grid_decomposition