free_mem – dtFFT
free_mem Subroutine
46 statements
Source File
private subroutine free_mem(platform, helper, backend, ptr, error_code)
Uses
iso_fortran_env
iso_c_binding
Frees memory based on backend
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
type(backend_helper), intent(inout) :: helper
Backend helper
type(dtfft_backend_t), intent(in) :: backend
GPU backend
type(c_ptr), intent(in) :: ptr
Pointer to the memory to free
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Called by
Call graph
free_mem calls fname, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, mpi_abort, nvshmem_free, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_conf_log_enabled calls get_conf_internal
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
execute_autotune calls free_mem
mem_free calls free_mem
autotune_reshape_plan calls execute_autotune
get_plan_execution_time calls execute_autotune
run_autotune_backend calls execute_autotune, run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_transpose_id calls get_plan_execution_time
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid
run_autotune_datatypes calls autotune_transpose_id