from_bricks – dtFFT
from_bricks Function
192 statements
Source File
private function from_bricks(self, platform, bricks, comm) result(error_code)
Type Bound
pencil_init
Arguments
Type Intent Optional Attributes Name
class(pencil_init), intent(inout) :: self
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for
type(pencil_init), intent(in) :: bricks
type(MPI_Comm), intent(in) :: comm
MPI Communicator passed to plan constructors
Return Value integer(kind=int32)
Error code
Calls
Call graph
from_bricks calls dims3d, mpi_allreduce, mpi_bcast, mpi_cart_create, mpi_cart_get, mpi_cart_sub, mpi_cartdim_get, mpi_comm_dup, mpi_comm_free, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_dims_create, mpi_topo_test, periods, create, destroy_pencil_init, get_conf_log_enabled, write_message, remain_dims, temp_coords, temp_dims, temp_periods
create calls mpi_comm_size, mpi_allgather, check_if_even, destroy, get_local_size
destroy_pencil_init calls mpi_comm_free
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
check_if_even calls mpi_comm_size, mpi_allgather
get_local_size calls mpi_comm_rank, mpi_comm_size, mpi_allgather