generate_candidates – dtFFT
generate_candidates Subroutine
99 statements
Source File
public subroutine generate_candidates(dims, tile_dim, other_dim, base_storage, props, candidates, num_candidates)
Generate kernel configuration candidates for given problem
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Local dimensions of the input data, always 3D
integer(kind=int32), intent(in) :: tile_dim
Tile dimension
integer(kind=int32), intent(in) :: other_dim
Other dimension (not tiled)
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(device_props), intent(in) :: props
GPU architecture properties
type(kernel_config), intent(out) :: candidates(:)
Generated kernel configurations
integer(kind=int32), intent(out) :: num_candidates
Number of generated candidates
Calls
Called by
Call graph
generate_candidates calls estimate_memory_pressure, estimate_optimal_padding, find_valid_combination
estimate_optimal_padding calls count_bank_conflicts
get_kernel calls generate_candidates
create calls get_kernel