get – dtFFT
get Function
49 statements
Source File
private function get(self, ndims, kernel_type, base_storage, tile_size, block_rows, fun) result(ierr)
Uses
iso_fortran_env
iso_c_binding
Returns kernel ready to be executed
Type Bound
nvrtc_module
Arguments
Type Intent Optional Attributes Name
class(nvrtc_module), intent(in) :: self
This module
integer(kind=int32), intent(in) :: ndims
Number of dimensions, used only for forward permutation
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
integer(kind=int32), intent(in) :: tile_size
Size of shared memory tile, template parameter
integer(kind=int32), intent(in) :: block_rows
Number of rows processed by single thread, template parameter
type(CUfunction), intent(out) :: fun
Resulting kernel
Return Value integer(kind=int32)
Calls
Called by
Call graph
get calls fname, mpi_abort, check, cudageterrorstring, get_mangled_name, write_message
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_mangled_name calls fname, mpi_abort, get_name_expression, nvrtcgeterrorstring
write_message calls mpi_comm_rank, mpi_finalized
check_instance calls check
get_name_expression calls to_str, astring_f2c
nvrtcgeterrorstring calls string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
get_kernel_instance calls get
get_kernel calls get_kernel_instance
create calls get_kernel