get_conf_compression_enabled – dtFFT
get_conf_compression_enabled Function
4 statements
Source File
public elemental function get_conf_compression_enabled() result(bool)
Whether compression is enabled or not
Arguments
None
Return Value logical
Result flag
Calls
Called by
Call graph
get_conf_compression_enabled calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
autotune_reshape_plan calls get_conf_compression_enabled
init calls get_conf_compression_enabled
run_autotune_backend calls get_conf_compression_enabled
autotune_grid calls run_autotune_backend
create calls init, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
autotune_grid_decomposition calls autotune_grid