get_aux_size_reshape – dtFFT
get_aux_size_reshape Function
13 statements
Source File
private function get_aux_size_reshape(self, error_code)
Returns minimum number of elements required for reshape auxiliary buffer
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value integer(kind=int64)
Calls
Called by
Call graph
get_aux_size_reshape calls dtfft_get_error_string, get_aux_bytes_reshape, get_element_size, write_message
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_element_size calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes calls get_aux_bytes_generic
get_aux_bytes_generic calls get_aux_bytes
dtfft_get_aux_size_reshape_c calls get_aux_size_reshape