get_conf_rma_enabled – dtFFT
get_conf_rma_enabled Function
4 statements
Source File
public elemental function get_conf_rma_enabled() result(bool)
Whether RMA backends are enabled or not
Arguments
None
Return Value logical
Result flag
Called by
Call graph
autotune_reshape_plan calls get_conf_rma_enabled
run_autotune_backend calls get_conf_rma_enabled
autotune_grid calls run_autotune_backend
create calls run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
autotune_grid_decomposition calls autotune_grid