get_permutations – dtFFT
get_permutations Subroutine
29 statements
Source File
private subroutine get_permutations(ndims, dperm, cperm)
Returns data and communicator permutations for given number of dimensions
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: ndims
Number of dimensions
integer(kind=int8), intent(out), allocatable :: dperm(:,:)
Data permutations
integer(kind=int8), intent(out), allocatable :: cperm(:,:)
Communicator permutations
Called by
Call graph
autotune_grid calls get_permutations, create_pencils_and_comm
create_pencils_and_comm calls get_permutations
autotune_grid_decomposition calls autotune_grid
create calls create_pencils_and_comm, autotune_grid_decomposition