get_aux_bytes – dtFFT
get_aux_bytes Function
4 statements
Source File
private pure function get_aux_bytes(self)
Returns number of bytes required by aux buffer
Type Bound
abstract_reshape_handle
Arguments
Type Intent Optional Attributes Name
class(abstract_reshape_handle), intent(in) :: self
Abstract reshape Handle
Return Value integer(kind=int64)
Called by
Call graph
get_aux_bytes_generic calls get_aux_bytes
alloc_and_set_aux calls get_aux_bytes_generic
get_aux_bytes calls get_aux_bytes_generic, get_aux_size
execute_autotune calls alloc_and_set_aux
get_aux_bytes_reshape calls get_aux_bytes
get_aux_size calls get_aux_bytes, is_aux_needed, get_alloc_size, get_aux_size_reshape
get_local_sizes calls get_aux_bytes
is_aux_needed calls get_aux_bytes
autotune_reshape_plan calls execute_autotune
check_aux calls is_aux_needed, get_aux_bytes, get_alloc_bytes
dtfft_get_aux_bytes_reshape_c calls get_aux_bytes_reshape
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_local_sizes_c calls get_local_sizes
get_alloc_size calls get_local_sizes
get_aux_size_reshape calls get_aux_bytes_reshape
get_plan_execution_time calls execute_autotune
run_autotune_backend calls execute_autotune, run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_transpose_id calls get_plan_execution_time
create calls run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
dtfft_get_alloc_size_c calls get_alloc_size
dtfft_get_aux_bytes_c calls get_aux_bytes
dtfft_get_aux_size_reshape_c calls get_aux_size_reshape
execute_ptr calls check_aux
get_alloc_bytes calls get_alloc_size
reshape_private calls check_aux
transpose_private calls check_aux
autotune_grid_decomposition calls autotune_grid
dtfft_execute_c calls execute_ptr
dtfft_get_alloc_bytes_c calls get_alloc_bytes
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
run_autotune_datatypes calls autotune_transpose_id
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr