get_env_string – dtFFT
get_env_string Function
28 statements
Source File
private function get_env_string(name, default, valid_values) result(env)
Obtains string environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
character(len=*), intent(in) :: default
Name of environment variable without prefix
type(string), intent(in) :: valid_values(:)
List of valid variable values
Return Value character(len=:), allocatable
Environment variable value
Calls
Called by
Call graph
get_env_string calls get_env, get_log_enabled, write_message
get_env calls get_env_string, get_env_base, get_env_int32, get_env_int8, get_env_logical
write_message calls mpi_comm_rank, mpi_finalized
get_env_int32 calls get_env, get_log_enabled, write_message
get_env_int8 calls get_env
get_env_logical calls get_env
create_helper calls get_env
get_datatype_from_env calls get_env
get_iters_from_env calls get_env
init_internal calls get_env
check_create_args calls init_internal
create_cuda calls create_helper, run_autotune_backend, autotune_grid_decomposition
create_private calls get_datatype_from_env, autotune_grid, autotune_grid_decomposition, check_create_args
get_plan_execution_time calls get_iters_from_env
run_autotune_backend calls create_helper, get_iters_from_env
autotune_grid calls run_autotune_backend, get_plan_execution_time, autotune_mpi_datatypes
autotune_transpose_id calls get_plan_execution_time
autotune_grid_decomposition calls autotune_grid
autotune_mpi_datatypes calls autotune_transpose_id
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c calls create_c2c_core
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal