get_gpu_backend – dtFFT
get_gpu_backend Function
11 statements
Source File
private function get_gpu_backend(self, error_code)
Returns selected GPU backend during autotuning
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value type(dtfft_gpu_backend_t)
Calls
Called by
Call graph
get_gpu_backend calls get_gpu_backend
dtfft_get_gpu_backend_c calls get_gpu_backend
get_local_sizes calls get_gpu_backend
dtfft_get_local_sizes_c calls get_local_sizes
get_alloc_size calls get_local_sizes
check_aux calls get_alloc_size
dtfft_get_alloc_size_c calls get_alloc_size
execute calls check_aux
dtfft_execute_c calls execute