get_conf_log_enabled – dtFFT
get_conf_log_enabled Function
4 statements
Source File
public elemental function get_conf_log_enabled() result(bool)
Whether logging is enabled or not
Arguments
None
Return Value logical
Result flag
Calls
Called by
Call graph
get_conf_log_enabled calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
add calls get_conf_log_enabled
alloc_mem calls get_conf_log_enabled
autotune_adaptive calls get_conf_log_enabled, execute_autotune
autotune_grid calls get_conf_log_enabled, run_autotune_backend
autotune_grid_decomposition calls get_conf_log_enabled, autotune_grid
autotune_reshape_plan calls get_conf_log_enabled, autotune_adaptive, execute_autotune
check_aux calls get_conf_log_enabled
create_host calls get_conf_log_enabled, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64
create_nvrtc_module calls get_conf_log_enabled, add, create
create calls get_conf_log_enabled, autotune_grid_decomposition, run_autotune_backend, autotune_reshape_plan, get_kernel
execute_many calls get_conf_log_enabled, execute_single, execute_autotune
execute_single calls get_conf_log_enabled, execute_single_transpose_modes
free_mem calls get_conf_log_enabled
from_bricks calls get_conf_log_enabled
get_kernel calls get_conf_log_enabled, create_nvrtc_module, get_kernel_instance
get_kernel_instance calls get_conf_log_enabled
report_compression calls get_conf_log_enabled
report_timings calls get_conf_log_enabled
run_execute_single calls get_conf_log_enabled, execute_autotune
select_access_mode_f128 calls get_conf_log_enabled
select_access_mode_f32 calls get_conf_log_enabled
select_access_mode_f64 calls get_conf_log_enabled
alloc_and_set_aux calls alloc_mem
execute_autotune calls alloc_mem, free_mem, report_timings, alloc_and_set_aux
execute_ptr calls check_aux
execute_single_transpose_modes calls run_execute_single
mem_alloc calls alloc_mem
mem_free calls free_mem
reshape_private calls check_aux
run_autotune_backend calls execute_many, execute_single
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr