get_z_slab_enabled – dtFFT
get_z_slab_enabled Function
15 statements
Source File
private function get_z_slab_enabled(self, error_code)
Returns logical value is Z-slab optimization enabled internally
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value logical
Calls
Called by
Call graph
get_z_slab_enabled calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_get_z_slab_enabled_c calls get_z_slab_enabled