get_kernel_instance – dtFFT
get_kernel_instance Function
33 statements
Source File
public function get_kernel_instance(ndims, kernel_type, base_storage, tile_size, block_rows) result(fun)
Uses
iso_fortran_env
Retrieves a kernel instance from the cache If the instance is not found, an error is raised
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: ndims
Number of dimensions (2 or 3)
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
integer(kind=int32), intent(in) :: tile_size
Tile size (number of columns)
integer(kind=int32), intent(in) :: block_rows
Block rows
Return Value type(CUfunction)
Retrieved kernel instance
Calls
Called by
Call graph
get_kernel_instance calls to_str, mpi_abort, get, get_conf_log_enabled, get_kernel_string, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get calls mpi_abort, write_message, fname, check, cudageterrorstring, get_mangled_name
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_mangled_name calls mpi_abort, fname, get_name_expression, nvrtcgeterrorstring
check_instance calls check
get_name_expression calls to_str, astring_f2c
nvrtcgeterrorstring calls string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
astring_f2c calls string_f2c
get_kernel calls get_kernel_instance
create calls get_kernel