get_transpose_type – dtFFT
get_transpose_type Function
19 statements
Source File
public pure function get_transpose_type(send, recv) result(transpose_type)
Determines transpose ID based on pencils
Arguments
Type Intent Optional Attributes Name
type(pencil), intent(in) :: send
Send pencil
type(pencil), intent(in) :: recv
Receive pencil
Return Value type(dtfft_transpose_t)
Transpose ID
Called by
Call graph
create calls get_transpose_type, create_reshape_plans, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
create_reshape_plans calls create
execute_many calls create, execute_single
run_execute_single calls create
autotune_adaptive calls create_reshape_plans
autotune_reshape_plan calls create_reshape_plans, autotune_adaptive
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid