get_user_platform – dtFFT
get_user_platform Function
4 statements
Source File
public function get_user_platform()
Returns platform set by the user or default one
Arguments
None
Return Value type(dtfft_platform_t)
Calls
Called by
Call graph
get_user_platform calls get_platform_from_env
check_create_args calls get_user_platform
create calls get_user_platform
create_private calls check_create_args, create
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal
r2r_constructor calls create_r2r
dtfft_plan_r2r_t calls r2r_constructor
c2c_constructor calls create_generic_c2c
dtfft_plan_c2c_t calls c2c_constructor