get_local_sizes – dtFFT
get_local_sizes Subroutine
25 statements
Source File
public subroutine get_local_sizes(pencils, in_starts, in_counts, out_starts, out_counts, alloc_size, is_y_slab)
Obtain local starts and counts in real and fourier spaces
Arguments
Type Intent Optional Attributes Name
type(pencil), intent(in) :: pencils(:)
Array of pencils
integer(kind=int32), intent(out), optional :: in_starts(:)
Start indexes in real space (0-based)
integer(kind=int32), intent(out), optional :: in_counts(:)
Number of elements in real space
integer(kind=int32), intent(out), optional :: out_starts(:)
Start indexes in fourier space (0-based)
integer(kind=int32), intent(out), optional :: out_counts(:)
Number of elements in fourier space
integer(kind=int64), intent(out), optional :: alloc_size
Minimal number of elements required to execute plan
logical, intent(in), optional :: is_y_slab
Is Y-slab optimization used
Called by
Call graph
create calls get_local_sizes, run_autotune_backend, autotune_grid_decomposition
get_local_sizes calls get_local_sizes, get_local_sizes_internal
get_local_sizes_internal calls get_local_sizes
run_autotune_backend calls get_local_sizes
autotune_grid calls run_autotune_backend
dtfft_get_local_sizes_c calls get_local_sizes
get_alloc_size calls get_local_sizes
autotune_grid_decomposition calls autotune_grid
dtfft_get_alloc_size_c calls get_alloc_size
get_alloc_bytes calls get_alloc_size
get_aux_size calls get_alloc_size
check_aux calls get_alloc_bytes, get_aux_bytes
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_aux_size_c calls get_aux_size
get_aux_bytes calls get_aux_size
dtfft_get_aux_bytes_c calls get_aux_bytes
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr