get_stream_int64 – dtFFT
get_stream_int64 Subroutine
10 statements
Source File
private subroutine get_stream_int64(self, stream, error_code)
Returns CUDA stream associated with plan
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int64), intent(out) :: stream
CUDA-Fortran Stream
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
get_stream_int64 calls get_stream, get_cuda_stream
get_stream_ptr calls dtfft_get_error_string, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_get_stream_c calls get_stream