get_conf_z_slab_enabled – dtFFT
get_conf_z_slab_enabled Function
4 statements
Source File
public elemental function get_conf_z_slab_enabled() result(bool)
Whether Z-slab optimization is enabled or not
Arguments
None
Return Value logical
Result flag
Calls
Called by
Call graph
get_conf_z_slab_enabled calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
create calls get_conf_z_slab_enabled