get_z_slab – dtFFT
get_z_slab Function
4 statements
Source File
public pure function get_z_slab()
Whether Z-slab optimization is enabled or not
Arguments
None
Return Value logical
Calls
Called by
Call graph
get_z_slab calls get_z_slab_from_env
create calls get_z_slab
create_private calls create
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal