get_iters_from_env – dtFFT
get_iters_from_env Function
8 statements
Source File
public function get_iters_from_env(is_warmup) result(n_iters)
Obtains number of iterations from environment variable
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: is_warmup
Warmup variable flag
Return Value integer(kind=int32)
Calls
Called by
Call graph
get_iters_from_env calls get_env
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
get_env_int32 calls get_env, get_log_enabled, write_message
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized
get_plan_execution_time calls get_iters_from_env
run_autotune_backend calls get_iters_from_env
autotune_grid calls run_autotune_backend, get_plan_execution_time, autotune_mpi_datatypes
autotune_transpose_id calls get_plan_execution_time
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid
autotune_mpi_datatypes calls autotune_transpose_id
create_private calls autotune_grid, autotune_grid_decomposition