get_transpose_kernel_code – dtFFT
get_transpose_kernel_code Function
100 statements
Source File
public function get_transpose_kernel_code(kernel_name, ndims, base_storage, transpose_type, enable_packing, padding) result(code)
Generates code that will be used to locally tranpose data and prepares to send it to other processes ndims == 2
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: kernel_name
Name of CUDA kernel
integer(kind=int8), intent(in) :: ndims
Number of dimensions
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(dtfft_transpose_t), intent(in) :: transpose_type
Transpose id
logical, intent(in) :: enable_packing
If data should be manually packed or not
integer(kind=int32), intent(in) :: padding
Return Value type(kernel_codegen)
Resulting code
Calls
Called by
Call graph
get_transpose_kernel_code calls to_str, add_line, get_code_init, get_neighbor_function_code
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_code_init calls add_line
get_neighbor_function_code calls add_line
get_transpose_kernel calls get_transpose_kernel_code
get_kernel calls get_transpose_kernel
create calls get_kernel, create