get_backend – dtFFT
get_backend Function
4 statements
Source File
private function get_backend(self)
Returns plan backend
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(in) :: self
Reshape class
Return Value type(dtfft_backend_t)
Called by
Call graph
create_private calls get_backend
get_backend calls get_backend
get_reshape_backend calls get_backend
report calls get_backend
report_compression calls get_backend
create_c2c_core calls create_private
create_r2r_internal calls create_private
dtfft_get_backend_c calls get_backend
dtfft_get_reshape_backend_c calls get_reshape_backend
dtfft_report_c calls report
dtfft_report_compression_c calls report_compression
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal