get_aux_bytes_transpose – dtFFT
get_aux_bytes_transpose Function
15 statements
Source File
private function get_aux_bytes_transpose(self, error_code)
Returns minimum number of bytes required for transpose auxiliary buffer
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value integer(kind=int64)
Calls
Called by
Call graph
get_aux_bytes_transpose calls dtfft_get_error_string, get_aux_bytes, write_message
get_aux_bytes calls get_aux_bytes_generic
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes_generic calls get_aux_bytes
dtfft_get_aux_bytes_transpose_c calls get_aux_bytes_transpose
get_aux_size_transpose calls get_aux_bytes_transpose
dtfft_get_aux_size_transpose_c calls get_aux_size_transpose