get_aux_size – dtFFT
get_aux_size Function
4 statements
Source File
private pure function get_aux_size(self)
Returns number of bytes required by aux buffer
Type Bound
abstract_transpose_handle
Arguments
Type Intent Optional Attributes Name
class(abstract_transpose_handle), intent(in) :: self
Abstract Transpose Handle
Return Value integer(kind=int64)
Called by
Call graph
get_aux_size_generic calls get_aux_size
alloc_and_set_aux calls get_aux_size_generic
get_aux_size calls get_aux_size_generic
create calls alloc_and_set_aux, run_autotune_backend, autotune_grid_decomposition
get_local_sizes calls get_aux_size
run_autotune_backend calls alloc_and_set_aux
autotune_grid calls run_autotune_backend
dtfft_get_local_sizes_c calls get_local_sizes
get_alloc_size calls get_local_sizes
autotune_grid_decomposition calls autotune_grid
check_aux calls get_alloc_size
dtfft_get_alloc_size_c calls get_alloc_size
get_alloc_bytes calls get_alloc_size
dtfft_get_alloc_bytes_c calls get_alloc_bytes
execute_ptr calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr