get_gpu_backend – dtFFT
get_gpu_backend Function
4 statements
Source File
private function get_gpu_backend(self)
Returns plan GPU backend
Type Bound
abstract_transpose_plan
Arguments
Type Intent Optional Attributes Name
class(abstract_transpose_plan), intent(in) :: self
Transposition class
Return Value type(dtfft_gpu_backend_t)
Called by
Call graph
execute calls get_gpu_backend, check_aux
get_gpu_backend calls get_gpu_backend
report calls get_gpu_backend
transpose calls get_gpu_backend
dtfft_execute_c calls execute
dtfft_get_gpu_backend_c calls get_gpu_backend
dtfft_report_c calls report
get_local_sizes calls get_gpu_backend
dtfft_get_local_sizes_c calls get_local_sizes
get_alloc_size calls get_local_sizes
check_aux calls get_alloc_size
dtfft_get_alloc_size_c calls get_alloc_size