get_local_sizes – dtFFT
get_local_sizes Subroutine
57 statements
Source File
private subroutine get_local_sizes(self, in_starts, in_counts, out_starts, out_counts, alloc_size, error_code)
Obtain local starts and counts in real and fourier spaces
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: in_starts(:)
Starts of local portion of data in real space (0-based)
integer(kind=int32), intent(out), optional :: in_counts(:)
Number of elements of local portion of data in ‘real’ space
integer(kind=int32), intent(out), optional :: out_starts(:)
Starts of local portion of data in fourier space (0-based)
integer(kind=int32), intent(out), optional :: out_counts(:)
Number of elements of local portion of data in fourier space
integer(kind=int64), intent(out), optional :: alloc_size
Minimal number of elements required to execute plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
get_local_sizes calls mpi_allreduce, dtfft_get_error_string, get_aux_bytes, get_backend, get_local_sizes_internal, get_local_sizes, is_backend_nvshmem, write_message
get_aux_bytes calls get_aux_bytes_generic, get_aux_size
get_local_sizes_internal calls get_local_sizes, counts, starts
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes_generic calls get_aux_bytes
dtfft_get_local_sizes_c calls get_local_sizes
get_alloc_size calls get_local_sizes
dtfft_get_alloc_size_c calls get_alloc_size
get_alloc_bytes calls get_alloc_size
get_aux_size calls get_alloc_size
check_aux calls get_alloc_bytes, get_aux_bytes
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_aux_bytes_c calls get_aux_bytes
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr