get_aux_bytes – dtFFT
get_aux_bytes Function
6 statements
Source File
private pure function get_aux_bytes(self)
Returns maximum auxiliary memory size needed by reshape plan
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(in) :: self
Reshape class
Return Value integer(kind=int64)
Calls
Called by
Call graph
get_aux_bytes calls get_aux_bytes_generic, get_aux_bytes
get_aux_bytes_generic calls get_aux_bytes
get_aux_bytes_reshape calls get_aux_bytes
get_aux_bytes_transpose calls get_aux_bytes
is_aux_needed calls get_aux_bytes
check_aux calls get_aux_bytes, is_aux_needed
dtfft_get_aux_bytes_c calls get_aux_bytes
dtfft_get_aux_bytes_reshape_c calls get_aux_bytes_reshape
dtfft_get_aux_bytes_transpose_c calls get_aux_bytes_transpose
get_aux_size calls get_aux_bytes
get_aux_size_reshape calls get_aux_bytes_reshape
get_aux_size_transpose calls get_aux_bytes_transpose
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_aux_size_reshape_c calls get_aux_size_reshape
dtfft_get_aux_size_transpose_c calls get_aux_size_transpose
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr