get_pencil – dtFFT
get_pencil Function
35 statements
Source File
private function get_pencil(self, dim, error_code)
Returns pencil decomposition
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(in) :: dim
Required dimension:
0 for XYZ layout (real space, R2C only)
1 for XYZ layout
2 for YXZ layout
3 for ZXY layout
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value type(dtfft_pencil_t)
Calls
Called by
Call graph
get_pencil calls make_public, dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_get_pencil_c calls get_pencil