get_reshape_backend – dtFFT
get_reshape_backend Function
21 statements
Source File
private function get_reshape_backend(self, error_code)
Returns selected reshape backend during autotuning
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value type(dtfft_backend_t)
Calls
Called by
Call graph
get_reshape_backend calls dtfft_get_error_string, get_backend, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_get_reshape_backend_c calls get_reshape_backend