get_kernel_args – dtFFT
get_kernel_args Subroutine
48 statements
Source File
public subroutine get_kernel_args(comm, dims, transpose_type, kernel_type, block_rows, ptrs, params)
Populates kernel arguments based on kernel type
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: comm
integer(kind=int32), intent(in) :: dims(:)
Local dimensions to process
type(dtfft_transpose_t), intent(in) :: transpose_type
Type of transposition to perform
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int32), intent(in) :: block_rows
Number of rows in each block
type(c_ptr), intent(in) :: ptrs(3)
type(kernelArgs), intent(out) :: params
Kernel arguments
Calls
Called by
Call graph
get_kernel_args calls mpi_comm_rank, mpi_comm_size
create calls get_kernel_args, get_kernel, create
get_kernel calls get_kernel_args