get_gpu_backend_from_env – dtFFT
get_gpu_backend_from_env Function
3 statements
Source File
public pure function get_gpu_backend_from_env()
Returns GPU backend to use set by environment variable
Arguments
None
Return Value type(dtfft_gpu_backend_t)
Called by
Call graph
get_user_gpu_backend calls get_gpu_backend_from_env
create_cuda calls get_user_gpu_backend
create_private calls get_user_gpu_backend
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal