get_conf_pipelined_enabled – dtFFT
get_conf_pipelined_enabled Function
4 statements
Source File
public elemental function get_conf_pipelined_enabled() result(bool)
Whether pipelined backends are enabled or not
Arguments
None
Return Value logical
Result flag
Calls
Called by
Call graph
get_conf_pipelined_enabled calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
autotune_reshape_plan calls get_conf_pipelined_enabled
run_autotune_backend calls get_conf_pipelined_enabled
autotune_grid calls run_autotune_backend
create calls run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
autotune_grid_decomposition calls autotune_grid