get_correct_backend – dtFFT
get_correct_backend Function
12 statements
Source File
public elemental function get_correct_backend(back)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: back
Return Value type(dtfft_backend_t)
Calls
Called by
Call graph
get_correct_backend calls get_conf_platform
autotune_grid_decomposition calls get_correct_backend, autotune_grid
dtfft_set_config calls get_correct_backend
get_conf_backend calls get_correct_backend
get_conf_reshape_backend calls get_correct_backend
run_autotune_backend calls get_correct_backend
autotune_grid calls run_autotune_backend
check_create_args calls get_conf_backend
create calls get_conf_reshape_backend, autotune_grid_decomposition, get_conf_backend, run_autotune_backend
dtfft_set_config_c calls dtfft_set_config
create_private calls check_create_args
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal