get_dims – dtFFT
get_dims Subroutine
15 statements
Source File
private subroutine get_dims(self, dims, error_code)
Returns global dimensions
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in), target :: self
Abstract plan
integer(kind=int32), intent(out), pointer :: dims(:)
Global dimensions
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
get_dims calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_get_dims_c calls get_dims