get_conf_stream – dtFFT
get_conf_stream Function
20 statements
Source File
public function get_conf_stream() result(stream)
Uses
iso_c_binding
iso_fortran_env
Returns either the custom provided by user or creates a new one
Arguments
None
Return Value type(dtfft_stream_t)
Calls
Called by
Call graph
get_conf_stream calls cudastreamcreate, to_str, mpi_abort, cudageterrorstring
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
create_cuda calls get_conf_stream
create_private calls get_conf_stream
create calls get_conf_stream, get_kernel, create
get_kernel calls get_conf_stream
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal