get_log_enabled – dtFFT
get_log_enabled Function
4 statements
Source File
public pure function get_log_enabled() result(log)
Returns the value of the log_enabled variable
Arguments
None
Return Value logical
Value of the log_enabled variable
Called by
Call graph
alloc_mem calls get_log_enabled
autotune_grid calls get_log_enabled, run_autotune_backend, get_plan_execution_time, autotune_mpi_datatypes
autotune_grid_decomposition calls get_log_enabled, autotune_grid
create_c2c calls get_log_enabled, create_c2c_core
create_c2c_pencil calls get_log_enabled, create_c2c_internal
create_cuda calls get_log_enabled, run_autotune_backend, alloc_and_set_aux, autotune_grid_decomposition, create_helper, load_cuda, load_nvrtc
create_pencil_init calls get_log_enabled
create_private calls get_log_enabled, autotune_grid_decomposition, autotune_grid, get_datatype_from_env, check_create_args
create_r2c calls get_log_enabled, create_r2c_internal
create_r2c_pencil calls get_log_enabled, create_r2c_internal
create_r2r calls get_log_enabled, create_r2r_internal
create_r2r_pencil calls get_log_enabled, create_r2r_internal
create calls get_log_enabled, load_vkfft
destroy_helper calls get_log_enabled
destroy calls get_log_enabled, mem_free_ptr
dl_error calls get_log_enabled
execute_ptr calls get_log_enabled, check_aux
get_alloc_bytes calls get_log_enabled, get_element_size, get_alloc_size
get_dims calls get_log_enabled
get_element_size calls get_log_enabled
get_env_int32 calls get_log_enabled, get_env
get_env_string calls get_log_enabled, get_env
get_executor calls get_log_enabled
get_local_sizes calls get_log_enabled
get_pencil calls get_log_enabled
get_plan_execution_time calls get_log_enabled, get_iters_from_env
get_precision calls get_log_enabled
get_stream_ptr calls get_log_enabled
mem_alloc_ptr calls get_log_enabled
mem_free_ptr calls get_log_enabled
report calls get_log_enabled
run_autotune_backend calls get_log_enabled, alloc_mem, alloc_and_set_aux, create_helper, get_iters_from_env
transpose_ptr calls get_log_enabled
get_env calls get_env_int32, get_env_string, get_env_int8, get_env_logical
alloc_and_set_aux calls alloc_mem
autotune_transpose_id calls get_plan_execution_time
check_aux calls get_element_size, mem_alloc_ptr, get_alloc_size
create_helper calls destroy_helper, get_env
dtfft_destroy_c calls destroy
dtfft_execute_c calls execute_ptr
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_dims_c calls get_dims
dtfft_get_element_size_c calls get_element_size
dtfft_get_executor_c calls get_executor
dtfft_get_local_sizes_c calls get_local_sizes
dtfft_get_pencil_c calls get_pencil
dtfft_get_precision_c calls get_precision
dtfft_mem_alloc_c calls mem_alloc_ptr
dtfft_mem_free_c calls mem_free_ptr
dtfft_report_c calls report
dtfft_transpose_c calls transpose_ptr
execute calls execute_ptr
get_alloc_size calls get_local_sizes
load_library calls dl_error
load_symbol calls dl_error
mem_alloc_c32_1d calls mem_alloc_ptr
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_c32_3d calls mem_alloc_ptr
mem_alloc_c64_1d calls mem_alloc_ptr
mem_alloc_c64_2d calls mem_alloc_ptr
mem_alloc_c64_3d calls mem_alloc_ptr
mem_alloc_r32_1d calls mem_alloc_ptr
mem_alloc_r32_2d calls mem_alloc_ptr
mem_alloc_r32_3d calls mem_alloc_ptr
mem_alloc_r64_1d calls mem_alloc_ptr
mem_alloc_r64_2d calls mem_alloc_ptr
mem_alloc_r64_3d calls mem_alloc_ptr
mem_alloc calls alloc_mem
mem_free_c32_1d calls mem_free_ptr
mem_free_c32_2d calls mem_free_ptr
mem_free_c32_3d calls mem_free_ptr
mem_free_c64_1d calls mem_free_ptr
mem_free_c64_2d calls mem_free_ptr
mem_free_c64_3d calls mem_free_ptr
mem_free_r32_1d calls mem_free_ptr
mem_free_r32_2d calls mem_free_ptr
mem_free_r32_3d calls mem_free_ptr
mem_free_r64_1d calls mem_free_ptr
mem_free_r64_2d calls mem_free_ptr
mem_free_r64_3d calls mem_free_ptr
transpose calls transpose_ptr
unload_library calls dl_error
autotune_mpi_datatypes calls autotune_transpose_id
dtfft_get_alloc_size_c calls get_alloc_size
dtfft_get_stream_c calls get_stream
dynamic_load calls load_library, load_symbol, unload_library
get_datatype_from_env calls get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_iters_from_env calls get_env
get_stream_int64 calls get_stream
init_internal calls get_env
check_create_args calls init_internal
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
load_vkfft calls load
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core