get_backend_from_env – dtFFT
get_backend_from_env Function
69 statements
Source File
private function get_backend_from_env(name)
Returns backend or reshape backend obtained from environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of the environment variable
Return Value type(dtfft_backend_t)
Calls
Called by
Call graph
get_backend_from_env calls get_env, destroy_string, destroy_strings, is_valid_backend, write_message
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_strings calls destroy_string
write_message calls mpi_comm_rank, mpi_finalized
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls get_env, write_message, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, destroy_string, write_message
init_environment calls get_backend_from_env
init_internal calls init_environment
check_create_args calls init_internal
dtfft_set_config calls init_internal
test_device_kernels calls init_internal
create_private calls check_create_args
dtfft_set_config_c calls dtfft_set_config
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal