get_comm – dtFFT
get_comm Function
4 statements
Source File
private pure function get_comm(c_comm)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int32_t), intent(in) :: c_comm
Return Value type(mpi_comm)
Called by
Call graph
dtfft_create_plan_c2c_c calls get_comm
dtfft_create_plan_c2c_pencil_c calls get_comm
dtfft_create_plan_r2r_c calls get_comm
dtfft_create_plan_r2r_pencil_c calls get_comm