get_alloc_size – dtFFT
get_alloc_size Function
6 statements
Source File
private function get_alloc_size(self, error_code) result(alloc_size)
Wrapper around get_local_sizes to obtain number of elements only
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value integer(kind=int64)
Minimal number of elements required to execute plan
Calls
Called by
Call graph
get_alloc_size calls get_local_sizes
get_local_sizes calls mpi_allreduce, dtfft_get_error_string, get_aux_bytes, get_backend, get_local_sizes_internal, get_local_sizes, is_backend_nvshmem, write_message
get_aux_bytes calls get_aux_bytes_generic, get_aux_size
get_local_sizes_internal calls get_local_sizes, counts, starts
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes_generic calls get_aux_bytes
dtfft_get_alloc_size_c calls get_alloc_size
get_alloc_bytes calls get_alloc_size
get_aux_size calls get_alloc_size
check_aux calls get_alloc_bytes, get_aux_bytes
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_aux_bytes_c calls get_aux_bytes
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr