get_kernel – dtFFT
get_kernel Subroutine
327 statements
Source File
private subroutine get_kernel(dims, kernel_type, kernel_string, effort, base_storage, props, tile_size, block_rows, kernel, force_effort, neighbor_data)
Uses
iso_fortran_env
iso_c_binding
Compiles kernel and caches it. Returns compiled kernel.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Local dimensions to process
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
type(string), intent(in) :: kernel_string
Kernel string
type(dtfft_effort_t), intent(in) :: effort
How thoroughly dtFFT searches for the optimal transpose kernel
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(device_props), intent(in) :: props
GPU architecture properties
integer(kind=int32), intent(out) :: tile_size
Size of the tile in shared memory
integer(kind=int32), intent(out) :: block_rows
Number of rows in each block processed by each thread
type(CUfunction), intent(out) :: kernel
Compiled kernel to return
logical, intent(in), optional :: force_effort
Should effort be forced or not
integer(kind=int32), intent(in), optional :: neighbor_data(:)
Neighbor data for pipelined kernels
Calls
Called by
Call graph
get_kernel calls fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudafree, cudamalloc, cudastreamsynchronize, to_str, mpi_abort, create_nvrtc_module, cudageterrorstring, culaunchkernel, evaluate_analytical_performance, generate_candidates, get_conf_kernel_autotune_enabled, get_conf_log_enabled, get_conf_measure_iters, get_conf_measure_warmup_iters, get_conf_stream, get_kernel_args, get_kernel_instance, get_kernel_launch_params, is_pack_kernel, is_unpack_kernel, pop_nvtx_domain_range, push_nvtx_domain_range, sort_candidates_by_score, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create_nvrtc_module calls to_str, get_conf_log_enabled, write_message, check, add, create, destroy_string, get_kernel_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
evaluate_analytical_performance calls count_bank_conflicts, estimate_bank_conflict_ratio, estimate_coalescing, estimate_occupancy
generate_candidates calls estimate_memory_pressure, estimate_optimal_padding, find_valid_combination
get_conf_kernel_autotune_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_stream calls fname, mpi_abort, cudageterrorstring, cudastreamcreate
get_kernel_args calls is_pack_kernel, is_unpack_kernel
get_kernel_instance calls to_str, mpi_abort, get_conf_log_enabled, write_message, get, get_kernel_string
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
add calls to_str, get_conf_log_enabled, write_message, create
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create calls fname, mpi_abort, cudageterrorstring, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message, get_kernel_string, mem_free_host, compile_program, destroy, get_code, mem_alloc_host, nvrtcgeterrorstring, get_kernel
estimate_bank_conflict_ratio calls count_bank_conflicts
estimate_coalescing calls mpi_abort, write_message
estimate_optimal_padding calls count_bank_conflicts
get calls fname, mpi_abort, cudageterrorstring, write_message, check, get_mangled_name
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
check_instance calls check
compile_program calls fname, to_str, mpi_abort, write_message, astring_f2c, string_c2f, mem_alloc_host, nvrtcgeterrorstring, destroy_strings, set_name_expression
destroy calls fname, mpi_abort, cudageterrorstring, write_message, destroy_string, nvrtcgeterrorstring, is_null_ptr
get_code calls mpi_abort, is_pack_kernel, is_unpack_kernel, write_message, add_line, is_transpose_kernel
get_mangled_name calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression
mem_alloc_host calls aligned_alloc
nvrtcgeterrorstring calls string_c2f
destroy_strings calls destroy_string
get_name_expression calls to_str, astring_f2c
set_name_expression calls fname, mpi_abort, nvrtcgeterrorstring, get_name_expression