get_contiguous_execution_blocks – dtFFT
get_contiguous_execution_blocks Subroutine
17 statements
Source File
private subroutine get_contiguous_execution_blocks(size, blocks, threads)
Gets the number of blocks and threads for a contiguous execution
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: size
Total amount of iterations required
type(dim3), intent(out) :: blocks
Grid of blocks.
type(dim3), intent(out) :: threads
Thread block.
Called by
Call graph
execute calls get_contiguous_execution_blocks, execute
get_kernel calls get_contiguous_execution_blocks
create calls get_kernel, create
execute_mpi calls execute
execute_nccl calls execute
execute_cuda calls execute
run_autotune_backend calls execute
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid