get_conf_kernel_optimization_enabled – dtFFT
get_conf_kernel_optimization_enabled Function
4 statements
Source File
public elemental function get_conf_kernel_optimization_enabled() result(bool)
Whether kernel optimization is enabled or not
Arguments
None
Return Value logical
Result flag
Calls
Called by
Call graph
get_conf_kernel_optimization_enabled calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
create_host calls get_conf_kernel_optimization_enabled
get_kernel calls get_conf_kernel_optimization_enabled
create calls get_kernel