get_conf_measure_warmup_iters – dtFFT
get_conf_measure_warmup_iters Function
4 statements
Source File
public elemental function get_conf_measure_warmup_iters() result(iters)
Returns the number of warmup iterations
Arguments
None
Return Value integer(kind=int32)
Result
Calls
Called by
Call graph
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
create_host calls get_conf_measure_warmup_iters
execute_autotune calls get_conf_measure_warmup_iters
get_kernel calls get_conf_measure_warmup_iters
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid