get_conf_measure_iters – dtFFT
get_conf_measure_iters Function
4 statements
Source File
public elemental function get_conf_measure_iters() result(iters)
Returns the number of measurement iterations
Arguments
None
Return Value integer(kind=int32)
Result
Calls
Called by
Call graph
get_conf_measure_iters calls get_conf_internal
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_kernel calls get_conf_measure_iters
get_plan_execution_time calls get_conf_measure_iters
run_autotune_backend calls get_conf_measure_iters
autotune_grid calls run_autotune_backend, get_plan_execution_time, autotune_mpi_datatypes
autotune_transpose_id calls get_plan_execution_time
create_cuda calls run_autotune_backend, autotune_grid_decomposition
create calls get_kernel, create
autotune_grid_decomposition calls autotune_grid
autotune_mpi_datatypes calls autotune_transpose_id
create_private calls autotune_grid, autotune_grid_decomposition