get_code – dtFFT
get_code Function
150 statements
Source File
private function get_code(kernel_name, ndims, base_storage, kernel_type) result(code)
Uses
iso_fortran_env
Generates code that will be used to locally tranpose data and prepares to send it to other processes
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: kernel_name
Name of CUDA kernel
integer(kind=int32), intent(in) :: ndims
Number of dimensions
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to generate code for
Return Value type(codegen_t)
Resulting code
Calls
Called by
Call graph
get_code calls mpi_abort, add_line, is_pack_kernel, is_transpose_kernel, is_unpack_kernel, write_message
write_message calls mpi_comm_rank, mpi_finalized
create calls get_code, get_kernel
create_nvrtc_module calls create
get_kernel calls create_nvrtc_module