get_user_stream – dtFFT
get_user_stream Function
21 statements
Source File
public function get_user_stream() result(stream)
Uses
dtfft_interface_cuda
iso_fortran_env
iso_c_binding
Returns either the custom provided by user or creates a new one
Arguments
None
Return Value type(dtfft_stream_t)
Calls
Called by
Call graph
get_user_stream calls cudastreamcreate, int_to_str, mpi_abort, cudageterrorstring
int_to_str calls int_to_str_int32, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c
create calls get_user_stream
create_cuda calls get_user_stream
create_private calls get_user_stream
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal
r2r_constructor calls create_r2r
dtfft_plan_r2r_t calls r2r_constructor
c2c_constructor calls create_generic_c2c
dtfft_plan_c2c_t calls c2c_constructor