get_mangled_name – dtFFT
get_mangled_name Function
25 statements
Source File
private function get_mangled_name(basic_name, prog, tile_dim, block_rows, padding) result(mangled)
Uses
iso_fortran_env
iso_c_binding
Gets mangled name for given template parameters from nvRTC program
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: basic_name
Basic kernel name
type(nvrtcProgram), intent(in) :: prog
nvRTC program
integer(kind=int32), intent(in) :: tile_dim
Size of shared memory tile, template parameter
integer(kind=int32), intent(in) :: block_rows
Number of rows processed by single thread, template parameter
integer(kind=int32), intent(in) :: padding
Padding to avoid shared memory bank conflicts, template parameter
Return Value type(c_ptr)
Mangled kernel name
Calls
Called by
Call graph
get_mangled_name calls fname, mpi_abort, get_name_expression, nvrtcgeterrorstring
get_name_expression calls to_str, astring_f2c
nvrtcgeterrorstring calls string_c2f
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
get calls get_mangled_name
get_kernel_instance calls get
get_kernel calls get_kernel_instance
create calls get_kernel