get_transpose_kernel – dtFFT
get_transpose_kernel Subroutine
19 statements
Source File
private subroutine get_transpose_kernel(comm, kernel_name, dims, transpose_type, kernel_type, base_storage, props, config, blocks, threads, kernel)
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: comm
MPI Communicator
character(len=*), intent(in) :: kernel_name
integer(kind=int32), intent(in) :: dims(:)
Local dimensions to process
type(dtfft_transpose_t), intent(in) :: transpose_type
Type of transposition to perform
type(kernel_type_t), intent(in) :: kernel_type
Type of kernel to build
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(device_props), intent(in) :: props
type(kernel_config), intent(in) :: config
type(dim3), intent(out) :: blocks
type(dim3), intent(out) :: threads
type(CUfunction), intent(out) :: kernel
Compiled kernel to return
Calls
Called by
Call graph
get_transpose_kernel calls compile_and_cache, destroy_code, get_transpose_kernel_code
compile_and_cache calls to_str, is_null_ptr, mpi_abort, add, astring_f2c, cudageterrorstring, destroy_strings, get, get_conf_log_enabled, nvrtcgeterrorstring, pop_nvtx_domain_range, push_nvtx_domain_range, string_c2f, to_cstr, write_message
get_transpose_kernel_code calls to_str, add_line, get_code_init, get_neighbor_function_code
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
add calls create, get_true_transpose_type
astring_f2c calls string_f2c
cudageterrorstring calls string_c2f, cudageterrorstring_c
destroy_strings calls destroy_string
get calls get_true_transpose_type, is_unpack_kernel
get_code_init calls add_line
get_conf_log_enabled calls get_conf_internal
get_neighbor_function_code calls add_line
nvrtcgeterrorstring calls string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls astring_f2c, nvtxdomainrangepushex_c, create_nvtx_domain
to_cstr calls astring_f2c
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_kernel calls get_transpose_kernel
create calls get_kernel, create