get_platform_from_env – dtFFT
get_platform_from_env Function
3 statements
Source File
public pure function get_platform_from_env()
Returns execution platform set by environment variable
Arguments
None
Return Value type(dtfft_platform_t)
Called by
Call graph
get_user_platform calls get_platform_from_env
check_create_args calls get_user_platform
create calls get_user_platform
create_private calls check_create_args, create
create_c2c_internal calls create_private
create_r2r calls create_private
create_c2c calls create_c2c_internal
create_r2c calls create_c2c_internal