get_conf_transpose – dtFFT
get_conf_transpose Function
4 statements
Source File
public elemental function get_conf_transpose() result(config)
Returns compression config for transposes
Arguments
None
Return Value type(dtfft_compression_config_t)
Result
Called by
Call graph
create calls get_conf_transpose, run_autotune_backend, autotune_grid_decomposition
run_autotune_backend calls get_conf_transpose
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid