get_aux_bytes – dtFFT
get_aux_bytes Function
4 statements
Source File
private pure function get_aux_bytes(self)
Returns number of bytes required by aux buffer
Type Bound
abstract_reshape_handle
Arguments
Type Intent Optional Attributes Name
class(abstract_reshape_handle), intent(in) :: self
Abstract reshape Handle
Return Value integer(kind=int64)
Called by
Call graph
get_aux_bytes_generic calls get_aux_bytes
alloc_and_set_aux calls get_aux_bytes_generic
get_aux_bytes calls get_aux_bytes_generic, get_aux_bytes
execute_autotune calls alloc_and_set_aux
get_aux_bytes_reshape calls get_aux_bytes
get_aux_bytes_transpose calls get_aux_bytes
is_aux_needed calls get_aux_bytes
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
check_aux calls get_aux_bytes, is_aux_needed
dtfft_get_aux_bytes_c calls get_aux_bytes
dtfft_get_aux_bytes_reshape_c calls get_aux_bytes_reshape
dtfft_get_aux_bytes_transpose_c calls get_aux_bytes_transpose
execute_many calls execute_autotune, execute_single
get_aux_size calls get_aux_bytes
get_aux_size_reshape calls get_aux_bytes_reshape
get_aux_size_transpose calls get_aux_bytes_transpose
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_aux_size_reshape_c calls get_aux_size_reshape
dtfft_get_aux_size_transpose_c calls get_aux_size_transpose
execute_ptr calls check_aux
execute_single_transpose_modes calls run_execute_single
reshape_private calls check_aux
run_autotune_backend calls execute_many, execute_single
transpose_private calls check_aux
autotune_grid calls run_autotune_backend
dtfft_execute_c calls execute_ptr
execute_single calls execute_single_transpose_modes
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
autotune_grid_decomposition calls autotune_grid
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr