get_user_gpu_backend – dtFFT
get_user_gpu_backend Function
4 statements
Source File
public function get_user_gpu_backend()
Returns GPU backend set by the user or default one
Arguments
None
Return Value type(dtfft_gpu_backend_t)
Calls
Called by
Call graph
get_user_gpu_backend calls get_gpu_backend_from_env
create_cuda calls get_user_gpu_backend
create_private calls get_user_gpu_backend
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal
r2r_constructor calls create_r2r
dtfft_plan_r2r_t calls r2r_constructor
c2c_constructor calls create_generic_c2c
dtfft_plan_c2c_t calls c2c_constructor