get_unpack_kernel_code – dtFFT
get_unpack_kernel_code Function
34 statements
Source File
private function get_unpack_kernel_code(kernel_name, base_storage, is_partial) result(code)
Generates code that will be used to unpack data when it is recieved
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: kernel_name
Name of CUDA kernel
integer(kind=int8), intent(in) :: base_storage
Number of bytes needed to store single element
logical, intent(in) :: is_partial
Return Value type(kernel_code)
Resulting code
Calls
Called by
Call graph
get_unpack_kernel_code calls add_line, get_code_init, get_neighbor_function_code
get_code_init calls add_line, int_to_str
get_neighbor_function_code calls add_line
int_to_str calls int_to_str_int32, int_to_str_int8
compile_and_cache calls get_unpack_kernel_code
create calls compile_and_cache, create