get_conf_backend – dtFFT
get_conf_backend Function
4 statements
Source File
public elemental function get_conf_backend()
Returns backend set by the user or default one
Arguments
None
Return Value type(dtfft_backend_t)
Calls
Called by
Call graph
get_conf_backend calls get_correct_backend
get_correct_backend calls get_conf_platform
check_create_args calls get_conf_backend
create calls get_conf_backend
create_private calls check_create_args
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal