get_reshape_type – dtFFT
get_reshape_type Function
19 statements
Source File
public pure function get_reshape_type(send, recv) result(reshape_type)
Determines reshape ID based on pencils
Arguments
Type Intent Optional Attributes Name
type(pencil), intent(in) :: send
Send pencil
type(pencil), intent(in) :: recv
Receive pencil
Return Value type(dtfft_reshape_t)
Reshape ID
Called by
Call graph
create calls get_reshape_type, create_reshape_plans, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
create_reshape_plans calls create
get_plan_execution_time calls create
autotune_reshape_plan calls create_reshape_plans
autotune_transpose_id calls get_plan_execution_time
run_autotune_datatypes calls autotune_transpose_id
run_autotune_backend calls run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid