get_code_init – dtFFT
get_code_init Subroutine
26 statements
Source File
private subroutine get_code_init(kernel_name, base_storage, code, buffer_type)
Generates basic code that is used in all other kernels
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: kernel_name
Name of CUDA kernel
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(kernel_code), intent(inout) :: code
Resulting code
character(len=:), intent(out), optional, allocatable :: buffer_type
Type of buffer that should be used
Calls
Called by
Call graph
get_code_init calls int_to_str, add_line
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
get_transpose_kernel_code calls get_code_init
get_unpack_kernel_code calls get_code_init
get_unpack_pipelined_kernel_code calls get_code_init
compile_and_cache calls get_transpose_kernel_code, get_unpack_kernel_code, get_unpack_pipelined_kernel_code
create calls compile_and_cache, create