get_kernel_string – dtFFT
get_kernel_string Function
32 statements
Source File
public function get_kernel_string(kernel) result(str)
Gets the string description of a kernel
Arguments
Type Intent Optional Attributes Name
type(kernel_type_t), intent(in) :: kernel
kernel type
Return Value type(string)
kernel string
Called by
Call graph
create_nvrtc_module calls get_kernel_string, create
create calls get_kernel_string, create, get_kernel
execute_test calls get_kernel_string, create
get_kernel_instance calls get_kernel_string
test_transpose calls get_kernel_string
get_kernel calls create_nvrtc_module, get_kernel_instance
test_compression calls test_transpose
test_device_kernels calls execute_test