get_local_size – dtFFT
get_local_size Subroutine
38 statements
Source File
private subroutine get_local_size(n_global, comm, start, count, start_to_keep, size_to_keep)
Computes local portions of data based on global count and position inside grid communicator
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: n_global
Global number of points
type(MPI_Comm), intent(in) :: comm
Grid communicator
integer(kind=int32), intent(out) :: start
Local start
integer(kind=int32), intent(out) :: count
Local count
integer(kind=int32), intent(in), optional :: start_to_keep
Start to keep in case of user defined decomposition
integer(kind=int32), intent(in), optional :: size_to_keep
Size to keep in case of user defined decomposition
Calls
Called by
Call graph
get_local_size calls mpi_allgather, mpi_comm_rank, mpi_comm_size
create calls get_local_size, create_pencils_and_comm, autotune_grid_decomposition
create_pencils_and_comm calls create
create_r2c_internal calls create
autotune_grid calls create_pencils_and_comm
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
autotune_grid_decomposition calls autotune_grid