get_aux_size – dtFFT
get_aux_size Function
22 statements
Source File
private function get_aux_size(self, error_code)
Returns minimum number of elements required for auxiliary buffer which may be different from alloc_size when backend is pipelined
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value integer(kind=int64)
Calls
Called by
Call graph
get_aux_size calls dtfft_get_error_string, get_alloc_size, get_aux_bytes, get_aux_size_reshape, is_aux_needed, write_message
get_alloc_size calls get_local_sizes
get_aux_bytes calls get_aux_bytes_generic, get_aux_size
get_aux_size_reshape calls dtfft_get_error_string, write_message, get_aux_bytes_reshape, get_element_size
is_aux_needed calls get_aux_bytes
write_message calls mpi_comm_rank, mpi_finalized
get_aux_bytes_generic calls get_aux_bytes
get_aux_bytes_reshape calls dtfft_get_error_string, get_aux_bytes, write_message
get_element_size calls dtfft_get_error_string, write_message
get_local_sizes calls dtfft_get_error_string, get_aux_bytes, write_message, mpi_allreduce, get_backend, get_local_sizes, get_local_sizes_internal, is_backend_nvshmem
get_local_sizes_internal calls get_local_sizes, counts, starts
dtfft_get_aux_size_c calls get_aux_size
check_aux calls get_aux_bytes
dtfft_get_aux_bytes_c calls get_aux_bytes
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr