get_backend – dtFFT
get_backend Function
4 statements
Source File
private function get_backend(self)
Returns plan backend
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(in) :: self
Transposition class
Return Value type(dtfft_backend_t)
Called by
Call graph
check_aux calls get_backend, get_aux_bytes, get_alloc_bytes
create_private calls get_backend
get_aux_size calls get_backend, get_alloc_size
get_backend calls get_backend
get_local_sizes calls get_backend
get_reshape_backend calls get_backend
report calls get_backend
create_c2c_core calls create_private
create_r2r_internal calls create_private
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_backend_c calls get_backend
dtfft_get_local_sizes_c calls get_local_sizes
dtfft_get_reshape_backend_c calls get_reshape_backend
dtfft_report_c calls report
execute_ptr calls check_aux
get_alloc_size calls get_local_sizes
get_aux_bytes calls get_aux_size
reshape_private calls check_aux
transpose_private calls check_aux
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
dtfft_execute_c calls execute_ptr
dtfft_get_alloc_size_c calls get_alloc_size
dtfft_get_aux_bytes_c calls get_aux_bytes
execute calls execute_ptr
get_alloc_bytes calls get_alloc_size
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr