get_datatype_from_env – dtFFT
get_datatype_from_env Function
4 statements
Source File
public function get_datatype_from_env(name) result(env)
Obtains datatype id from environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
Return Value integer(kind=int8)
Calls
Called by
Call graph
get_datatype_from_env calls get_env
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls get_env, write_message
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, destroy_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
create calls get_datatype_from_env