get_true_transpose_type – dtFFT
get_true_transpose_type Function
9 statements
Source File
private function get_true_transpose_type(transpose_type) result(transpose_type_)
Returns generic transpose id. Since X-Y and Y-Z transpositions are symmectric, it returns only one of them. X-Z and Z-X are not symmetric
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_t), intent(in) :: transpose_type
Type of transposition to perform
Return Value type(dtfft_transpose_t)
Fixed id of transposition
Called by
Call graph
add calls get_true_transpose_type
get calls get_true_transpose_type
compile_and_cache calls add, get
get_kernel calls compile_and_cache, get_transpose_kernel
get_transpose_kernel calls compile_and_cache
create calls get_kernel, create