get_grid_dims – dtFFT
get_grid_dims Subroutine
15 statements
Source File
private subroutine get_grid_dims(self, grid_dims, error_code)
Returns grid decomposition dimensions
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in), target :: self
Abstract plan
integer(kind=int32), intent(out), pointer :: grid_dims(:)
Grid dimensions
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
get_grid_dims calls dtfft_get_error_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
dtfft_get_grid_dims_c calls get_grid_dims