get_name_expression – dtFFT
get_name_expression Function
15 statements
Source File
private function get_name_expression(basic_name, tile_dim, block_rows, padding) result(expression)
Generates name expression for given template parameters
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: basic_name
Basic kernel name
integer(kind=int32), intent(in) :: tile_dim
Size of shared memory tile, template parameter
integer(kind=int32), intent(in) :: block_rows
Number of rows processed by single thread, template parameter
integer(kind=int32), intent(in) :: padding
Padding to avoid shared memory bank conflicts, template parameter
Return Value character(len=c_char), allocatable, (:)
Resulting name expression
Calls
Called by
Call graph
get_name_expression calls to_str, astring_f2c
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
get_mangled_name calls get_name_expression
set_name_expression calls get_name_expression
compile_program calls set_name_expression
get calls get_mangled_name
create calls compile_program, get_kernel
get_kernel_instance calls get
create_nvrtc_module calls create
get_kernel calls get_kernel_instance, create_nvrtc_module