init_internal – dtFFT
init_internal Function
13 statements
Source File
public function init_internal()
Checks if MPI is initialized and loads environment variables
Arguments
None
Return Value integer(kind=int32)
Calls
Called by
Call graph
init_internal calls mpi_initialized, init_environment
init_environment calls access_modes, destroy, get_env, platforms, destroy_strings, get_backend_from_env, transpose_modes
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
destroy_strings calls destroy_string
get_backend_from_env calls get_env, destroy_strings, destroy_string, is_valid_backend, write_message
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls get_env, write_message, mpi_abort
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, destroy_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
check_create_args calls init_internal
dtfft_set_config calls init_internal
test_compression calls init_internal
test_device_kernels calls init_internal
create_private calls check_create_args
dtfft_set_config_c calls dtfft_set_config
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal