init – dtFFT
init Function
62 statements
Source File
private function init(self, platform, effort, backend, autotune_effort, compression_config, base_dtype, base_storage) result(error_code)
Uses
iso_fortran_env
Initializes reshape plan base
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(inout) :: self
Reshape class
type(dtfft_platform_t), intent(in) :: platform
Execution platform
type(dtfft_effort_t), intent(in) :: effort
Effort level
type(dtfft_backend_t), intent(in) :: backend
type(dtfft_effort_t), intent(in) :: autotune_effort
type(dtfft_compression_config_t), intent(in) :: compression_config
Compression configuration
type(MPI_Datatype), intent(in) :: base_dtype
Base datatype
integer(kind=int64), intent(in) :: base_storage
Number of bytes to store single element of base datatype
Return Value integer(kind=int32)
Error code
Calls
Called by
Call graph
init calls create, destroy, mpi_abort, check_compression_config, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_stream, is_backend_compressed, is_backend_nccl, is_backend_nvshmem, load_cuda, load_nvrtc, write_message
check_compression_config calls is_valid_compression_lib, is_valid_compression_mode
get_conf_compression_enabled calls get_conf_internal
get_conf_datatype_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_stream calls mpi_abort, fname, cudastreamcreate, cudageterrorstring
load_cuda calls destroy_strings, dynamic_load
load_nvrtc calls destroy_strings, dynamic_load
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
cudageterrorstring calls cudageterrorstring_c, string_c2f
destroy_strings calls destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
is_null_ptr calls is_null_ptr, is_null_funptr
load_library calls is_null_ptr, dlopen, astring_f2c, dl_error
load_symbol calls mpi_abort, write_message, is_null_ptr, dlsym, astring_f2c, dl_error
string_c2f calls is_null_ptr
unload_library calls dlclose, dl_error
astring_f2c calls string_f2c
dl_error calls write_message, string_c2f, dlerror
create calls init