init – dtFFT
init Subroutine
32 statements
Source File
private subroutine init(self, uncompressed_ptr, dims, zfp, field)
Initializes ZFP stream and field for compression/decompression
Type Bound
compressor_zfp
Arguments
Type Intent Optional Attributes Name
class(compressor_zfp), intent(inout) :: self
Compressor instance
type(c_ptr), intent(in) :: uncompressed_ptr
Pointer to uncompressed data
integer(kind=int32), intent(in) :: dims(:)
Array dimensions
type(zfp_stream), intent(out) :: zfp
ZFP stream
type(zfp_field), intent(out) :: field
ZFP field
Calls
Called by
Call graph
init calls zfp_stream_open, zfp_stream_set_execution, zfp_stream_set_reversible, zfp_create_field, zfp_field_set_stride, zfp_stream_set_accuracy, zfp_stream_set_precision, zfp_stream_set_rate
zfp_create_field calls zfp_field_2d, zfp_field_3d
zfp_field_set_stride calls zfp_field_dimensionality, zfp_field_set_stride_2d, zfp_field_set_stride_3d
zfp_stream_set_accuracy calls zfp_stream_set_accuracy_interface
zfp_stream_set_precision calls zfp_stream_set_precision_interface
zfp_stream_set_rate calls zfp_field_dimensionality, zfp_field_type, zfp_stream_set_rate_interface
compress calls init
decompress calls init