int8_to_string – dtFFT
int8_to_string Function
7 statements
Source File
private function int8_to_string(n) result(str)
Convert 8-bit integer to string
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: n
Integer to convert
Return Value character(len=:), allocatable
Resulting string
Called by
Call graph
to_str calls int8_to_string
add calls to_str
alloc_mem calls to_str
autotune_grid calls to_str, create_pencils_and_comm, run_autotune_backend
check_aux calls to_str
compile_program calls to_str, set_name_expression
create_cart_comm calls to_str
create_host calls to_str, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64
create_nvrtc_module calls to_str, add, create
create calls to_str, alloc_and_set_aux, autotune_grid_decomposition, create_pencils_and_comm, run_autotune_backend, compile_program, get_kernel, make_plan
destroy calls to_str, mem_free
execute calls to_str, execute_ptr
free_mem calls to_str
get_kernel calls to_str, create_nvrtc_module, get_kernel_instance
get_kernel_instance calls to_str, get
get_name_expression calls to_str
get_plan_execution_time calls to_str, report_timings
make_plan calls to_str
mem_alloc calls to_str, alloc_mem
mem_free calls to_str, free_mem
report calls to_str
report_timings calls to_str
run_autotune_datatypes calls to_str, autotune_transpose_id
select_access_mode_f128 calls to_str
select_access_mode_f32 calls to_str
select_access_mode_f64 calls to_str
alloc_and_set_aux calls alloc_mem
autotune_grid_decomposition calls autotune_grid
autotune_transpose_id calls get_plan_execution_time
create_pencils_and_comm calls create_cart_comm
dtfft_report_c calls report
execute_ptr calls check_aux
get_mangled_name calls get_name_expression
run_autotune_backend calls alloc_mem, free_mem, report_timings, run_autotune_datatypes, alloc_and_set_aux
set_name_expression calls get_name_expression
dtfft_execute_c calls execute_ptr
get calls get_mangled_name