int_to_str_int64 – dtFFT
int_to_str_int64 Function
7 statements
Source File
private function int_to_str_int64(n) result(string)
Convert 64-bit integer to string
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: n
Integer to convert
Return Value character(len=:), allocatable
Resulting string
Called by
Call graph
int_to_str calls int_to_str_int64
alloc_mem calls int_to_str
autotune_grid calls int_to_str, run_autotune_backend, get_plan_execution_time, autotune_mpi_datatypes
autotune_grid_decomposition calls int_to_str, autotune_grid
clean_unused_cache calls int_to_str
compile_and_cache calls int_to_str, get_transpose_kernel_code, get_unpack_kernel_code, get_unpack_pipelined_kernel_code
create_cuda calls int_to_str, clean_unused_cache, create_helper, get_user_stream, run_autotune_backend, alloc_and_set_aux, autotune_grid_decomposition
create_device_pointer calls int_to_str
create_helper calls int_to_str, destroy_helper
create_private calls int_to_str, autotune_grid_decomposition, autotune_grid, get_user_stream
create calls int_to_str, get_user_stream, make_plan, compile_and_cache, create_device_pointer, destroy, create
destroy_helper calls int_to_str
destroy_stream calls int_to_str
destroy calls int_to_str, destroy, clean_unused_cache, destroy_stream
execute_mpi calls int_to_str, execute
execute_nccl calls int_to_str, execute
execute calls int_to_str, execute
free_mem calls int_to_str
get_code_init calls int_to_str
get_plan_execution_time calls int_to_str
get_user_stream calls int_to_str
make_plan calls int_to_str
mem_alloc calls int_to_str, alloc_mem
mem_free calls int_to_str, free_mem
report calls int_to_str
run_autotune_backend calls int_to_str, alloc_mem, create_helper, free_mem, alloc_and_set_aux, destroy, execute
alloc_and_set_aux calls alloc_mem
autotune_transpose_id calls get_plan_execution_time
create_c2c_core calls create_private
create_r2r_internal calls create_private
dtfft_report_c calls report
get_transpose_kernel_code calls get_code_init
get_unpack_kernel_code calls get_code_init
get_unpack_pipelined_kernel_code calls get_code_init
autotune_mpi_datatypes calls autotune_transpose_id
create_c2c calls create_c2c_core
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
destroy_cuda calls destroy, mem_free
dtfft_destroy_c calls destroy
execute_cuda calls execute
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal