int_to_str_int32 – dtFFT
int_to_str_int32 Function
7 statements
Source File
private function int_to_str_int32(n) result(string)
Convert 32-bit integer to string
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: n
Integer to convert
Return Value character(len=:), allocatable
Resulting string
Called by
Call graph
int_to_str calls int_to_str_int32
autotune_grid calls int_to_str, get_plan_execution_time, autotune_mpi_datatypes, run_autotune_backend
autotune_grid_decomposition calls int_to_str, autotune_grid
clean_unused_cache calls int_to_str
compile_and_cache calls int_to_str, get_transpose_kernel_code, get_unpack_kernel_code, get_unpack_pipelined_kernel_code
create calls int_to_str, get_user_stream, make_plan, compile_and_cache, create_device_pointer, destroy, create
create_cuda calls int_to_str, clean_unused_cache, get_user_stream, run_autotune_backend, autotune_grid_decomposition
create_device_pointer calls int_to_str
create_helper calls int_to_str, destroy_helper
create_private calls int_to_str, autotune_grid, autotune_grid_decomposition, create, get_user_stream
destroy calls int_to_str, destroy, clean_unused_cache, destroy_stream
destroy_helper calls int_to_str
destroy_stream calls int_to_str
execute calls int_to_str, execute
execute_mpi calls int_to_str, execute
execute_nccl calls int_to_str, execute
get_code_init calls int_to_str
get_plan_execution_time calls int_to_str
get_user_stream calls int_to_str
make_plan calls int_to_str
mem_alloc calls int_to_str
mem_free calls int_to_str
report calls int_to_str
run_autotune_backend calls int_to_str, create_helper, destroy, execute
autotune_transpose_id calls get_plan_execution_time
create_c2c_internal calls create_private
create_r2r calls create_private
dtfft_report_c calls report
get_transpose_kernel_code calls get_code_init
get_unpack_kernel_code calls get_code_init
get_unpack_pipelined_kernel_code calls get_code_init
autotune_mpi_datatypes calls autotune_transpose_id
create_generic_c2c calls create_c2c_internal
destroy_cuda calls destroy
dtfft_destroy_c calls destroy
execute_cuda calls execute
r2r_constructor calls create_r2r
dtfft_plan_r2r_t calls r2r_constructor
c2c_constructor calls create_generic_c2c
dtfft_plan_c2c_t calls c2c_constructor