is_aux_needed – dtFFT
is_aux_needed Function
4 statements
Source File
private pure function is_aux_needed(self)
Returns true if aux is needed. false otherwise
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(in) :: self
Reshape class
Return Value logical
Calls
Called by
Call graph
is_aux_needed calls get_aux_bytes
get_aux_bytes calls get_aux_bytes_generic
get_aux_bytes_generic calls get_aux_bytes
check_aux calls is_aux_needed
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr