is_backend_compressed – dtFFT
is_backend_compressed Function
5 statements
Source File
public pure elemental function is_backend_compressed(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: param
Return Value logical
Called by
Call graph
autotune_reshape_plan calls is_backend_compressed
create calls is_backend_compressed, autotune_reshape_plan, init, run_autotune_backend, autotune_grid_decomposition
execute calls is_backend_compressed, execute_ptr
init calls is_backend_compressed
report_compression calls is_backend_compressed
run_autotune_backend calls is_backend_compressed
autotune_grid calls run_autotune_backend
dtfft_report_compression_c calls report_compression
execute_2d calls execute
execute_2d_reshape calls execute
execute_generic calls execute
execute_generic_reshape calls execute
execute_z_slab calls execute, execute_generic
execute_z_slab_reshape calls execute
reshape_private calls execute
transpose_private calls execute
autotune_grid_decomposition calls autotune_grid
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_ptr calls execute_private
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
dtfft_execute_c calls execute_ptr