is_backend_compatible – dtFFT
is_backend_compatible Function
9 statements
Source File
private pure function is_backend_compatible(backend1, backend2)
Checks if two communication backends are compatible
Backends are compatible if they belong to the same family: MPI backends are compatible with each other, NCCL with NCCL, NVSHMEM with NVSHMEM.
@return .true. if backends are compatible, .false. otherwise
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: backend1
First backend to compare
type(dtfft_backend_t), intent(in) :: backend2
Second backend to compare
Return Value logical
Calls
Called by
Call graph
is_backend_compatible calls is_backend_mpi, is_backend_nccl, is_backend_nvshmem
autotune_reshape_plan calls is_backend_compatible
create calls is_backend_compatible, autotune_reshape_plan