is_backend_mpi – dtFFT
is_backend_mpi Function
5 statements
Source File
public pure elemental function is_backend_mpi(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: param
Return Value logical
Called by
Call graph
autotune_reshape_plan calls is_backend_mpi, is_backend_compatible
create_mpi calls is_backend_mpi
create calls is_backend_mpi, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan, get_compatible, is_backend_compatible
get_compatible calls is_backend_mpi
is_backend_compatible calls is_backend_mpi
run_autotune_backend calls is_backend_mpi
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid