is_backend_nccl – dtFFT
is_backend_nccl Function
5 statements
Source File
public pure elemental function is_backend_nccl(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: param
Return Value logical
Called by
Call graph
alloc_mem calls is_backend_nccl
autotune_reshape_plan calls is_backend_nccl, is_backend_compatible, execute_autotune, autotune_adaptive
check_create_args calls is_backend_nccl
create calls is_backend_nccl, init, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan, get_compatible, is_backend_compatible
create_nccl calls is_backend_nccl
free_mem calls is_backend_nccl
get_compatible calls is_backend_nccl
init calls is_backend_nccl
is_backend_compatible calls is_backend_nccl
run_autotune_backend calls is_backend_nccl, execute_many, execute_single
alloc_and_set_aux calls alloc_mem
autotune_grid calls run_autotune_backend
create_private calls check_create_args
execute_autotune calls alloc_mem, free_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
mem_free calls free_mem
autotune_adaptive calls execute_autotune
autotune_grid_decomposition calls autotune_grid
create_c2c_core calls create_private
create_r2r_internal calls create_private
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
execute_single_transpose_modes calls run_execute_single
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
execute_single calls execute_single_transpose_modes