is_backend_nvshmem – dtFFT
is_backend_nvshmem Function
5 statements
Source File
public pure elemental function is_backend_nvshmem(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: param
Return Value logical
Called by
Call graph
alloc_mem calls is_backend_nvshmem
autotune_reshape_plan calls is_backend_nvshmem, is_backend_compatible, execute_autotune
check_create_args calls is_backend_nvshmem
check_device_pointers calls is_backend_nvshmem
create calls is_backend_nvshmem, autotune_reshape_plan, get_compatible, is_backend_compatible, run_autotune_backend, autotune_grid_decomposition
free_mem calls is_backend_nvshmem
get_compatible calls is_backend_nvshmem
get_local_sizes calls is_backend_nvshmem
is_backend_compatible calls is_backend_nvshmem
run_autotune_backend calls is_backend_nvshmem, execute_autotune, run_autotune_datatypes
alloc_and_set_aux calls alloc_mem
autotune_grid calls run_autotune_backend
create_private calls check_create_args
dtfft_get_local_sizes_c calls get_local_sizes
execute_autotune calls alloc_mem, free_mem, alloc_and_set_aux
get_alloc_size calls get_local_sizes
mem_alloc calls alloc_mem
mem_free calls free_mem
autotune_grid_decomposition calls autotune_grid
create_c2c_core calls create_private
create_r2r_internal calls create_private
dtfft_get_alloc_size_c calls get_alloc_size
get_alloc_bytes calls get_alloc_size
get_aux_size calls get_alloc_size
get_plan_execution_time calls execute_autotune
autotune_transpose_id calls get_plan_execution_time
check_aux calls get_alloc_bytes, get_aux_bytes
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_aux_size_c calls get_aux_size
get_aux_bytes calls get_aux_size
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
dtfft_get_aux_bytes_c calls get_aux_bytes
execute_ptr calls check_aux
reshape_private calls check_aux
run_autotune_datatypes calls autotune_transpose_id
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr