is_backend_pipelined – dtFFT
is_backend_pipelined Function
5 statements
Source File
public pure elemental function is_backend_pipelined(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: param
Return Value logical
Called by
Call graph
autotune_reshape_plan calls is_backend_pipelined
check_aux calls is_backend_pipelined, get_aux_bytes
create calls is_backend_pipelined, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
get_aux_size calls is_backend_pipelined
run_autotune_backend calls is_backend_pipelined
autotune_grid calls run_autotune_backend
dtfft_get_aux_size_c calls get_aux_size
execute_ptr calls check_aux
get_aux_bytes calls get_aux_size
reshape_private calls check_aux
transpose_private calls check_aux
autotune_grid_decomposition calls autotune_grid
dtfft_execute_c calls execute_ptr
dtfft_get_aux_bytes_c calls get_aux_bytes
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr