is_host_executor – dtFFT
is_host_executor Function
5 statements
Source File
public pure elemental function is_host_executor(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_executor_t), intent(in) :: param
Return Value logical
Called by
Call graph
check_create_args calls is_host_executor
create_private calls check_create_args
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c calls create_c2c_core
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal