is_nvshmem_generic – dtFFT
is_nvshmem_generic Function
16 statements
Source File
private pure function is_nvshmem_generic(plans, backend)
Arguments
Type Intent Optional Attributes Name
type(reshape_container), intent(in) :: plans(:)
Reshape handles
type(dtfft_backend_t), intent(in) :: backend
Return Value logical
Calls
Called by
Call graph
is_nvshmem_generic calls get_backend, is_backend_nvshmem
alloc_and_set_aux calls is_nvshmem_generic
is_nvshmem calls is_nvshmem_generic
execute_autotune calls alloc_and_set_aux
mem_alloc calls is_nvshmem
mem_free calls is_nvshmem
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid