is_nvshmem – dtFFT
is_nvshmem Function
4 statements
Source File
private pure function is_nvshmem(self)
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(in) :: self
Reshape class
Return Value logical
Calls
Called by
Call graph
is_nvshmem calls is_nvshmem_generic
is_nvshmem_generic calls get_backend, is_backend_nvshmem
mem_alloc calls is_nvshmem
mem_free calls is_nvshmem