is_same_ptr – dtFFT
is_same_ptr Function
5 statements
Source File
public elemental function is_same_ptr(ptr1, ptr2)
Checks if two pointer are the same
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: ptr1
First pointer
type(c_ptr), intent(in) :: ptr2
Second pointer
Return Value logical
Called by
Call graph
compress calls is_same_ptr
decompress calls is_same_ptr
execute_ptr calls is_same_ptr, execute_private
execute calls is_same_ptr, execute_ptr, compress, decompress, execute
free_mem calls is_same_ptr
dtfft_execute_c calls execute_ptr
execute_2d calls execute
execute_2d_reshape calls execute
execute_autotune calls free_mem
execute_generic calls execute
execute_generic_reshape calls execute
execute_z_slab calls execute, execute_generic
execute_z_slab_reshape calls execute
mem_free calls free_mem
reshape_private calls execute
transpose_private calls execute
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_end calls execute
execute_fused calls execute
execute_many calls execute_autotune, execute_single
execute_mpi calls execute, execute_fused
execute_nccl calls execute
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
execute_test calls execute
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
run_execute_single calls execute_autotune
test_pack_unpack calls execute
test_transpose calls execute
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_single_transpose_modes calls run_execute_single
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
run_autotune_backend calls execute_many, execute_single
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid