is_unpack_kernel – dtFFT
is_unpack_kernel Function
5 statements
Source File
public pure elemental function is_unpack_kernel(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(kernel_type_t), intent(in) :: param
Return Value logical
Called by
Call graph
create_host calls is_unpack_kernel
create calls is_unpack_kernel, get_code, get_kernel, create
get_code calls is_unpack_kernel
get_kernel calls is_unpack_kernel, get_kernel_args, create_nvrtc_module
get_kernel_args calls is_unpack_kernel
execute_test calls create
execute calls get_kernel_args
create_nvrtc_module calls create
test_device_kernels calls execute_test