is_valid_transpose_type – dtFFT
is_valid_transpose_type Function
5 statements
Source File
public pure elemental function is_valid_transpose_type(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_t), intent(in) :: param
Return Value logical
Called by
Call graph
create calls is_valid_transpose_type, create_reshape_plans, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
create_reshape_plans calls create
get_plan_execution_time calls create
autotune_reshape_plan calls create_reshape_plans
autotune_transpose_id calls get_plan_execution_time
run_autotune_datatypes calls autotune_transpose_id
run_autotune_backend calls run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid