is_valid_executor – dtFFT
is_valid_executor Function
5 statements
Source File
public pure elemental function is_valid_executor(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_executor_t), intent(in) :: param
Return Value logical
Called by
Call graph
check_create_args calls is_valid_executor
create_private calls check_create_args
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal