is_valid_backend – dtFFT
is_valid_backend Function
5 statements
Source File
public pure elemental function is_valid_backend(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: param
Return Value logical
Called by
Call graph
dtfft_set_config calls is_valid_backend, init_internal
get_backend_from_env calls is_valid_backend
dtfft_set_config_c calls dtfft_set_config
init_environment calls get_backend_from_env
init_internal calls init_environment
check_create_args calls init_internal
test_device_kernels calls init_internal
create_private calls check_create_args
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal