is_valid_comm_type – dtFFT
is_valid_comm_type Function
5 statements
Source File
public pure elemental function is_valid_comm_type(param) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: param
Return Value logical
Called by
Call graph
check_create_args calls is_valid_comm_type
create_private calls check_create_args
create_c2c_internal calls create_private
create_r2r calls create_private
create_generic_c2c calls create_c2c_internal
r2r_constructor calls create_r2r
dtfft_plan_r2r_t calls r2r_constructor
c2c_constructor calls create_generic_c2c
dtfft_plan_c2c_t calls c2c_constructor