is_valid_compression_lib – dtFFT
is_valid_compression_lib Function
5 statements
Source File
private pure elemental function is_valid_compression_lib(param) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_compression_lib_t), intent(in) :: param
Return Value logical
Called by
Call graph
check_compression_config calls is_valid_compression_lib
init calls check_compression_config
test_pack_unpack calls check_compression_config
create calls init
test_compression calls test_pack_unpack