load_symbol – dtFFT
load_symbol Function
20 statements
Source File
private function load_symbol(handle, name) result(symbol_handle)
Uses
iso_fortran_env
Dynamically loads symbol from library
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: handle
Loaded handle
character(len=*), intent(in) :: name
Name of function to load
Return Value type(c_funptr)
Function pointer
Calls
Called by
Call graph
load_symbol calls dlsym, is_null_ptr, mpi_abort, astring_f2c, dl_error, write_message
is_null_ptr calls is_null_ptr, is_null_funptr
astring_f2c calls string_f2c
dl_error calls write_message, dlerror, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
string_c2f calls is_null_ptr
dynamic_load calls load_symbol
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
init calls load_cuda, load_nvrtc
load_vkfft calls load
test_device_kernels calls load_cuda, load_nvrtc
create calls load_vkfft, init