load – dtFFT
load Function
19 statements
Source File
private function load(wrapper, suffix) result(error_code)
Loads VkFFT library
Arguments
Type Intent Optional Attributes Name
class(vkfft_wrapper), intent(inout) :: wrapper
VkFFT Wrapper
character(len=*), intent(in) :: suffix
Suffix for the library name
Return Value integer(kind=int32)
Error code
Calls
Called by
Call graph
load calls destroy_strings, dynamic_load
destroy_strings calls destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
is_null_ptr calls is_null_ptr, is_null_funptr
load_library calls is_null_ptr, dlopen, astring_f2c, dl_error
load_symbol calls is_null_ptr, dlsym, mpi_abort, astring_f2c, dl_error, write_message
unload_library calls dlclose, dl_error
astring_f2c calls string_f2c
dl_error calls write_message, dlerror, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
string_c2f calls is_null_ptr
load_vkfft calls load
create calls load_vkfft