load_nvshmem – dtFFT
load_nvshmem Function
23 statements
Source File
public function load_nvshmem() result(error_code)
Loads the NVSHMEM library and needed symbols
Arguments
None
Return Value integer(kind=int32)
Error code
Calls
Called by
Call graph
load_nvshmem calls destroy_strings, dynamic_load
dynamic_load calls is_null_ptr, load_library, load_symbol
is_null_ptr calls is_null_ptr, is_null_funptr
load_library calls is_null_ptr, astring_f2c, dl_error
load_symbol calls is_null_ptr, astring_f2c, dl_error
astring_f2c calls string_f2c
dl_error calls get_log_enabled, string_c2f, write_message
write_message calls mpi_comm_rank, mpi_finalized
create_cuda calls load_nvshmem