load_nvrtc – dtFFT
load_nvrtc Function
31 statements
Source File
public function load_nvrtc() result(error_code)
Dynamically loads nvRTC library and its functions
Arguments
None
Return Value integer(kind=int32)
Error code
Calls
Called by
Call graph
load_nvrtc calls destroy_strings, dynamic_load
destroy_strings calls destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
is_null_ptr calls is_null_ptr, is_null_funptr
load_library calls is_null_ptr, dlopen, astring_f2c, dl_error
load_symbol calls is_null_ptr, dlsym, mpi_abort, astring_f2c, dl_error, write_message
unload_library calls dlclose, dl_error
astring_f2c calls string_f2c
dl_error calls write_message, dlerror, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
string_c2f calls is_null_ptr
init calls load_nvrtc
test_device_kernels calls load_nvrtc
create calls init