load_library – dtFFT
load_library Function
11 statements
Source File
private function load_library(name) result(lib_handle)
Dynamically loads library
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of library to load
Return Value type(c_ptr)
Loaded handle
Calls
Called by
Call graph
load_library calls dlopen, is_null_ptr, astring_f2c, dl_error
is_null_ptr calls is_null_ptr, is_null_funptr
astring_f2c calls string_f2c
dl_error calls dlerror, string_c2f, write_message
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
dynamic_load calls load_library
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
init calls load_cuda, load_nvrtc
load_vkfft calls load
create calls init, load_vkfft