make_plan – dtFFT
make_plan Subroutine
73 statements
Source File
private subroutine make_plan(fft_rank, fft_sizes, mkl_precision, forward_domain, how_many, idist, odist, plan)
Creates general MKL plan
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: fft_rank
Rank of fft: 1 or 2
integer(kind=c_long), intent(in) :: fft_sizes(:)
Dimensions of transform
integer(kind=int32), intent(in) :: mkl_precision
MKL Precision
integer(kind=int32), intent(in) :: forward_domain
C2C or R2C flag
integer(kind=int32), intent(in) :: how_many
Sets DFTI_NUMBER_OF_TRANSFORMS
integer(kind=int32), intent(in) :: idist
Sets DFTI_INPUT_DISTANCE
integer(kind=int32), intent(in) :: odist
Sets DFTI_OUTPUT_DISTANCE
type(c_ptr), intent(inout) :: plan
Resulting plan
Calls
Called by
Call graph
make_plan calls mkl_dfti_commit_desc, mkl_dfti_create_desc, mkl_dfti_set_value, to_str, mpi_abort, dftierrormessage
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
dftierrormessage calls dftierrormessage_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
create calls make_plan