mark_unused – dtFFT
mark_unused Subroutine
12 statements
Source File
private subroutine mark_unused(kernel)
Takes CUDA kernel as an argument and searches for it in cache If kernel is found than reduces ref_count and return null pointer
Arguments
Type Intent Optional Attributes Name
type(CUfunction), intent(inout) :: kernel
CUDA kernel to search for
Calls
Called by
Call graph
mark_unused calls is_same_ptr
destroy calls mark_unused, destroy
create calls destroy, create
destroy_cuda calls destroy
run_autotune_backend calls destroy
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid