mem_alloc_c32_2d – dtFFT
mem_alloc_c32_2d Subroutine
21 statements
Source File
private subroutine mem_alloc_c32_2d(self, alloc_size, ptr, sizes, lbounds, error_code)
Allocates pointer of rank 2
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
integer(kind=int64), intent(in) :: alloc_size
Number of elements to allocate
complex(kind=real32), intent(out), pointer :: ptr(:,:)
integer(kind=int32), intent(in) :: sizes(2)
integer(kind=int32), intent(in), optional :: lbounds(2)
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Call graph
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_ptr calls mem_alloc_host, is_null_ptr, mem_alloc, dtfft_get_error_string, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized