mem_alloc – dtFFT
mem_alloc Subroutine
13 statements
Source File
private subroutine mem_alloc(alloc_bytes, ptr)
Allocates MKL memory
Type Bound
mkl_executor
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: alloc_bytes
Number of bytes to allocate
type(c_ptr), intent(out) :: ptr
Allocated pointer
Calls
Call graph
mem_alloc calls int_to_str, mkl_dfti_mem_alloc, mpi_abort, dftierrormessage
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
dftierrormessage calls dftierrormessage_c, string_c2f