mem_free_ptr – dtFFT
mem_free_ptr Subroutine
28 statements
Source File
private subroutine mem_free_ptr(self, ptr, error_code)
Frees previously allocated memory specific for this plan
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: ptr
Pointer allocated with mem_alloc
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
mem_free_ptr calls mem_free_host, mem_free, dtfft_get_error_string, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized
destroy calls mem_free_ptr
dtfft_mem_free_c calls mem_free_ptr
mem_free_c32_1d calls mem_free_ptr
mem_free_c32_2d calls mem_free_ptr
mem_free_c32_3d calls mem_free_ptr
mem_free_c64_1d calls mem_free_ptr
mem_free_c64_2d calls mem_free_ptr
mem_free_c64_3d calls mem_free_ptr
mem_free_r32_1d calls mem_free_ptr
mem_free_r32_2d calls mem_free_ptr
mem_free_r32_3d calls mem_free_ptr
mem_free_r64_1d calls mem_free_ptr
mem_free_r64_2d calls mem_free_ptr
mem_free_r64_3d calls mem_free_ptr
dtfft_destroy_c calls destroy