mem_free – dtFFT
mem_free Subroutine
12 statements
Source File
private subroutine mem_free(ptr)
Frees MKL aligned memory
Type Bound
mkl_executor
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: ptr
Pointer to free
Calls
Call graph
mem_free calls int_to_str, mkl_dfti_mem_free, mpi_abort, dftierrormessage
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
dftierrormessage calls dftierrormessage_c, string_c2f