mem_free – dtFFT
mem_free Subroutine
6 statements
Source File
private subroutine mem_free(self, ptr, error_code)
Frees memory allocated with mem_alloc
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(inout) :: self
Transposition class
type(c_ptr), intent(in) :: ptr
Pointer to the memory to free
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Call graph
mem_free calls free_mem
free_mem calls fname, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, to_str, mpi_abort, nvshmem_free, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_conf_log_enabled calls get_conf_internal
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr