mem_alloc – dtFFT
mem_alloc Subroutine
11 statements
Source File
private subroutine mem_alloc(self, comm, alloc_bytes, ptr, error_code)
Allocates memory based on selected backend
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(inout) :: self
Reshape class
type(MPI_Comm), intent(in) :: comm
MPI communicator
integer(kind=int64), intent(in) :: alloc_bytes
Number of bytes to allocate
type(c_ptr), intent(out) :: ptr
Pointer to the allocated memory
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Call graph
mem_alloc calls alloc_mem, is_nvshmem
alloc_mem calls fname, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, to_str, is_null_ptr, mpi_abort, mpi_allreduce, cudageterrorstring, dtfft_get_backend_string, get_conf_log_enabled, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, write_message, temp
is_nvshmem calls is_nvshmem_generic
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
cudageterrorstring calls cudageterrorstring_c, string_c2f
get_conf_log_enabled calls get_conf_internal
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr