mem_free – dtFFT
mem_free Subroutine
6 statements
Source File
private subroutine mem_free(self, ptr, error_code)
Frees memory allocated with mem_alloc
Type Bound
abstract_transpose_plan
Arguments
Type Intent Optional Attributes Name
class(abstract_transpose_plan), intent(inout) :: self
Transposition class
type(c_ptr), intent(in) :: ptr
Pointer to the memory to free
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Called by
Call graph
mem_free calls free_mem
free_mem calls cudafree, int_to_str, ncclcommderegister, ncclmemfree, nvshmem_free, mpi_abort, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
destroy_cuda calls mem_free