mem_alloc_r64_2d – dtFFT
mem_alloc_r64_2d Subroutine
14 statements
Source File
private subroutine mem_alloc_r64_2d(self, alloc_size, ptr, shape, error_code)
Allocates real64 pointer of rank 2
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
integer(kind=int64), intent(in) :: alloc_size
Number of real64 elements to allocate
real(kind=real64), intent(out), pointer :: ptr(:,:)
integer(kind=int32), intent(in) :: shape(2)
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
mem_alloc_r64_2d calls mem_alloc
mem_alloc_c32_1d calls mem_alloc
mem_alloc_c32_2d calls mem_alloc
mem_alloc_c32_3d calls mem_alloc
mem_alloc_c64_1d calls mem_alloc
mem_alloc_c64_2d calls mem_alloc
mem_alloc_c64_3d calls mem_alloc
mem_alloc_ptr calls mem_alloc_host, is_null_ptr, mem_alloc, dtfft_get_error_string, get_log_enabled, write_message
mem_alloc_r32_1d calls mem_alloc
mem_alloc_r32_2d calls mem_alloc
mem_alloc_r32_3d calls mem_alloc
mem_alloc_r64_1d calls mem_alloc
mem_alloc_r64_3d calls mem_alloc
write_message calls mpi_comm_rank, mpi_finalized
check_aux calls mem_alloc
dtfft_mem_alloc_c calls mem_alloc
execute calls check_aux
dtfft_execute_c calls execute