mem_alloc_host – dtFFT
mem_alloc_host Function
11 statements
Source File
public function mem_alloc_host(alloc_size) result(ptr)
Allocates memory using C11 Standard alloc_align with 16 bytes alignment
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: alloc_size
Number of bytes to allocate
Return Value type(c_ptr)
Pointer to allocate
Calls
Called by
Call graph
mem_alloc_host calls aligned_alloc
alloc_mem calls mem_alloc_host
compile_program calls mem_alloc_host
create_host calls mem_alloc_host
create calls mem_alloc_host, compile_program, autotune_reshape_plan, get_kernel, run_autotune_backend, autotune_grid_decomposition
execute_test calls mem_alloc_host
mem_alloc_ptr calls mem_alloc_host
test_pack_unpack calls mem_alloc_host
test_transpose calls mem_alloc_host
alloc_and_set_aux calls alloc_mem
check_aux calls mem_alloc_ptr
create_nvrtc_module calls create
dtfft_mem_alloc_c calls mem_alloc_ptr
execute_autotune calls alloc_mem, alloc_and_set_aux
mem_alloc_c32_1d calls mem_alloc_ptr
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_c32_3d calls mem_alloc_ptr
mem_alloc_c64_1d calls mem_alloc_ptr
mem_alloc_c64_2d calls mem_alloc_ptr
mem_alloc_c64_3d calls mem_alloc_ptr
mem_alloc_r32_1d calls mem_alloc_ptr
mem_alloc_r32_2d calls mem_alloc_ptr
mem_alloc_r32_3d calls mem_alloc_ptr
mem_alloc_r64_1d calls mem_alloc_ptr
mem_alloc_r64_2d calls mem_alloc_ptr
mem_alloc_r64_3d calls mem_alloc_ptr
mem_alloc calls alloc_mem
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
execute_ptr calls check_aux
get_kernel calls create_nvrtc_module
reshape_private calls check_aux
run_execute_single calls execute_autotune
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute_single_transpose_modes calls run_execute_single
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
run_autotune_backend calls execute_many, execute_single
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
autotune_grid calls run_autotune_backend
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_single calls execute_single_transpose_modes
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
autotune_grid_decomposition calls autotune_grid