mem_alloc_r64_3d – dtFFT
mem_alloc_r64_3d Subroutine
21 statements
Source File
private subroutine mem_alloc_r64_3d(self, alloc_size, ptr, sizes, lbounds, error_code)
Allocates pointer of rank 3
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
integer(kind=int64), intent(in) :: alloc_size
Number of elements to allocate
real(kind=real64), intent(out), pointer :: ptr(:,:,:)
Allocated pointer
integer(kind=int32), intent(in) :: sizes(3)
Number of elements in each direction
integer(kind=int32), intent(in), optional :: lbounds(3)
Lower boundaries of pointer, default is (1, 1)
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Call graph
mem_alloc_r64_3d calls mem_alloc_ptr
mem_alloc_ptr calls is_null_ptr, mem_alloc, dtfft_get_error_string, mem_alloc_host, write_message
mem_alloc_host calls aligned_alloc
write_message calls mpi_comm_rank, mpi_finalized