mem_alloc_ptr – dtFFT
mem_alloc_ptr Function
37 statements
Source File
private function mem_alloc_ptr(self, alloc_bytes, error_code) result(ptr)
Allocates memory specific for this plan
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
integer(kind=int64), intent(in) :: alloc_bytes
Number of bytes to allocate
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value type(c_ptr)
Allocated pointer
Calls
Called by
Call graph
mem_alloc_ptr calls is_null_ptr, mem_alloc, dtfft_get_error_string, mem_alloc_host, write_message
mem_alloc_host calls aligned_alloc
write_message calls mpi_comm_rank, mpi_finalized
check_aux calls mem_alloc_ptr
dtfft_mem_alloc_c calls mem_alloc_ptr
mem_alloc_c32_1d calls mem_alloc_ptr
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_c32_3d calls mem_alloc_ptr
mem_alloc_c64_1d calls mem_alloc_ptr
mem_alloc_c64_2d calls mem_alloc_ptr
mem_alloc_c64_3d calls mem_alloc_ptr
mem_alloc_r32_1d calls mem_alloc_ptr
mem_alloc_r32_2d calls mem_alloc_ptr
mem_alloc_r32_3d calls mem_alloc_ptr
mem_alloc_r64_1d calls mem_alloc_ptr
mem_alloc_r64_2d calls mem_alloc_ptr
mem_alloc_r64_3d calls mem_alloc_ptr
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr