mem_alloc – dtFFT
mem_alloc Subroutine
8 statements
Source File
private subroutine mem_alloc(self, comm, alloc_bytes, ptr, error_code)
Allocates memory based on selected backend
Type Bound
abstract_transpose_plan
Arguments
Type Intent Optional Attributes Name
class(abstract_transpose_plan), intent(inout) :: self
Transposition class
type(MPI_Comm), intent(in) :: comm
MPI communicator
integer(kind=int64), intent(in) :: alloc_bytes
Number of bytes to allocate
type(c_ptr), intent(out) :: ptr
Pointer to the allocated memory
integer(kind=int32), intent(out) :: error_code
Error code
Calls
Call graph
mem_alloc calls alloc_mem
alloc_mem calls cudamalloc, cudamemgetinfo, int_to_str, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_abort, mpi_allreduce, cudageterrorstring, is_backend_nccl, is_backend_nvshmem, ncclgeterrorstring, temp
int_to_str calls int_to_str_int32, int_to_str_int64, int_to_str_int8
cudageterrorstring calls cudageterrorstring_c, string_c2f
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f