mem_free_c32_2d – dtFFT
mem_free_c32_2d Subroutine
6 statements
Source File
private subroutine mem_free_c32_2d(self, ptr, error_code)
Frees previously allocated memory specific for this plan
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
complex(kind=real32), intent(inout), target :: ptr(:,:)
Pointer allocated with mem_alloc
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Call graph
mem_free_c32_2d calls mem_free_ptr
mem_free_ptr calls mem_free_host, mem_free, dtfft_get_error_string, get_log_enabled, write_message
write_message calls mpi_comm_rank, mpi_finalized