ncclGetErrorString – dtFFT
ncclGetErrorString Function
5 statements
Source File
public function ncclGetErrorString(ncclResult_t) result(string)
Generates an error message.
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int32_t), intent(in) :: ncclResult_t
Completion status of a function.
Return Value character(len=:), allocatable
Error message
Calls
Called by
Call graph
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
alloc_mem calls ncclgeterrorstring
create_helper calls ncclgeterrorstring, destroy_helper
destroy_helper calls ncclgeterrorstring
execute_nccl calls ncclgeterrorstring
free_mem calls ncclgeterrorstring
alloc_and_set_aux calls alloc_mem
autotune_reshape_plan calls create_helper, destroy_helper, execute_autotune
create calls create_helper, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
destroy calls destroy_helper, destroy
execute_autotune calls alloc_mem, free_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
mem_free calls free_mem
run_autotune_backend calls create_helper, destroy_helper, execute_autotune, run_autotune_datatypes
autotune_grid calls run_autotune_backend
get_plan_execution_time calls execute_autotune
autotune_grid_decomposition calls autotune_grid
autotune_transpose_id calls get_plan_execution_time
run_autotune_datatypes calls autotune_transpose_id