nvrtcGetErrorString – dtFFT
nvrtcGetErrorString Function
7 statements
Source File
public function nvrtcGetErrorString(error_code) result(string)
Helper function that returns a string describing the given nvrtcResult code For unrecognized enumeration values, it returns “NVRTC_ERROR unknown”
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: error_code
CUDA Runtime Compilation API result code.
Return Value character(len=:), allocatable
Result string
Calls
Called by
Call graph
nvrtcgeterrorstring calls string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
compile_program calls nvrtcgeterrorstring, set_name_expression
create calls nvrtcgeterrorstring, compile_program, destroy, get_kernel
destroy calls nvrtcgeterrorstring
get_mangled_name calls nvrtcgeterrorstring
set_name_expression calls nvrtcgeterrorstring
create_nvrtc_module calls create
get calls get_mangled_name
get_kernel calls create_nvrtc_module, get_kernel_instance
get_kernel_instance calls get