output – dtFFT
output Subroutine
68 statements
Source File
private subroutine output(self, name, vec)
Uses
iso_fortran_env
iso_c_binding
Writes pencil data to stdout
Type Bound
pencil
Arguments
Type Intent Optional Attributes Name
class(pencil), intent(in) :: self
Pencil
character(len=*), intent(in) :: name
Name of pencil
type(c_ptr), intent(in) :: vec
Calls
Call graph
output calls fname, cudadevicesynchronize, cudamemcpy, is_device_ptr, mpi_abort, mpi_barrier, mpi_comm_rank, mpi_comm_size, cudageterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr