permute_backward_end_pipelined_write_f64_block_64 – dtFFT
permute_backward_end_pipelined_write_f64_block_64 Subroutine
31 statements
Source File
private pure subroutine permute_backward_end_pipelined_write_f64_block_64(in, out, dims, locals)
Backward permutation end of a 3D array for a single neighbor
Backward permutation end is defined as:
out(x,y,z) = in(x,z,y) for 3D arrays
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: in(:)
Source host-allocated buffer
real(kind=real64), intent(inout) :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in) :: dims(:)
Dimensions of the array
integer(kind=int32), intent(in) :: locals(:)
Neighbor data
Called by
Call graph
execute_f64_block_64 calls permute_backward_end_pipelined_write_f64_block_64, permute_backward_end_write_f64_block_64
permute_backward_end_write_f64_block_64 calls permute_backward_end_pipelined_write_f64_block_64