pre_sync – dtFFT
pre_sync Subroutine
33 statements
Source File
private subroutine pre_sync(self, stream)
Uses
iso_fortran_env
iso_c_binding
Type Bound
compressor_zfp
Arguments
Type Intent Optional Attributes Name
class(compressor_zfp), intent(inout) :: self
Abstract kernel
type(dtfft_stream_t), intent(in) :: stream
Calls
Call graph
pre_sync calls fname, cudaeventrecord, cudastreamwaitevent, mpi_abort, cudageterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr