ptr_offset – dtFFT
ptr_offset Function
8 statements
Source File
public pure function ptr_offset(ptr, n_bytes) result(new_ptr)
Returns pointer offset by n_bytes
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: ptr
Original pointer
integer(kind=int64), intent(in) :: n_bytes
Number of bytes to offset
Return Value type(c_ptr)
New pointer
Called by
Call graph
check_aux calls ptr_offset
compress calls ptr_offset
decompress calls ptr_offset
execute_fused calls ptr_offset, execute
execute calls ptr_offset, compress, decompress, execute_ptr, execute
execute_mpi calls execute_fused, execute
execute_ptr calls check_aux
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute_end calls execute
execute_nccl calls execute
execute_test calls execute
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
test_pack_unpack calls execute
test_transpose calls execute
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test