remove – dtFFT
remove Subroutine
14 statements
Source File
private subroutine remove(self, kernel)
Takes CUDA kernel as an argument and searches for it in cache If kernel is found than reduces ref_count of such entry and kernel becomes a null pointer
Type Bound
nvrtc_cache
Arguments
Type Intent Optional Attributes Name
class(nvrtc_cache), intent(inout) :: self
Cache instance
type(CUfunction), intent(inout) :: kernel
CUDA kernel to search for
Calls
Called by
Call graph
remove calls is_null_ptr, is_same_ptr
destroy calls remove, destroy
get_kernel calls remove
create calls destroy, get_kernel, create
destroy_cuda calls destroy
run_autotune_backend calls destroy
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid