report – dtFFT
report Subroutine
67 statements
Source File
private subroutine report(self, error_code)
Prints plan-related information to stdout
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
report calls comm_dims, to_str, dtfft_get_backend_string, dtfft_get_error_string, dtfft_get_executor_string, dtfft_get_precision_string, get_backend, get_grid, get_grid_str, report_backends, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_grid_str calls to_str
report_backends calls dtfft_get_backend_string, write_message, get_backend, mpi_abort
write_message calls mpi_comm_rank, mpi_finalized
dtfft_report_c calls report