report_backends – dtFFT
report_backends Subroutine
20 statements
Source File
private subroutine report_backends(self)
Uses
iso_fortran_env
Reports backends used by each plan. Should be used only for adaptive backend
Type Bound
reshape_plan_base
Arguments
Type Intent Optional Attributes Name
class(reshape_plan_base), intent(in) :: self
Reshape class
Calls
Called by
Call graph
report_backends calls get_backend, mpi_abort, dtfft_get_backend_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
report calls report_backends
dtfft_report_c calls report