report_timings – dtFFT
report_timings Function
20 statements
Source File
public function report_timings(comm, elapsed_time, n_iters, space_count) result(max_time)
Aggregates and writing timings to stdout
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: comm
real(kind=real32), intent(in) :: elapsed_time
integer(kind=int32), intent(in) :: n_iters
integer(kind=int32), intent(in), optional :: space_count
Return Value real(kind=real32)
Calls
Called by
Call graph
report_timings calls to_str, mpi_allreduce, mpi_comm_size, get_conf_log_enabled, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
execute_autotune calls report_timings
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid