report_compression – dtFFT
report_compression Subroutine
10 statements
Source File
private subroutine report_compression(self, name)
Uses
iso_fortran_env
Reports compression average compression ratio by this reshape handle
Type Bound
abstract_reshape_handle
Arguments
Type Intent Optional Attributes Name
class(abstract_reshape_handle), intent(in) :: self
Abstract reshape Handle
character(len=*), intent(in) :: name
Name of the reshape handle
Calls
Called by
Call graph
report_compression calls mpi_abort, write_message, report_compression
write_message calls mpi_comm_rank, mpi_finalized
dtfft_report_compression_c calls report_compression