report_compression – dtFFT
report_compression Subroutine
27 statements
Source File
private subroutine report_compression(self, error_code)
Report compression ratios for all operations where compression was performed This function can be repeatedly called after plan creation and after execution to see how compression ratios evolve.
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(in) :: self
Abstract plan
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
report_compression calls dtfft_get_error_string, get_backend, is_backend_compressed, report_compression, write_message, mpi_abort
write_message calls mpi_comm_rank, mpi_finalized
dtfft_report_compression_c calls report_compression