run_autotune_datatypes – dtFFT
run_autotune_datatypes Subroutine
22 statements
Source File
private subroutine run_autotune_datatypes(create_kwargs, buffer_size, helper, pencils, is_z_slab, best_forward_ids, best_backward_ids, elapsed_time)
Arguments
Type Intent Optional Attributes Name
type(create_args), intent(inout) :: create_kwargs
integer(kind=int64), intent(in) :: buffer_size
type(backend_helper), intent(inout) :: helper
Base MPI_Datatype
type(pencil), intent(in) :: pencils(:)
Source meta
logical, intent(in) :: is_z_slab
Is Z-slab optimization enabled
integer(kind=int8), intent(out) :: best_forward_ids(:)
Best Datatype ids for forward plan
integer(kind=int8), intent(out) :: best_backward_ids(:)
Best Datatype ids for backward plan
real(kind=real32), intent(out) :: elapsed_time
Elapsed time for best plans selected in [ms]
Calls
Called by
Call graph
run_autotune_datatypes calls to_str, autotune_transpose_id, get_conf_log_enabled, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
autotune_transpose_id calls get_plan_execution_time
get_conf_log_enabled calls get_conf_internal
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_plan_execution_time calls to_str, get_conf_log_enabled, write_message, allocate_plans, create, destroy_plans, execute_autotune, pop_nvtx_domain_range, push_nvtx_domain_range
create calls create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, run_autotune_backend, autotune_grid_decomposition
destroy_plans calls destroy
execute_autotune calls execute, fname, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_abort, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic
alloc_mem calls to_str, get_conf_log_enabled, write_message, fname, mpi_abort, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_allreduce, dtfft_get_backend_string, is_backend_nccl, is_backend_nvshmem, mem_alloc_host, ncclgeterrorstring, temp
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls cudageterrorstring_c, string_c2f
free_mem calls to_str, get_conf_log_enabled, write_message, fname, mpi_abort, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_backend_nccl, is_backend_nvshmem, is_same_ptr, ncclgeterrorstring
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
report_timings calls to_str, get_conf_log_enabled, write_message, mpi_allreduce, mpi_comm_size
get_aux_bytes_generic calls get_aux_bytes
mem_alloc_host calls aligned_alloc
ncclgeterrorstring calls string_c2f, ncclgeterrorstring_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
run_autotune_backend calls run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid