run_permute_backward_start – dtFFT
run_permute_backward_start Subroutine
33 statements
Source File
subroutine run_permute_backward_start(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Calls
Called by
Call graph
run_permute_backward_start calls compare, permute_backward_start_read_f32, permute_backward_start_read_f32_block_16, permute_backward_start_read_f32_block_32, permute_backward_start_read_f32_block_4, permute_backward_start_read_f32_block_64, permute_backward_start_read_f32_block_8, permute_backward_start_write_f32, permute_backward_start_write_f32_block_16, permute_backward_start_write_f32_block_32, permute_backward_start_write_f32_block_4, permute_backward_start_write_f32_block_64, permute_backward_start_write_f32_block_8
test_host_kernels calls run_permute_backward_start