run_permute_backward_end – dtFFT
run_permute_backward_end Subroutine
44 statements
Source File
subroutine run_permute_backward_end(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Calls
Called by
Call graph
run_permute_backward_end calls compare, permute_backward_end_read_f32, permute_backward_end_read_f32_block_16, permute_backward_end_read_f32_block_32, permute_backward_end_read_f32_block_4, permute_backward_end_read_f32_block_64, permute_backward_end_read_f32_block_8, permute_backward_end_write_f32, permute_backward_end_write_f32_block_16, permute_backward_end_write_f32_block_32, permute_backward_end_write_f32_block_4, permute_backward_end_write_f32_block_64, permute_backward_end_write_f32_block_8, permute_backward_start_write_f32, permute_backward_write_f32
permute_backward_end_read_f32 calls permute_backward_end_pipelined_read_f32
permute_backward_end_read_f32_block_16 calls permute_backward_end_pipelined_read_f32_block_16
permute_backward_end_read_f32_block_32 calls permute_backward_end_pipelined_read_f32_block_32
permute_backward_end_read_f32_block_4 calls permute_backward_end_pipelined_read_f32_block_4
permute_backward_end_read_f32_block_64 calls permute_backward_end_pipelined_read_f32_block_64
permute_backward_end_read_f32_block_8 calls permute_backward_end_pipelined_read_f32_block_8
permute_backward_end_write_f32 calls permute_backward_end_pipelined_write_f32
permute_backward_end_write_f32_block_16 calls permute_backward_end_pipelined_write_f32_block_16
permute_backward_end_write_f32_block_32 calls permute_backward_end_pipelined_write_f32_block_32
permute_backward_end_write_f32_block_4 calls permute_backward_end_pipelined_write_f32_block_4
permute_backward_end_write_f32_block_64 calls permute_backward_end_pipelined_write_f32_block_64
permute_backward_end_write_f32_block_8 calls permute_backward_end_pipelined_write_f32_block_8
test_host_kernels calls run_permute_backward_end