run_mpi_p2p – dtFFT
run_mpi_p2p Subroutine
32 statements
Source File
private subroutine run_mpi_p2p(comm, send, recv, in, out)
Executes MPI point-to-point communication
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: comm
MPI communicator
type(mpi_backend_helper), intent(inout) :: send
MPI Helper for send data
type(mpi_backend_helper), intent(inout) :: recv
MPI Helper for recv data
real(kind=real32), intent(in) :: in(:)
Data to be sent
real(kind=real32), intent(inout) :: out(:)
Data to be received
Calls
Called by
Call graph
run_mpi_p2p calls mpi_comm_size, mpi_recv_init, mpi_send_init, mpi_startall
execute_mpi calls run_mpi_p2p