run_autotune_backend – dtFFT
run_autotune_backend Subroutine
180 statements
Source File
private subroutine run_autotune_backend(platform, comms, cart_comm, effort, transpose_mode, base_dtype, pencils, base_storage, stream, is_z_slab, is_y_slab, fmodes, bmodes, backend, best_time, best_backend, best_transpose_mode, fbacks, bbacks)
Runs autotune for all backends
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: platform
Platform to create plan for
type(MPI_Comm), intent(in) :: comms(:)
1D comms
type(MPI_Comm), intent(in) :: cart_comm
3D Cartesian comm
type(dtfft_effort_t), intent(in) :: effort
Effort level for the plan creation
type(dtfft_transpose_mode_t), intent(in) :: transpose_mode
Transpose mode to use
type(MPI_Datatype), intent(in) :: base_dtype
Base MPI_Datatype
type(pencil), intent(in) :: pencils(:)
Layouts
integer(kind=int64), intent(in) :: base_storage
Number of bytes needed to store single element
type(dtfft_stream_t), intent(in) :: stream
Stream to use
logical, intent(in) :: is_z_slab
Is Z-slab optimization enabled
logical, intent(in) :: is_y_slab
Is Y-slab optimization enabled
type(dtfft_transpose_mode_t), intent(inout) :: fmodes(:)
Best transpose modes for forward plan
type(dtfft_transpose_mode_t), intent(inout) :: bmodes(:)
Best transpose modes for backward plan
type(dtfft_backend_t), intent(in), optional :: backend
GPU Backend to test. Should be passed only when effort is DTFFT_ESTIMATE or DTFFT_MEASURE
real(kind=real32), intent(out), optional :: best_time
Elapsed time for best backend
type(dtfft_backend_t), intent(out), optional :: best_backend
Best backend selected
type(dtfft_transpose_mode_t), intent(out), optional :: best_transpose_mode
Best transpose mode selected
type(dtfft_backend_t), intent(out), optional :: fbacks(:)
type(dtfft_backend_t), intent(out), optional :: bbacks(:)
Calls
Called by
Call graph
run_autotune_backend calls lbmodes, lbtimes, lfmodes, lftimes, create_helper, destroy_helper, execute_many, execute_single, get_conf_compression_enabled, get_conf_datatype_enabled, get_conf_fused_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, get_conf_rma_enabled, get_conf_transpose, get_correct_backend, is_backend_compressed, is_backend_fused, is_backend_mpi, is_backend_nccl, is_backend_nvshmem, is_backend_pipelined, is_backend_rma
create_helper calls destroy_helper, fname, get_env, ncclcomminitrank, ncclgetuniqueid, mpi_abort, mpi_allgather, mpi_bcast, mpi_comm_rank, mpi_comm_size, ncclgeterrorstring
destroy_helper calls fname, ncclcommdestroy, mpi_abort, ncclgeterrorstring, write_message
execute_many calls execute_single, btimes, ftimes, to_str, allocate_plans, create, destroy_plans, dtfft_get_backend_string, execute_autotune, get_conf_log_enabled, get_local_sizes, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
execute_single calls dtfft_get_backend_string, execute_single_transpose_modes, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
get_conf_compression_enabled calls get_conf_internal
get_conf_datatype_enabled calls get_conf_internal
get_conf_fused_enabled calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_correct_backend calls get_conf_platform
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
allocate_plans calls mpi_abort, write_message
create calls mpi_abort, write_message, create_private, get_reshape_type, get_transpose_type, is_valid_reshape_type, is_valid_transpose_type, run_autotune_backend, autotune_grid_decomposition
destroy_plans calls destroy
execute_autotune calls fname, mpi_abort, execute, cudaeventcreate, cudaeventdestroy, cudaeventelapsedtime, cudaeventrecord, cudaeventsynchronize, cudastreamsynchronize, mpi_barrier, mpi_wtime, alloc_and_set_aux, alloc_mem, cudageterrorstring, dtfft_get_error_string, free_mem, get_conf_measure_iters, get_conf_measure_warmup_iters, report_timings
execute_single_transpose_modes calls run_execute_single
get_conf_log_enabled calls get_conf_internal
ncclgeterrorstring calls ncclgeterrorstring_c, string_c2f
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
alloc_and_set_aux calls mpi_abort, alloc_mem, dtfft_get_error_string, mpi_allreduce, get_aux_bytes_generic, is_nvshmem_generic
alloc_mem calls is_backend_nccl, is_backend_nvshmem, fname, to_str, mpi_abort, dtfft_get_backend_string, get_conf_log_enabled, ncclgeterrorstring, write_message, cudageterrorstring, cudamalloc, cudamemgetinfo, ncclcommregister, ncclmemalloc, nvshmem_malloc, is_null_ptr, mpi_allreduce, mem_alloc_host, temp
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
cudageterrorstring calls string_c2f, cudageterrorstring_c
free_mem calls is_backend_nccl, is_backend_nvshmem, fname, to_str, mpi_abort, get_conf_log_enabled, ncclgeterrorstring, write_message, cudafree, mem_free_host, ncclcommderegister, ncclmemfree, nvshmem_free, is_same_ptr
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls get_env, mpi_abort, write_message
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, write_message, destroy_string
report_timings calls to_str, mpi_comm_size, get_conf_log_enabled, write_message, mpi_allreduce
run_execute_single calls allocate_plans, create, destroy_plans, execute_autotune, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
get_aux_bytes_generic calls get_aux_bytes
is_nvshmem_generic calls is_backend_nvshmem, get_backend
mem_alloc_host calls aligned_alloc
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid