run_pack_unpack – dtFFT
run_pack_unpack Subroutine
40 statements
Source File
subroutine run_pack_unpack(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Calls
Called by
Call graph
run_pack_unpack calls compare, pack_f32, pack_f32_block_16, pack_f32_block_32, pack_f32_block_4, pack_f32_block_64, pack_f32_block_8, unpack_f32, unpack_f32_block_16, unpack_f32_block_32, unpack_f32_block_4, unpack_f32_block_64, unpack_f32_block_8
pack_f32 calls pack_pipelined_f32
pack_f32_block_16 calls pack_pipelined_f32_block_16
pack_f32_block_32 calls pack_pipelined_f32_block_32
pack_f32_block_4 calls pack_pipelined_f32_block_4
pack_f32_block_64 calls pack_pipelined_f32_block_64
pack_f32_block_8 calls pack_pipelined_f32_block_8
unpack_f32 calls unpack_pipelined_f32
unpack_f32_block_16 calls unpack_pipelined_f32_block_16
unpack_f32_block_32 calls unpack_pipelined_f32_block_32
unpack_f32_block_4 calls unpack_pipelined_f32_block_4
unpack_f32_block_64 calls unpack_pipelined_f32_block_64
unpack_f32_block_8 calls unpack_pipelined_f32_block_8
test_host_kernels calls run_pack_unpack