run_permute_backward – dtFFT
run_permute_backward Subroutine
88 statements
Source File
subroutine run_permute_backward(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Calls
Called by
Call graph
run_permute_backward calls compare, pack_backward_read_f32, pack_backward_read_f32_block_16, pack_backward_read_f32_block_32, pack_backward_read_f32_block_4, pack_backward_read_f32_block_64, pack_backward_read_f32_block_8, pack_backward_write_f32, pack_backward_write_f32_block_16, pack_backward_write_f32_block_32, pack_backward_write_f32_block_4, pack_backward_write_f32_block_64, pack_backward_write_f32_block_8, permute_backward_read_f32, permute_backward_read_f32_block_16, permute_backward_read_f32_block_32, permute_backward_read_f32_block_4, permute_backward_read_f32_block_64, permute_backward_read_f32_block_8, permute_backward_write_f32, permute_backward_write_f32_block_16, permute_backward_write_f32_block_32, permute_backward_write_f32_block_4, permute_backward_write_f32_block_64, permute_backward_write_f32_block_8, unpack_backward_read_f32, unpack_backward_read_f32_block_16, unpack_backward_read_f32_block_32, unpack_backward_read_f32_block_4, unpack_backward_read_f32_block_64, unpack_backward_read_f32_block_8, unpack_backward_write_f32, unpack_backward_write_f32_block_16, unpack_backward_write_f32_block_32, unpack_backward_write_f32_block_4, unpack_backward_write_f32_block_64, unpack_backward_write_f32_block_8
unpack_backward_read_f32 calls unpack_backward_pipelined_read_f32
unpack_backward_read_f32_block_16 calls unpack_backward_pipelined_read_f32_block_16
unpack_backward_read_f32_block_32 calls unpack_backward_pipelined_read_f32_block_32
unpack_backward_read_f32_block_4 calls unpack_backward_pipelined_read_f32_block_4
unpack_backward_read_f32_block_64 calls unpack_backward_pipelined_read_f32_block_64
unpack_backward_read_f32_block_8 calls unpack_backward_pipelined_read_f32_block_8
unpack_backward_write_f32 calls unpack_backward_pipelined_write_f32
unpack_backward_write_f32_block_16 calls unpack_backward_pipelined_write_f32_block_16
unpack_backward_write_f32_block_32 calls unpack_backward_pipelined_write_f32_block_32
unpack_backward_write_f32_block_4 calls unpack_backward_pipelined_write_f32_block_4
unpack_backward_write_f32_block_64 calls unpack_backward_pipelined_write_f32_block_64
unpack_backward_write_f32_block_8 calls unpack_backward_pipelined_write_f32_block_8
test_host_kernels calls run_permute_backward