run_permute_forward – dtFFT
run_permute_forward Subroutine
92 statements
Source File
subroutine run_permute_forward(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Calls
Called by
Call graph
run_permute_forward calls compare, pack_forward_read_f32, pack_forward_read_f32_block_16, pack_forward_read_f32_block_32, pack_forward_read_f32_block_4, pack_forward_read_f32_block_64, pack_forward_read_f32_block_8, pack_forward_write_f32, pack_forward_write_f32_block_16, pack_forward_write_f32_block_32, pack_forward_write_f32_block_4, pack_forward_write_f32_block_64, pack_forward_write_f32_block_8, permute_forward_read_f32, permute_forward_read_f32_block_16, permute_forward_read_f32_block_32, permute_forward_read_f32_block_4, permute_forward_read_f32_block_64, permute_forward_read_f32_block_8, permute_forward_write_f32, permute_forward_write_f32_block_16, permute_forward_write_f32_block_32, permute_forward_write_f32_block_4, permute_forward_write_f32_block_64, permute_forward_write_f32_block_8, unpack_forward_read_f32, unpack_forward_read_f32_block_16, unpack_forward_read_f32_block_32, unpack_forward_read_f32_block_4, unpack_forward_read_f32_block_64, unpack_forward_read_f32_block_8, unpack_forward_write_f32, unpack_forward_write_f32_block_16, unpack_forward_write_f32_block_32, unpack_forward_write_f32_block_4, unpack_forward_write_f32_block_64, unpack_forward_write_f32_block_8
unpack_forward_read_f32 calls unpack_forward_pipelined_read_f32
unpack_forward_read_f32_block_16 calls unpack_forward_pipelined_read_f32_block_16
unpack_forward_read_f32_block_32 calls unpack_forward_pipelined_read_f32_block_32
unpack_forward_read_f32_block_4 calls unpack_forward_pipelined_read_f32_block_4
unpack_forward_read_f32_block_64 calls unpack_forward_pipelined_read_f32_block_64
unpack_forward_read_f32_block_8 calls unpack_forward_pipelined_read_f32_block_8
unpack_forward_write_f32 calls unpack_forward_pipelined_write_f32
unpack_forward_write_f32_block_16 calls unpack_forward_pipelined_write_f32_block_16
unpack_forward_write_f32_block_32 calls unpack_forward_pipelined_write_f32_block_32
unpack_forward_write_f32_block_4 calls unpack_forward_pipelined_write_f32_block_4
unpack_forward_write_f32_block_64 calls unpack_forward_pipelined_write_f32_block_64
unpack_forward_write_f32_block_8 calls unpack_forward_pipelined_write_f32_block_8
test_host_kernels calls run_permute_forward