select_kernel – dtFFT
select_kernel Function
111 statements
Source File
private function select_kernel(kernel, base_storage) result(fun)
Uses
iso_fortran_env
Selects the kernel implementation based on the given id and base storage size
Arguments
Type Intent Optional Attributes Name
type(host_kernel_t), intent(in) :: kernel
Kernel id
integer(kind=int64), intent(in) :: base_storage
Size of single element in bytes
Return Value procedure(execute_host_interface), pointer
Selected kernel implementation
Calls
Called by
Call graph
select_kernel calls to_str, mpi_abort, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
write_message calls mpi_comm_rank, mpi_finalized
create_host calls select_kernel