select_access_mode_f128 – dtFFT
select_access_mode_f128 Subroutine
34 statements
Source File
private subroutine select_access_mode_f128(self, in, out, n_warmup_iters, n_iters, execution_time)
Selects the best access mode for host kernels, complex(real64) version
Type Bound
kernel_host
Arguments
Type Intent Optional Attributes Name
class(kernel_host), intent(inout) :: self
Host kernel class
type(c_ptr), intent(in) :: in
Source host-allocated buffer
type(c_ptr), intent(in) :: out
Target host-allocated buffer
integer(kind=int32), intent(in) :: n_warmup_iters
Number of warmup iterations to perform before testing kernel
integer(kind=int32), intent(in) :: n_iters
Number of iterations to perform when testing kernel
real(kind=real64), intent(out) :: execution_time
Execution time of the selected access
Calls
Called by
Call graph
select_access_mode_f128 calls to_str, execute_benchmark, get_conf_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
execute_benchmark calls pop_nvtx_domain_range, push_nvtx_domain_range, write_message, mpi_abort, mpi_wtime
get_conf_log_enabled calls get_conf_internal
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create_host calls select_access_mode_f128