set_name_expression – dtFFT
set_name_expression Subroutine
24 statements
Source File
private subroutine set_name_expression(prog, basic_name, tile_dim, block_rows, padding)
Uses
iso_fortran_env
iso_c_binding
Sets name expression for given template parameters to nvRTC program
Arguments
Type Intent Optional Attributes Name
type(nvrtcProgram), intent(in) :: prog
nvRTC program
character(len=*), intent(in) :: basic_name
Basic kernel name
integer(kind=int32), intent(in) :: tile_dim
Size of shared memory tile, template parameter
integer(kind=int32), intent(in) :: block_rows
Number of rows processed by single thread, template parameter
integer(kind=int32), intent(in) :: padding
Padding to avoid shared memory bank conflicts, template parameter
Calls
Called by
Call graph
set_name_expression calls fname, mpi_abort, get_name_expression, nvrtcgeterrorstring
get_name_expression calls to_str, astring_f2c
nvrtcgeterrorstring calls string_c2f
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
compile_program calls set_name_expression
create calls compile_program, get_kernel
create_nvrtc_module calls create
get_kernel calls create_nvrtc_module