string_f2c – dtFFT
string_f2c Subroutine
21 statements
Source File
public subroutine string_f2c(fstring, cstring, string_size)
Convert Fortran string to C string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fstring
Fortran string
character(kind=c_char, len=1), intent(inout) :: cstring(*)
C string
integer(kind=int64), intent(out), optional :: string_size
Size of the C string
Called by
Call graph
astring_f2c calls string_f2c
dtfft_get_backend_string_c calls string_f2c
dtfft_get_error_string_c calls string_f2c
dtfft_get_executor_string_c calls string_f2c
dtfft_get_precision_string_c calls string_f2c
compile_program calls astring_f2c, set_name_expression
create_nvtx_domain calls astring_f2c
get_name_expression calls astring_f2c
load_library calls astring_f2c
load_symbol calls astring_f2c
push_nvtx_domain_range calls astring_f2c, create_nvtx_domain
autotune_adaptive calls push_nvtx_domain_range
autotune_grid calls push_nvtx_domain_range, run_autotune_backend
autotune_reshape_plan calls push_nvtx_domain_range, autotune_adaptive
compress calls push_nvtx_domain_range
create_c2c_internal calls push_nvtx_domain_range
create_host calls push_nvtx_domain_range, execute_benchmark, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64
create_r2c_internal calls push_nvtx_domain_range
create_r2r_internal calls push_nvtx_domain_range
create calls push_nvtx_domain_range, autotune_grid_decomposition, run_autotune_backend, init, autotune_reshape_plan, compile_program, get_kernel, load_vkfft
decompress calls push_nvtx_domain_range
destroy calls push_nvtx_domain_range
dynamic_load calls load_library, load_symbol
execute_benchmark calls push_nvtx_domain_range
execute_end calls push_nvtx_domain_range, execute
execute_many calls push_nvtx_domain_range, execute_single
execute_ptr calls push_nvtx_domain_range, execute_private
execute_self_copy calls push_nvtx_domain_range
execute_single calls push_nvtx_domain_range, execute_single_transpose_modes
execute calls push_nvtx_domain_range, compress, decompress, execute_ptr, execute_self_copy, execute
get_kernel calls push_nvtx_domain_range, create_nvrtc_module, get_kernel_instance
get_mangled_name calls get_name_expression
reshape_end calls push_nvtx_domain_range, execute_end
reshape_ptr calls push_nvtx_domain_range, reshape_private
reshape_start_ptr calls push_nvtx_domain_range, reshape_private
run_execute_single calls push_nvtx_domain_range
select_access_mode_f128 calls push_nvtx_domain_range, execute_benchmark
select_access_mode_f32 calls push_nvtx_domain_range, execute_benchmark
select_access_mode_f64 calls push_nvtx_domain_range, execute_benchmark
set_name_expression calls get_name_expression
transpose_end calls push_nvtx_domain_range, execute_end
transpose_ptr calls push_nvtx_domain_range, transpose_private
transpose_start_ptr calls push_nvtx_domain_range, transpose_private
autotune_grid_decomposition calls autotune_grid
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_nvrtc_module calls create
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
dtfft_destroy_c calls destroy
dtfft_execute_c calls execute_ptr
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_end_c calls reshape_end
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_end_c calls transpose_end
dtfft_transpose_start_c calls transpose_start_ptr
execute_2d calls execute
execute_2d_reshape calls execute
execute_fused calls execute_self_copy, execute
execute_generic calls execute
execute_generic_reshape calls execute
execute_mpi calls execute_self_copy, execute, execute_fused, execute_p2p_scheduled
execute_nccl calls execute_self_copy, execute
execute_p2p_scheduled calls execute_self_copy
execute_single_transpose_modes calls run_execute_single
execute_test calls execute
execute_z_slab calls execute, execute_generic
execute_z_slab_reshape calls execute
get calls get_mangled_name
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
reshape calls reshape_ptr
reshape_private calls execute
reshape_start calls reshape_start_ptr
run_autotune_backend calls execute_many, execute_single
test_pack_unpack calls execute
test_transpose calls execute
transpose calls transpose_ptr
transpose_private calls execute
transpose_start calls transpose_start_ptr
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
get_kernel_instance calls get
init calls load_cuda, load_nvrtc
load_vkfft calls load
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test, load_cuda, load_nvrtc