string_c2f – dtFFT
string_c2f Subroutine
20 statements
Source File
public subroutine string_c2f(cstring, fstring)
Convert C string to Fortran string
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: cstring
C string
character(len=:), allocatable :: fstring
Fortran string
Calls
Called by
Call graph
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
compile_program calls string_c2f, nvrtcgeterrorstring, set_name_expression
cudageterrorstring calls string_c2f
dftierrormessage calls string_c2f
dl_error calls string_c2f
ncclgeterrorstring calls string_c2f
nvrtcgeterrorstring calls string_c2f
alloc_mem calls cudageterrorstring, ncclgeterrorstring
create_helper calls ncclgeterrorstring, destroy_helper
create_private calls cudageterrorstring, get_conf_stream
create calls compile_program, cudageterrorstring, nvrtcgeterrorstring, destroy, get_kernel, make_plan, get_conf_stream, create_helper, init, run_autotune_backend, autotune_grid_decomposition, load_vkfft, autotune_reshape_plan
destroy_helper calls ncclgeterrorstring
destroy_stream calls cudageterrorstring
destroy calls cudageterrorstring, nvrtcgeterrorstring, dftierrormessage, destroy_helper, destroy_stream, destroy
execute_autotune calls cudageterrorstring, alloc_mem, free_mem, alloc_and_set_aux
execute_mpi calls cudageterrorstring, execute_self_copy, execute_fused, execute_p2p_scheduled
execute_nccl calls ncclgeterrorstring, execute_self_copy
execute_self_copy calls cudageterrorstring
execute_test calls cudageterrorstring
execute calls dftierrormessage, cudageterrorstring, execute_self_copy, execute
free_mem calls ncclgeterrorstring
get calls cudageterrorstring, get_mangled_name
get_conf_stream calls cudageterrorstring
get_kernel calls cudageterrorstring, get_conf_stream, create_nvrtc_module, get_kernel_instance
get_mangled_name calls nvrtcgeterrorstring
load_library calls dl_error
load_symbol calls dl_error
make_plan calls dftierrormessage
mem_alloc calls dftierrormessage, alloc_mem
mem_free calls dftierrormessage, free_mem
output calls cudageterrorstring
post_sync calls cudageterrorstring
pre_sync calls cudageterrorstring
set_name_expression calls nvrtcgeterrorstring
sync calls cudageterrorstring
unload_library calls dl_error
wait calls cudageterrorstring
test_device_kernels calls cudageterrorstring, execute_test, load_cuda, load_nvrtc
alloc_and_set_aux calls alloc_mem
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls create_helper, destroy_helper, execute_autotune, autotune_adaptive
create_c2c_core calls create_private
create_nvrtc_module calls create
create_r2r_internal calls create_private
dynamic_load calls load_library, load_symbol, unload_library
execute_fused calls execute_self_copy
execute_many calls execute_autotune, execute_single
execute_p2p_scheduled calls execute_self_copy
get_kernel_instance calls get
init calls get_conf_stream, load_cuda, load_nvrtc
run_autotune_backend calls create_helper, destroy_helper, execute_many, execute_single
run_execute_single calls execute_autotune
test_pack_unpack calls destroy
autotune_grid calls run_autotune_backend
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
dtfft_destroy_c calls destroy
execute_single_transpose_modes calls run_execute_single
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
test_compression calls test_pack_unpack
autotune_grid_decomposition calls autotune_grid
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
execute_single calls execute_single_transpose_modes
load_vkfft calls load