sync – dtFFT
sync Subroutine
19 statements
Source File
private subroutine sync(self, stream)
Uses
iso_c_binding
iso_fortran_env
Type Bound
compressor_zfp
Arguments
Type Intent Optional Attributes Name
class(compressor_zfp), intent(inout) :: self
Abstract kernel
type(dtfft_stream_t), intent(in) :: stream
Calls
Call graph
sync calls fname, cudastreamsynchronize, mpi_abort, cudageterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr