test_transpose – dtFFT
test_transpose Subroutine
89 statements
Source File
subroutine test_transpose(dims, f, fu, b, bu)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
type(kernel_type_t), intent(in) :: f
type(kernel_type_t), intent(in) :: fu
type(kernel_type_t), intent(in) :: b
type(kernel_type_t), intent(in) :: bu
Calls
Called by
Call graph
test_transpose calls mem_free_host, to_str, mpi_abort, create, destroy_string, execute, get_kernel_string, mem_alloc_host, set_compressor, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create calls create_private
execute calls mpi_abort, write_message, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, sync
mem_alloc_host calls aligned_alloc
write_message calls mpi_comm_rank, mpi_finalized
compress calls to_str, mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, compress_private, is_same_ptr, ptr_offset
decompress calls mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, decompress_private, is_same_ptr, ptr_offset
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
test_compression calls test_transpose