test_pack_unpack – dtFFT
test_pack_unpack Subroutine
48 statements
Source File
subroutine test_pack_unpack(dims)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Calls
Called by
Call graph
test_pack_unpack calls mem_free_host, mpi_abort, check_compression_config, create, destroy, execute, mem_alloc_host, set_compressor, write_message
check_compression_config calls is_valid_compression_lib, is_valid_compression_mode
create calls create_private
destroy calls mpi_abort, fname, cudaeventdestroy, cudageterrorstring
execute calls mpi_abort, write_message, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, sync
mem_alloc_host calls aligned_alloc
write_message calls mpi_comm_rank, mpi_finalized
compress calls mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, compress_private, to_str, is_same_ptr, ptr_offset
cudageterrorstring calls cudageterrorstring_c, string_c2f
decompress calls mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, decompress_private, is_same_ptr, ptr_offset
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr
test_compression calls test_pack_unpack