to_cstr – dtFFT
to_cstr Subroutine
5 statements
Source File
private subroutine to_cstr(self, c_code)
Converts Fortran CUDA code to C pointer
Type Bound
kernel_codegen
Arguments
Type Intent Optional Attributes Name
class(kernel_codegen), intent(in) :: self
Kernel code
character(len=c_char), intent(out), allocatable :: c_code(:)
C pointer to code
Calls
Called by
Call graph
to_cstr calls astring_f2c
astring_f2c calls string_f2c
compile_and_cache calls to_cstr
get_kernel calls compile_and_cache, get_transpose_kernel
get_transpose_kernel calls compile_and_cache
create calls get_kernel, create