transpose_start_ptr – dtFFT
transpose_start_ptr Function
25 statements
Source File
private function transpose_start_ptr(self, in, out, transpose_type, aux, error_code) result(request)
Starts an asynchronous transpose operation using type(c_ptr) pointers instead of buffers
Note
Buffers in and out cannot be the same
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: in
Incoming pointer. Note that values of this pointer will be modified in GPU build
type(c_ptr), intent(in) :: out
Resulting pointer
type(dtfft_transpose_t), intent(in) :: transpose_type
Type of transposition.
type(c_ptr), intent(in) :: aux
Auxiliary buffer. Not optional. If not required, c_null_ptr must be passed. Size of buffer must be greater than value returned by alloc_size parameter of get_local_sizes subroutine
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Return Value type(dtfft_request_t)
Asynchronous handle describing started transpose operation
Calls
Called by
Call graph
transpose_start_ptr calls pop_nvtx_domain_range, push_nvtx_domain_range, transpose_private
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
transpose_private calls check_aux, dtfft_get_error_string, execute, write_message
astring_f2c calls string_f2c
check_aux calls dtfft_get_error_string, write_message, to_str, is_null_ptr, mpi_abort, get_alloc_bytes, get_aux_bytes, get_conf_log_enabled, is_aux_needed, mem_alloc_ptr, ptr_offset
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
execute calls pop_nvtx_domain_range, push_nvtx_domain_range, execute, is_null_ptr, is_same_ptr
write_message calls mpi_comm_rank, mpi_finalized
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_alloc_bytes calls dtfft_get_error_string, write_message, get_alloc_size, get_element_size
get_aux_bytes calls dtfft_get_error_string, write_message, get_aux_size, get_element_size, get_aux_bytes_generic
get_conf_log_enabled calls get_conf_internal
is_aux_needed calls get_aux_bytes
mem_alloc_ptr calls dtfft_get_error_string, write_message, is_null_ptr, mem_alloc, mem_alloc_host
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_alloc_size calls get_local_sizes
get_aux_size calls dtfft_get_error_string, write_message, is_aux_needed, get_alloc_size, get_aux_bytes, get_aux_size_reshape
get_element_size calls dtfft_get_error_string, write_message
mem_alloc_host calls aligned_alloc
get_aux_bytes_generic calls get_aux_bytes
get_aux_size_reshape calls dtfft_get_error_string, write_message, get_element_size, get_aux_bytes_reshape
get_local_sizes calls dtfft_get_error_string, write_message, get_aux_bytes, mpi_allreduce, get_backend, get_local_sizes_internal, get_local_sizes, is_backend_nvshmem
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_local_sizes_internal calls get_local_sizes, counts, starts
dtfft_transpose_start_c calls transpose_start_ptr
transpose_start calls transpose_start_ptr