transpose_private – dtFFT
transpose_private Subroutine
20 statements
Source File
private subroutine transpose_private(self, in, out, aux, transpose_type, exec_type, error_code)
Performs single transposition using type(c_ptr) pointers instead of buffers
Note
Buffers in and out cannot be the same
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(c_ptr), intent(in) :: in
Incoming pointer. Note that values of this pointer will be modified in GPU build
type(c_ptr), intent(in) :: out
Resulting pointer
type(c_ptr), intent(in) :: aux
Auxiliary buffer. Not optional. If not required, c_null_ptr must be passed. Size of buffer must be greater than value returned by alloc_size parameter of get_local_sizes subroutine
type(dtfft_transpose_t), intent(in) :: transpose_type
Type of transposition.
type(async_exec_t), intent(in) :: exec_type
Type of asynchronous execution.
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
transpose_private calls check_aux, dtfft_get_error_string, execute, write_message
check_aux calls dtfft_get_error_string, write_message, to_str, is_null_ptr, mpi_abort, get_alloc_bytes, get_aux_bytes, get_conf_log_enabled, is_aux_needed, mem_alloc_ptr, ptr_offset
execute calls execute, is_null_ptr, is_same_ptr, pop_nvtx_domain_range, push_nvtx_domain_range
write_message calls mpi_comm_rank, mpi_finalized
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
get_alloc_bytes calls dtfft_get_error_string, write_message, get_alloc_size, get_element_size
get_aux_bytes calls dtfft_get_error_string, write_message, get_aux_size, get_element_size, get_aux_bytes_generic
get_conf_log_enabled calls get_conf_internal
is_aux_needed calls get_aux_bytes
mem_alloc_ptr calls dtfft_get_error_string, write_message, is_null_ptr, mem_alloc, mem_alloc_host
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_alloc_size calls get_local_sizes
get_aux_size calls dtfft_get_error_string, write_message, is_aux_needed, get_alloc_size, get_aux_bytes, get_aux_size_reshape
get_element_size calls dtfft_get_error_string, write_message
mem_alloc_host calls aligned_alloc
get_aux_bytes_generic calls get_aux_bytes
get_aux_size_reshape calls dtfft_get_error_string, write_message, get_element_size, get_aux_bytes_reshape
get_local_sizes calls dtfft_get_error_string, write_message, get_aux_bytes, mpi_allreduce, get_backend, get_local_sizes, get_local_sizes_internal, is_backend_nvshmem
get_aux_bytes_reshape calls dtfft_get_error_string, write_message, get_aux_bytes
get_local_sizes_internal calls get_local_sizes, counts, starts
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr