transpose – dtFFT
transpose Subroutine
39 statements
Source File
private subroutine transpose(self, in, out, transpose_type, error_code)
Performs single transposition
Note
Buffers in and out cannot be the same
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(*), intent(inout), target :: in(..)
Incoming buffer of any rank and kind. Note that this buffer will be modified in GPU build
type(*), intent(inout), target :: out(..)
Resulting buffer of any rank and kind
type(dtfft_transpose_type_t), intent(in) :: transpose_type
Type of transposition.
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Call graph
transpose calls check_device_pointers, dtfft_get_error_string, execute, get_gpu_backend, get_log_enabled, is_same_ptr, is_valid_transpose_type, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
check_device_pointers calls is_device_ptr, is_backend_nvshmem, is_nvshmem_ptr
execute calls pop_nvtx_domain_range, push_nvtx_domain_range, execute_private
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
is_nvshmem_ptr calls nvshmem_my_pe, nvshmem_ptr, is_null_ptr
is_null_ptr calls is_same_ptr