transpose_end – dtFFT
transpose_end Subroutine
20 statements
Source File
private subroutine transpose_end(self, request, error_code)
Ends previously started transposition
Type Bound
dtfft_plan_t
Arguments
Type Intent Optional Attributes Name
class(dtfft_plan_t), intent(inout) :: self
Abstract plan
type(dtfft_request_t), intent(inout) :: request
Handle obtained from transpose_start or transpose_start_ptr
integer(kind=int32), intent(out), optional :: error_code
Optional error code returned to user
Calls
Called by
Call graph
transpose_end calls dtfft_get_error_string, execute_end, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
execute_end calls pop_nvtx_domain_range, push_nvtx_domain_range, execute_end
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
dtfft_transpose_end_c calls transpose_end