unload_library – dtFFT
unload_library Subroutine
8 statements
Source File
public subroutine unload_library(handle)
Unloads library
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: handle
Loaded handle
Calls
Called by
Call graph
unload_library calls dlclose, dl_error
dl_error calls dlerror, string_c2f, write_message
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
is_null_ptr calls is_null_ptr, is_null_funptr
dynamic_load calls unload_library
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
init calls load_cuda, load_nvrtc
load_vkfft calls load
test_device_kernels calls load_cuda, load_nvrtc
create calls init, load_vkfft