unpack_forward_pipelined_read_f32_block_64 – dtFFT
unpack_forward_pipelined_read_f32_block_64 Subroutine
47 statements
Source File
private pure subroutine unpack_forward_pipelined_read_f32_block_64(in, out, dims, locals)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout) :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in) :: dims(:)
Dimensions of the array
integer(kind=int32), intent(in) :: locals(:)
Neighbor data
Called by
Call graph
execute_f32_block_64 calls unpack_forward_pipelined_read_f32_block_64, unpack_forward_read_f32_block_64
unpack_forward_read_f32_block_64 calls unpack_forward_pipelined_read_f32_block_64
run_permute_forward calls unpack_forward_read_f32_block_64
test_host_kernels calls run_permute_forward