unpack_pipelined_f32_block_64 – dtFFT
unpack_pipelined_f32_block_64 Subroutine
42 statements
Source File
private pure subroutine unpack_pipelined_f32_block_64(in, out, dims, locals)
Unpacks part of contiguous buffer recieved from a single rank.
For 3D arrays:
out(x + in_displacement, y, z) = in(out_displacement + z * nxx * nyy + y * nxx + x)
where out buffer x,y,z are full slab indices, while in buffer x,y,z are indices that were sent from neighbor rank.
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout) :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in) :: dims(:)
Dimensions of the array
integer(kind=int32), intent(in) :: locals(:)
Neighbor data
Called by
Call graph
execute_f32_block_64 calls unpack_pipelined_f32_block_64, unpack_f32_block_64
unpack_f32_block_64 calls unpack_pipelined_f32_block_64
run_pack_unpack calls unpack_f32_block_64
test_host_kernels calls run_pack_unpack