unpack_forward_write_f32_block_16 – dtFFT
unpack_forward_write_f32_block_16 Subroutine
10 statements
Source File
public pure subroutine unpack_forward_write_f32_block_16(in, out, dims, locals)
Unpacks pack of contiguous buffer recieved from all ranks, real(real32) version.
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout) :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in) :: dims(:)
Dimensions of the array
integer(kind=int32), intent(in) :: locals(:,:)
Neighbor data
Calls
Called by
Call graph
unpack_forward_write_f32_block_16 calls unpack_forward_pipelined_write_f32_block_16
execute_f32_block_16 calls unpack_forward_write_f32_block_16
run_permute_forward calls unpack_forward_write_f32_block_16
test_host_kernels calls run_permute_forward