unpack_backward_pipelined_write_f32_block_4 – dtFFT
unpack_backward_pipelined_write_f32_block_4 Subroutine
33 statements
Source File
private pure subroutine unpack_backward_pipelined_write_f32_block_4(in, out, dims, locals)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: in(:)
Source host-allocated buffer
real(kind=real32), intent(inout) :: out(:)
Target host-allocated buffer
integer(kind=int32), intent(in) :: dims(:)
Dimensions of the array
integer(kind=int32), intent(in) :: locals(:)
Neighbor data
Called by
Call graph
execute_f32_block_4 calls unpack_backward_pipelined_write_f32_block_4, unpack_backward_write_f32_block_4
unpack_backward_write_f32_block_4 calls unpack_backward_pipelined_write_f32_block_4
run_permute_backward calls unpack_backward_write_f32_block_4
test_host_kernels calls run_permute_backward