wait – dtFFT
wait Subroutine
33 statements
Source File
private subroutine wait(self, stream)
Uses
iso_fortran_env
iso_c_binding
Type Bound
abstract_backend
Arguments
Type Intent Optional Attributes Name
class(abstract_backend), intent(inout) :: self
Abstract backend
type(dtfft_stream_t), intent(in) :: stream
CUDA stream
Calls
Call graph
wait calls fname, cudaeventrecord, cudastreamwaitevent, mpi_abort, cudageterrorstring
cudageterrorstring calls cudageterrorstring_c, string_c2f
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr