write_message – dtFFT
write_message Subroutine
31 statements
Source File
public subroutine write_message(unit, message, prefix, is_fatal)
Write message to the specified unit
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: unit
Unit number
character(len=*), intent(in) :: message
Message to write
character(len=*), intent(in), optional :: prefix
Prefix to the message
logical, intent(in), optional :: is_fatal
If true, only rank 0 will print the message, otherwise all ranks will print it
Calls
Called by
Call graph
write_message calls mpi_comm_rank, mpi_finalized
add calls write_message
alloc_fft_plans calls write_message
alloc_mem calls write_message
allocate_plans calls write_message
autotune_adaptive calls write_message, create_reshape_plans, execute_autotune
autotune_grid calls write_message, create_pencils_and_comm, run_autotune_backend
autotune_grid_decomposition calls write_message, autotune_grid
autotune_reshape_plan calls write_message, autotune_adaptive, create_reshape_plans, destroy_helper, create_helper, execute_autotune
check_aux calls write_message, get_alloc_bytes, get_aux_bytes, mem_alloc_ptr
check_create_args calls write_message, init_internal
check_if_overflow calls write_message
compile_program calls write_message
compress calls write_message
create_c2c calls write_message, create_c2c_internal
create_c2c_pencil calls write_message, create_c2c_internal
create_cart_comm calls write_message
create_host calls write_message, execute_benchmark, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64, select_kernel
create_mpi calls write_message
create_nccl calls write_message
create_nvrtc_module calls write_message, add, create
create_pencil_init calls write_message
create_private calls write_message, alloc_fft_plans, check_create_args
create_r2c calls write_message, create_r2c_internal
create_r2c_pencil calls write_message, create_r2c_internal
create_r2r calls write_message, create_r2r_internal
create_r2r_pencil calls write_message, create_r2r_internal
create_reshape_plans calls write_message, allocate_plans, create
create calls write_message, compile_program, destroy, get_code, allocate_plans, autotune_grid_decomposition, init, create_helper, create_pencils_and_comm, run_autotune_backend, check_if_overflow, create, get_kernel, autotune_reshape_plan, create_reshape_plans, load_vkfft
decompress calls write_message
destroy_helper calls write_message
destroy calls write_message, mem_free_ptr, destroy_helper, destroy
dl_error calls write_message
estimate_coalescing calls write_message
execute_benchmark calls write_message
execute_host calls write_message
execute_many calls write_message, allocate_plans, create, execute_single, execute_autotune
execute_single calls write_message, execute_single_transpose_modes
execute_test calls write_message, create, execute
execute calls write_message, compress, decompress, execute, execute_ptr
free_mem calls write_message
from_bricks calls write_message
get calls write_message
get_alloc_bytes calls write_message, get_element_size, get_alloc_size
get_aux_bytes calls write_message, get_alloc_bytes
get_aux_bytes_reshape calls write_message
get_aux_bytes_transpose calls write_message
get_aux_size calls write_message, get_aux_bytes, get_element_size
get_aux_size_reshape calls write_message, get_aux_bytes_reshape, get_element_size
get_aux_size_transpose calls write_message, get_aux_bytes_transpose, get_element_size
get_backend_from_env calls write_message, get_env
get_backend calls write_message
get_code calls write_message
get_dims calls write_message
get_element_size calls write_message
get_env_int32 calls write_message, get_env
get_env_string calls write_message, get_env
get_executor calls write_message
get_grid_dims calls write_message
get_kernel calls write_message, create_nvrtc_module, get_kernel_instance, evaluate_analytical_performance
get_kernel_instance calls write_message, get
get_local_sizes calls write_message
get_pencil calls write_message
get_platform calls write_message
get_precision calls write_message
get_reshape_backend calls write_message
get_stream_ptr calls write_message
get_y_slab_enabled calls write_message
get_z_slab_enabled calls write_message
init calls write_message, load_cuda, load_nvrtc
load_symbol calls write_message, dl_error
mem_alloc_ptr calls write_message
mem_alloc calls write_message, alloc_mem
mem_free_ptr calls write_message
mem_free calls write_message, free_mem
report calls write_message, report_backends
report_backends calls write_message
report_compression calls write_message, report_compression
report_timings calls write_message
reshape_end calls write_message
run_execute_single calls write_message, allocate_plans, create, execute_autotune
select_access_mode_f128 calls write_message, execute_benchmark
select_access_mode_f32 calls write_message, execute_benchmark
select_access_mode_f64 calls write_message, execute_benchmark
select_kernel calls write_message
test_pack_unpack calls write_message, execute
test_transpose calls write_message, execute
transpose_end calls write_message
transpose_private calls write_message, check_aux, execute
get_env calls get_env_int32, get_env_string, get_env_int8, get_env_logical
alloc_and_set_aux calls alloc_mem
create_c2c_core calls create_private, create
create_helper calls destroy_helper, get_env
create_pencils_and_comm calls create_cart_comm
create_r2r_internal calls create_private, create
dtfft_destroy_c calls destroy
dtfft_get_alloc_bytes_c calls get_alloc_bytes
dtfft_get_aux_bytes_c calls get_aux_bytes
dtfft_get_aux_bytes_reshape_c calls get_aux_bytes_reshape
dtfft_get_aux_bytes_transpose_c calls get_aux_bytes_transpose
dtfft_get_aux_size_c calls get_aux_size
dtfft_get_aux_size_reshape_c calls get_aux_size_reshape
dtfft_get_aux_size_transpose_c calls get_aux_size_transpose
dtfft_get_backend_c calls get_backend
dtfft_get_dims_c calls get_dims
dtfft_get_element_size_c calls get_element_size
dtfft_get_executor_c calls get_executor
dtfft_get_grid_dims_c calls get_grid_dims
dtfft_get_local_sizes_c calls get_local_sizes
dtfft_get_pencil_c calls get_pencil
dtfft_get_platform_c calls get_platform
dtfft_get_precision_c calls get_precision
dtfft_get_reshape_backend_c calls get_reshape_backend
dtfft_get_y_slab_enabled_c calls get_y_slab_enabled
dtfft_get_z_slab_enabled_c calls get_z_slab_enabled
dtfft_mem_alloc_c calls mem_alloc_ptr
dtfft_mem_free_c calls mem_free_ptr
dtfft_report_c calls report
dtfft_report_compression_c calls report_compression
dtfft_reshape_end_c calls reshape_end
dtfft_transpose_end_c calls transpose_end
dynamic_load calls load_symbol, load_library, unload_library
evaluate_analytical_performance calls estimate_coalescing
execute_2d calls execute
execute_2d_reshape calls execute
execute_autotune calls alloc_mem, free_mem, report_timings, alloc_and_set_aux
execute_end calls execute
execute_fused calls execute
execute_generic calls execute
execute_generic_reshape calls execute
execute_mpi calls execute, execute_fused
execute_nccl calls execute
execute_ptr calls check_aux, execute_private
execute_single_transpose_modes calls run_execute_single
execute_z_slab calls execute, execute_generic
execute_z_slab_reshape calls execute
get_alloc_size calls get_local_sizes
init_environment calls get_backend_from_env, get_env
load_library calls dl_error
mem_alloc_c32_1d calls mem_alloc_ptr
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_c32_3d calls mem_alloc_ptr
mem_alloc_c64_1d calls mem_alloc_ptr
mem_alloc_c64_2d calls mem_alloc_ptr
mem_alloc_c64_3d calls mem_alloc_ptr
mem_alloc_r32_1d calls mem_alloc_ptr
mem_alloc_r32_2d calls mem_alloc_ptr
mem_alloc_r32_3d calls mem_alloc_ptr
mem_alloc_r64_1d calls mem_alloc_ptr
mem_alloc_r64_2d calls mem_alloc_ptr
mem_alloc_r64_3d calls mem_alloc_ptr
mem_free_c32_1d calls mem_free_ptr
mem_free_c32_2d calls mem_free_ptr
mem_free_c32_3d calls mem_free_ptr
mem_free_c64_1d calls mem_free_ptr
mem_free_c64_2d calls mem_free_ptr
mem_free_c64_3d calls mem_free_ptr
mem_free_r32_1d calls mem_free_ptr
mem_free_r32_2d calls mem_free_ptr
mem_free_r32_3d calls mem_free_ptr
mem_free_r64_1d calls mem_free_ptr
mem_free_r64_2d calls mem_free_ptr
mem_free_r64_3d calls mem_free_ptr
reshape_private calls check_aux, execute
run_autotune_backend calls destroy_helper, execute_many, execute_single, create_helper
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
unload_library calls dl_error
test_compression calls test_pack_unpack, test_transpose, init_internal
test_device_kernels calls execute_test, init_internal, load_cuda, load_nvrtc
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
dtfft_execute_c calls execute_ptr
dtfft_get_alloc_size_c calls get_alloc_size
dtfft_get_stream_c calls get_stream
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
execute_private calls execute_2d, execute_2d_reshape, execute_generic, execute_generic_reshape, execute_z_slab, execute_z_slab_reshape
get_env_int8 calls get_env
get_env_logical calls get_env
get_stream_int64 calls get_stream
init_internal calls init_environment
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_set_config calls init_internal
load_vkfft calls load
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
dtfft_set_config_c calls dtfft_set_config