zfp_stream_set_accuracy – dtFFT
zfp_stream_set_accuracy Subroutine
6 statements
Source File
public subroutine zfp_stream_set_accuracy(stream, acc)
Set accuracy as absolute error tolerance
Arguments
Type Intent Optional Attributes Name
type(zfp_stream), intent(in) :: stream
compressed stream
real(kind=c_double), intent(in) :: acc
desired error tolerance
Calls
Called by
Call graph
zfp_stream_set_accuracy calls zfp_stream_set_accuracy_interface
init calls zfp_stream_set_accuracy
compress calls init
decompress calls init