zfp_stream_set_rate – dtFFT
zfp_stream_set_rate Subroutine
11 statements
Source File
public subroutine zfp_stream_set_rate(stream, field, rate, is_complex)
Set compression rate with alignment for complex data
Arguments
Type Intent Optional Attributes Name
type(zfp_stream), intent(in) :: stream
compressed stream
type(zfp_field), intent(in) :: field
field metadata
real(kind=c_double), intent(in) :: rate
desired rate in compressed bits/scalar
logical, intent(in) :: is_complex
whether data is complex
Calls
Called by
Call graph
zfp_stream_set_rate calls zfp_field_dimensionality, zfp_field_type, zfp_stream_set_rate_interface
init calls zfp_stream_set_rate
compress calls init
decompress calls init