aligned_alloc – dtFFT
aligned_alloc Interface
8 statements
Source File
interface
Called by
private function aligned_alloc(alignment, alloc_size) result(ptr) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_size_t), value :: alignment
Alignment in bytes (16 bytes by default)
integer(kind=c_size_t), value :: alloc_size
Number of bytes to allocate
Return Value type(c_ptr)
Pointer to allocate
Description
Allocates memory using C11 Standard alloc_align with 16 bytes alignment
Call graph
mem_alloc_host calls aligned_alloc
alloc_mem calls mem_alloc_host
compile_program calls mem_alloc_host
create calls mem_alloc_host, compile_program, autotune_reshape_plan, get_kernel, run_autotune_backend, autotune_grid_decomposition
mem_alloc_ptr calls mem_alloc_host
alloc_and_set_aux calls alloc_mem
check_aux calls mem_alloc_ptr
create_nvrtc_module calls create
dtfft_mem_alloc_c calls mem_alloc_ptr
execute_autotune calls alloc_mem, alloc_and_set_aux
mem_alloc_c32_1d calls mem_alloc_ptr
mem_alloc_c32_2d calls mem_alloc_ptr
mem_alloc_c32_3d calls mem_alloc_ptr
mem_alloc_c64_1d calls mem_alloc_ptr
mem_alloc_c64_2d calls mem_alloc_ptr
mem_alloc_c64_3d calls mem_alloc_ptr
mem_alloc_r32_1d calls mem_alloc_ptr
mem_alloc_r32_2d calls mem_alloc_ptr
mem_alloc_r32_3d calls mem_alloc_ptr
mem_alloc_r64_1d calls mem_alloc_ptr
mem_alloc_r64_2d calls mem_alloc_ptr
mem_alloc_r64_3d calls mem_alloc_ptr
mem_alloc calls alloc_mem
autotune_reshape_plan calls execute_autotune
execute_ptr calls check_aux
get_kernel calls create_nvrtc_module
get_plan_execution_time calls execute_autotune
reshape_private calls check_aux
run_autotune_backend calls execute_autotune, run_autotune_datatypes
transpose_private calls check_aux
autotune_grid calls run_autotune_backend
autotune_transpose_id calls get_plan_execution_time
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
autotune_grid_decomposition calls autotune_grid
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
run_autotune_datatypes calls autotune_transpose_id
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr