cudaEventDestroy – dtFFT
cudaEventDestroy Interface
7 statements
Source File
interface
Called by
public function cudaEventDestroy(event) result(cudaError_t) bind(C, name="cudaEventDestroy")
Arguments
Type Intent Optional Attributes Name
type(cudaEvent), value :: event
Event identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the event was destroyed successfully, or an error code if there was an issue.
Description
Destroys an event.
Call graph
destroy calls cudaeventdestroy
execute_autotune calls cudaeventdestroy
get_kernel calls cudaeventdestroy
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
test_pack_unpack calls destroy
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
test_compression calls test_pack_unpack
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid