cudaGetDevice – dtFFT
cudaGetDevice Interface
7 statements
Source File
interface
Called by
public function cudaGetDevice(num) result(cudaError_t) bind(C, name="cudaGetDevice")
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int) :: num
Device number
Return Value integer(kind=c_int)
Returns cudaSuccess if the device was retrieved successfully, or an error code if there was an issue.
Description
Returns the current device.
Call graph
create_private calls cudagetdevice
create calls cudagetdevice
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal