cudaEventCreate – dtFFT
cudaEventCreate Interface
7 statements
Source File
interface
Called by
public function cudaEventCreate(event) result(cudaError_t) bind(C, name="cudaEventCreate")
Arguments
Type Intent Optional Attributes Name
type(cudaEvent) :: event
Event identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the event was created successfully, or an error code if there was an issue.
Description
Creates an event.
Call graph
get_kernel calls cudaeventcreate
run_autotune_backend calls cudaeventcreate
autotune_grid calls run_autotune_backend
create calls get_kernel, run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid