cudaMemGetInfo – dtFFT
cudaMemGetInfo Interface
8 statements
Source File
interface
Called by
public function cudaMemGetInfo(free, total) result(cudaError_t) bind(C, name="cudaMemGetInfo")
Arguments
Type Intent Optional Attributes Name
integer(kind=c_size_t) :: free
Free memory in bytes
integer(kind=c_size_t) :: total
Total memory in bytes
Return Value integer(kind=c_int)
Returns cudaSuccess if the memory information was retrieved successfully, or an error code if there was an issue.
Description
Returns the amount of free and total memory on the device.
Call graph
alloc_mem calls cudamemgetinfo
alloc_and_set_aux calls alloc_mem
execute_autotune calls alloc_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid