cudaFree – dtFFT
cudaFree Interface
7 statements
Source File
interface
Called by
public function cudaFree(ptr) result(cudaError_t) bind(C, name="cudaFree")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: ptr
Pointer to memory to free
Return Value integer(kind=c_int)
Returns cudaSuccess if memory was freed successfully, or an error code if there was an issue.
Description
Frees memory on the device.
Call graph
execute_test calls cudafree
free_mem calls cudafree
get_kernel calls cudafree
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_autotune calls free_mem
mem_free calls free_mem
test_device_kernels calls execute_test
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid