cudaMemcpyAsync – dtFFT
cudaMemcpyAsync Interface
20 statements
Source File
public interface cudaMemcpyAsync
Copies data asynchronously between host and device.
Called by
Functions
private function cudaMemcpyAsync_ptr(dst, src, count, kdir, stream) result(cudaError_t) bind(C, name="cudaMemcpyAsync")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: dst
Destination pointer
type(c_ptr), value :: src
Source pointer
integer(kind=c_size_t), value :: count
Size in bytes to copy
integer(kind=c_int), value :: kdir
Direction of copy (host-to-device, device-to-host, etc.)
type(dtfft_stream_t), value :: stream
Stream identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the copy was initiated successfully, or an error code if there was an issue.
private function cudaMemcpyAsync_r32(dst, src, count, kdir, stream) result(cudaError_t) bind(C, name="cudaMemcpyAsync")
Arguments
Type Intent Optional Attributes Name
real(kind=c_float) :: dst
Destination array (32-bit float)
real(kind=c_float) :: src
Source array (32-bit float)
integer(kind=c_size_t), value :: count
Number of elements to copy
integer(kind=c_int), value :: kdir
Direction of copy
type(dtfft_stream_t), value :: stream
Stream identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the copy was initiated successfully, or an error code if there was an issue.
Call graph
execute calls cudamemcpyasync, execute
execute_mpi calls execute
execute_nccl calls execute
execute_cuda calls execute
run_autotune_backend calls execute
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid