cudaStreamCreate – dtFFT
cudaStreamCreate Interface
7 statements
Source File
interface
Called by
public function cudaStreamCreate(stream) result(cudaError_t) bind(C, name="cudaStreamCreate")
Arguments
Type Intent Optional Attributes Name
type(dtfft_stream_t) :: stream
Pointer to the created stream
Return Value integer(kind=c_int)
Returns cudaSuccess if the stream was created successfully, or an error code if there was an issue.
Description
Creates an asynchronous stream.
Call graph
create calls cudastreamcreate, get_conf_stream, get_kernel, init
get_conf_stream calls cudastreamcreate
test_device_kernels calls cudastreamcreate
create_private calls get_conf_stream
get_kernel calls get_conf_stream
init calls get_conf_stream
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal