cudaEventSynchronize – dtFFT
cudaEventSynchronize Interface
7 statements
Source File
interface
Called by
public function cudaEventSynchronize(event) result(cudaError_t) bind(C, name="cudaEventSynchronize")
Arguments
Type Intent Optional Attributes Name
type(cudaEvent), value :: event
Event identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the event completed successfully, or an error code if there was an issue.
Description
Waits for an event to complete.
Call graph
execute_autotune calls cudaeventsynchronize
get_kernel calls cudaeventsynchronize
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid