cudaStreamWaitEvent – dtFFT
cudaStreamWaitEvent Interface
9 statements
Source File
interface
Called by
public function cudaStreamWaitEvent(stream, event, flags) result(cudaError_t) bind(C, name="cudaStreamWaitEvent")
Arguments
Type Intent Optional Attributes Name
type(dtfft_stream_t), value :: stream
Stream identifier
type(cudaEvent), value :: event
Event identifier
integer(kind=c_int), value :: flags
Flags for the wait operation
Return Value integer(kind=c_int)
Returns cudaSuccess if the stream is waiting successfully, or an error code if there was an issue.
Description
Makes a stream wait on an event.
Call graph
execute_self_copy calls cudastreamwaitevent
post_sync calls cudastreamwaitevent
pre_sync calls cudastreamwaitevent
wait calls cudastreamwaitevent
execute_fused calls execute_self_copy
execute_mpi calls execute_self_copy, execute_fused, execute_p2p_scheduled
execute_nccl calls execute_self_copy
execute_p2p_scheduled calls execute_self_copy
execute calls execute_self_copy, execute