cudaMalloc – dtFFT
cudaMalloc Interface
8 statements
Source File
interface
Called by
public function cudaMalloc(ptr, count) result(cudaError_t) bind(C, name="cudaMalloc")
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: ptr
Pointer to allocated device memory
integer(kind=c_size_t), value :: count
Requested allocation size in bytes
Return Value integer(kind=c_int)
Returns cudaSuccess if memory was allocated successfully, or cudaErrorMemoryAllocation if the memory could not be allocated.
Description
Allocates memory on the device.
Call graph
alloc_mem calls cudamalloc
execute_test calls cudamalloc
get_kernel calls cudamalloc
alloc_and_set_aux calls alloc_mem
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_autotune calls alloc_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
test_device_kernels calls execute_test
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid