cudaEventElapsedTime – dtFFT
cudaEventElapsedTime Interface
9 statements
Source File
interface
Called by
public function cudaEventElapsedTime(time, start, end) result(cudaError_t) bind(C, name="cudaEventElapsedTime")
Arguments
Type Intent Optional Attributes Name
real(kind=c_float) :: time
Elapsed time in milliseconds
type(cudaEvent), value :: start
Starting event
type(cudaEvent), value :: end
Ending event
Return Value integer(kind=c_int)
Returns cudaSuccess if the elapsed time was computed successfully, or an error code if there was an issue.
Description
Computes the elapsed time between two events.
Call graph
get_kernel calls cudaeventelapsedtime
run_autotune_backend calls cudaeventelapsedtime
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
create calls get_kernel, create
autotune_grid_decomposition calls autotune_grid