cudaStreamDestroy – dtFFT
cudaStreamDestroy Interface
7 statements
Source File
interface
Called by
public function cudaStreamDestroy(stream) result(cudaError_t) bind(C, name="cudaStreamDestroy")
Arguments
Type Intent Optional Attributes Name
type(dtfft_stream_t), value :: stream
Stream identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the stream was destroyed successfully, or an error code if there was an issue.
Description
Destroys an asynchronous stream.
Call graph
destroy_stream calls cudastreamdestroy
destroy calls cudastreamdestroy, destroy_stream
test_device_kernels calls cudastreamdestroy
dtfft_destroy_c calls destroy