cudaStreamSynchronize – dtFFT
cudaStreamSynchronize Interface
7 statements
Source File
interface
Called by
public function cudaStreamSynchronize(stream) result(cudaError_t) bind(C, name="cudaStreamSynchronize")
Arguments
Type Intent Optional Attributes Name
type(dtfft_stream_t), value :: stream
Stream identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the stream tasks completed successfully, or an error code if there was an issue.
Description
Waits for stream tasks to complete.
Call graph
execute calls cudastreamsynchronize, execute
execute_autotune calls cudastreamsynchronize
execute_mpi calls cudastreamsynchronize
get_kernel calls cudastreamsynchronize
sync calls cudastreamsynchronize
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid