cudaEventRecord – dtFFT
cudaEventRecord Interface
8 statements
Source File
interface
Called by
public function cudaEventRecord(event, stream) result(cudaError_t) bind(C, name="cudaEventRecord")
Arguments
Type Intent Optional Attributes Name
type(cudaEvent), value :: event
Event identifier
type(dtfft_stream_t), value :: stream
Stream identifier
Return Value integer(kind=c_int)
Returns cudaSuccess if the event was recorded successfully, or an error code if there was an issue.
Description
Records an event in a stream.
Call graph
execute_autotune calls cudaeventrecord
execute_self_copy calls cudaeventrecord
get_kernel calls cudaeventrecord
post_sync calls cudaeventrecord
pre_sync calls cudaeventrecord
wait calls cudaeventrecord
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
create calls get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_fused calls execute_self_copy
execute_many calls execute_autotune, execute_single
execute_mpi calls execute_self_copy, execute_fused, execute_p2p_scheduled
execute_nccl calls execute_self_copy
execute_p2p_scheduled calls execute_self_copy
execute calls execute_self_copy, execute
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid