cuModuleUnload – dtFFT
cuModuleUnload Interface
79 statements
Source File
interface
Called by
public function cuModuleUnload(hmod) result(cuResult) bind(C, name="cuModuleUnload")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: hmod
Module to unload
Return Value integer(kind=c_int)
Driver result code
Description
Unloads a module.
Unloads a module hmod from the current context. Attempting to unload a module which was obtained from the Library Management API such as cuLibraryGetModule will return CUDA_ERROR_NOT_PERMITTED.
Call graph
clean_unused_cache calls cumoduleunload
create_cuda calls clean_unused_cache
destroy calls clean_unused_cache
dtfft_destroy_c calls destroy