dlopen – dtFFT
dlopen Interface
8 statements
Source File
interface
Called by
private function dlopen(filename, mode) bind(C)
Arguments
Type Intent Optional Attributes Name
character(len=c_char) :: filename(*)
Name of the library
integer(kind=c_int), value :: mode
Options to dlopen
Return Value type(c_ptr)
Handle to the library
Description
Load and link a dynamic library
Call graph
load_library calls dlopen
dynamic_load calls load_library
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
create_cuda calls load_cuda, load_nvrtc
load_vkfft calls load
create calls load_vkfft