dlsym – dtFFT
dlsym Interface
8 statements
Source File
interface
Called by
private function dlsym(handle, name) bind(C)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: handle
Handle to the library
character(len=c_char) :: name(*)
Name of the symbol
Return Value type(c_funptr)
Address of the symbol
Description
Get address of a symbol from a dynamic library
Call graph
load_symbol calls dlsym
dynamic_load calls load_symbol
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
init calls load_cuda, load_nvrtc
load_vkfft calls load
create calls init, load_vkfft