dtfft_plan_r2r_t – dtFFT
dtfft_plan_r2r_t Interface
3 statements
Source File
public interface dtfft_plan_r2r_t
R2R Plan Constructor
Calls
Module Procedures
private function r2r_constructor(dims, kinds, comm, precision, effort, executor, error_code) result(plan)
R2R Plan Constructor
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
Global dimensions of transform
type(dtfft_r2r_kind_t), intent(in), optional :: kinds(:)
Kinds of R2R transform
type(MPI_Comm), intent(in), optional :: comm
Communicator
type(dtfft_precision_t), intent(in), optional :: precision
Presicion of Transform
type(dtfft_effort_t), intent(in), optional :: effort
How thoroughly dtFFT searches for the optimal plan
type(dtfft_executor_t), intent(in), optional :: executor
Type of External FFT Executor
integer(kind=int32), intent(out), optional :: error_code
Optional Error Code returned to user
Return Value type(dtfft_plan_r2r_t)
R2R Plan
Call graph
dtfft_plan_r2r_t calls r2r_constructor
r2r_constructor calls create_r2r
create_r2r calls create, fft_mapping, pencils, create_private, dtfft_get_error_string, get_log_enabled, pop_nvtx_domain_range, push_nvtx_domain_range, write_message
create_private calls cudagetdevice, cudagetdevicecount, int_to_str, local_devices, mpi_abort, mpi_allgather, mpi_comm_free, mpi_comm_rank, mpi_comm_size, mpi_comm_split_type, alloc_fft_plans, check_create_args, count_unique, create, cudageterrorstring, get_user_gpu_backend, get_user_stream
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
write_message calls mpi_comm_rank, mpi_finalized
int_to_str calls int_to_str_int32, int_to_str_int8
astring_f2c calls string_f2c
check_create_args calls mpi_topo_test, get_user_platform, init_internal, is_cuda_executor, is_host_executor, is_valid_comm_type, is_valid_dimension, is_valid_effort, is_valid_executor, is_valid_precision, is_valid_r2r_kind
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
create calls get_log_enabled, write_message, int_to_str, mpi_comm_size, create_private, mpi_cart_get, mpi_cartdim_get, mpi_dims_create, mpi_topo_test, get_user_platform, get_z_slab_flag, temp_coords, temp_dims, temp_periods
cudageterrorstring calls cudageterrorstring_c
get_user_gpu_backend calls get_gpu_backend_from_env
get_user_stream calls int_to_str, mpi_abort, cudageterrorstring, cudastreamcreate
get_user_platform calls get_platform_from_env
init_internal calls backends, get_env, mpi_initialized, platforms
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
get_env_int32 calls get_log_enabled, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_log_enabled, write_message, get_env