get_conf_internal – dtFFT
get_conf_internal Interface
4 statements
Source File
private interface get_conf_internal
Returns value from configuration unless environment variable is set
Calls
Called by
Module Procedures
private elemental function get_conf_internal_logical(from_conf, from_env)
Returns value from configuration unless environment variable is set
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: from_conf
Value from configuration
integer(kind=int32), intent(in) :: from_env
Value from environment variable
Return Value logical
private elemental function get_conf_internal_int32(from_conf, from_env)
Returns value from configuration unless environment variable is set
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: from_conf
Value from configuration
integer(kind=int32), intent(in) :: from_env
Value from environment variable
Return Value integer(kind=int32)
Call graph
get_conf_internal calls get_conf_internal_int32, get_conf_internal_logical
get_conf_datatype_enabled calls get_conf_internal
get_conf_fourier_reshape_enabled calls get_conf_internal
get_conf_kernel_autotune_enabled calls get_conf_internal
get_conf_log_enabled calls get_conf_internal
get_conf_measure_iters calls get_conf_internal
get_conf_measure_warmup_iters calls get_conf_internal
get_conf_mpi_enabled calls get_conf_internal
get_conf_nccl_enabled calls get_conf_internal
get_conf_nvshmem_enabled calls get_conf_internal
get_conf_pipelined_enabled calls get_conf_internal
get_conf_y_slab_enabled calls get_conf_internal
get_conf_z_slab_enabled calls get_conf_internal
add calls get_conf_log_enabled
alloc_mem calls get_conf_log_enabled
autotune_grid calls get_conf_log_enabled, run_autotune_backend
autotune_reshape_plan calls get_conf_datatype_enabled, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, execute_autotune
check_aux calls get_conf_log_enabled
create_host calls get_conf_kernel_autotune_enabled, get_conf_log_enabled, get_conf_measure_iters, get_conf_measure_warmup_iters, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64
create_nvrtc_module calls get_conf_log_enabled, add, create
create calls get_conf_log_enabled, get_conf_y_slab_enabled, get_conf_z_slab_enabled, init, run_autotune_backend, autotune_grid_decomposition, get_conf_fourier_reshape_enabled, autotune_reshape_plan, get_kernel
execute_autotune calls get_conf_measure_iters, get_conf_measure_warmup_iters, alloc_mem, free_mem, report_timings, alloc_and_set_aux
free_mem calls get_conf_log_enabled
from_bricks calls get_conf_log_enabled
get_kernel calls get_conf_kernel_autotune_enabled, get_conf_log_enabled, get_conf_measure_iters, get_conf_measure_warmup_iters, create_nvrtc_module, get_kernel_instance
get_kernel_instance calls get_conf_log_enabled
get_plan_execution_time calls get_conf_log_enabled, execute_autotune
init calls get_conf_datatype_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled
report_timings calls get_conf_log_enabled
run_autotune_backend calls get_conf_datatype_enabled, get_conf_log_enabled, get_conf_mpi_enabled, get_conf_nccl_enabled, get_conf_nvshmem_enabled, get_conf_pipelined_enabled, execute_autotune, run_autotune_datatypes
run_autotune_datatypes calls get_conf_log_enabled, autotune_transpose_id
select_access_mode_f128 calls get_conf_log_enabled
select_access_mode_f32 calls get_conf_log_enabled
select_access_mode_f64 calls get_conf_log_enabled
alloc_and_set_aux calls alloc_mem
autotune_grid_decomposition calls autotune_grid
autotune_transpose_id calls get_plan_execution_time
execute_ptr calls check_aux
mem_alloc calls alloc_mem
mem_free calls free_mem
reshape_private calls check_aux
transpose_private calls check_aux
dtfft_execute_c calls execute_ptr
execute calls execute_ptr
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr