get_env – dtFFT
get_env Interface
7 statements
Source File
public interface get_env
Obtains environment variable
Calls
Called by
Module Procedures
private function get_env_base(name) result(env)
Base function of obtaining dtFFT environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
Return Value type(string)
private function get_env_string(name, default, valid_values) result(env)
Obtains string environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
character(len=*), intent(in) :: default
Name of environment variable without prefix
type(string), intent(in) :: valid_values(:)
List of valid variable values
Return Value type(string)
private function get_env_int32(name, default, valid_values, min_valid_value) result(env)
Base Integer function of obtaining dtFFT environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
integer(kind=int32), intent(in) :: default
Default value in case env is not set or it has wrong value
integer(kind=int32), intent(in), optional :: valid_values(:)
List of valid values
integer(kind=int32), intent(in), optional :: min_valid_value
Mininum valid value. Usually 0 or 1
Return Value integer(kind=int32)
private function get_env_int8(name, default, valid_values) result(env)
Obtains int8 environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
integer(kind=int8), intent(in) :: default
Default value in case env is not set or it has wrong value
integer(kind=int32), intent(in) :: valid_values(:)
List of valid values
Return Value integer(kind=int8)
private function get_env_logical(name, default) result(env)
Obtains logical environment variable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Name of environment variable without prefix
logical, intent(in) :: default
Default value in case env is not set or it has wrong value
Return Value logical
Call graph
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
get_env_base calls mpi_bcast, destroy_string
get_env_int32 calls get_env, write_message
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls get_env, destroy_string, write_message
write_message calls mpi_comm_rank, mpi_finalized
create_helper calls get_env
get_backend_from_env calls get_env
get_datatype_from_env calls get_env
init_environment calls get_env, get_backend_from_env
autotune_reshape_plan calls create_helper
create calls create_helper, get_datatype_from_env, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
init_internal calls init_environment
run_autotune_backend calls create_helper
autotune_grid calls run_autotune_backend
check_create_args calls init_internal
dtfft_set_config calls init_internal
autotune_grid_decomposition calls autotune_grid
create_private calls check_create_args
dtfft_set_config_c calls dtfft_set_config
create_c2c_core calls create_private
create_r2r_internal calls create_private
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal