is_device_ptr – dtFFT
is_device_ptr Interface
7 statements
Source File
interface
Called by
public function is_device_ptr(ptr) result(bool) bind(C)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: ptr
Device pointer
Return Value logical(kind=c_bool)
Result
Description
Checks if pointer can be accessed from device
Call graph
check_device_pointers calls is_device_ptr
execute_ptr calls check_device_pointers
transpose_ptr calls check_device_pointers
dtfft_execute_c calls execute_ptr
dtfft_transpose_c calls transpose_ptr
execute calls execute_ptr
transpose calls transpose_ptr