is_null_ptr – dtFFT
is_null_ptr Interface
4 statements
Source File
private interface is_null_ptr
Checks if pointer is NULL
Calls
Called by
Module Procedures
private interface is_null_ptr()
Checks if pointer is NULL
Arguments
None
private elemental function is_null_funptr(ptr)
Checks if pointer is NULL
Arguments
Type Intent Optional Attributes Name
type(c_funptr), intent(in) :: ptr
Pointer to check
Return Value logical
Call graph
is_null_ptr calls is_null_ptr, is_null_funptr
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
load_library calls is_null_ptr, dl_error
load_symbol calls is_null_ptr, dl_error
string_c2f calls is_null_ptr
compile_program calls string_c2f, nvrtcgeterrorstring, set_name_expression
cudageterrorstring calls string_c2f
dftierrormessage calls string_c2f
dl_error calls string_c2f
load calls dynamic_load
load_cuda calls dynamic_load
load_nvrtc calls dynamic_load
ncclgeterrorstring calls string_c2f
nvrtcgeterrorstring calls string_c2f
alloc_mem calls cudageterrorstring, ncclgeterrorstring
create_helper calls ncclgeterrorstring, destroy_helper
create_private calls cudageterrorstring, get_conf_stream
create calls compile_program, cudageterrorstring, nvrtcgeterrorstring, destroy, get_kernel, make_plan, get_conf_stream, create_helper, init, run_autotune_backend, autotune_grid_decomposition, load_vkfft, autotune_reshape_plan
destroy_helper calls ncclgeterrorstring
destroy_stream calls cudageterrorstring
destroy calls cudageterrorstring, nvrtcgeterrorstring, dftierrormessage, destroy_helper, destroy_stream, destroy
execute_autotune calls cudageterrorstring, alloc_mem, free_mem, alloc_and_set_aux
execute_mpi calls cudageterrorstring, execute_self_copy, execute_fused, execute_p2p_scheduled
execute_nccl calls ncclgeterrorstring, execute_self_copy
execute_self_copy calls cudageterrorstring
execute_test calls cudageterrorstring
execute calls dftierrormessage, cudageterrorstring, execute_self_copy, execute
free_mem calls ncclgeterrorstring
get calls cudageterrorstring, get_mangled_name
get_conf_stream calls cudageterrorstring
get_kernel calls cudageterrorstring, get_conf_stream, create_nvrtc_module, get_kernel_instance
get_mangled_name calls nvrtcgeterrorstring
init calls load_cuda, load_nvrtc, get_conf_stream
load_vkfft calls load
make_plan calls dftierrormessage
mem_alloc calls dftierrormessage, alloc_mem
mem_free calls dftierrormessage, free_mem
output calls cudageterrorstring
post_sync calls cudageterrorstring
pre_sync calls cudageterrorstring
set_name_expression calls nvrtcgeterrorstring
sync calls cudageterrorstring
unload_library calls dl_error
wait calls cudageterrorstring
test_device_kernels calls cudageterrorstring, load_cuda, load_nvrtc, execute_test
alloc_and_set_aux calls alloc_mem
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls create_helper, destroy_helper, execute_autotune, autotune_adaptive
create_c2c_core calls create_private
create_nvrtc_module calls create
create_r2r_internal calls create_private
execute_fused calls execute_self_copy
execute_many calls execute_autotune, execute_single
execute_p2p_scheduled calls execute_self_copy
get_kernel_instance calls get
run_autotune_backend calls create_helper, destroy_helper, execute_many, execute_single
run_execute_single calls execute_autotune
test_pack_unpack calls destroy
autotune_grid calls run_autotune_backend
create_c2c_internal calls create_c2c_core
create_r2c_internal calls create_c2c_core
create_r2r calls create_r2r_internal
create_r2r_pencil calls create_r2r_internal
dtfft_destroy_c calls destroy
execute_single_transpose_modes calls run_execute_single
test_compression calls test_pack_unpack
autotune_grid_decomposition calls autotune_grid
create_c2c calls create_c2c_internal
create_c2c_pencil calls create_c2c_internal
create_r2c calls create_r2c_internal
create_r2c_pencil calls create_r2c_internal
execute_single calls execute_single_transpose_modes