mem_free_host – dtFFT
mem_free_host Interface
6 statements
Source File
interface
Called by
public subroutine mem_free_host(ptr) bind(C, name="free")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: ptr
Pointer to free
Description
Frees memory allocated with aligned_alloc
Call graph
create_host calls mem_free_host
create calls mem_free_host, get_kernel, autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_test calls mem_free_host
free_mem calls mem_free_host
mem_free_ptr calls mem_free_host
test_pack_unpack calls mem_free_host
test_transpose calls mem_free_host
create_nvrtc_module calls create
destroy calls mem_free_ptr
dtfft_mem_free_c calls mem_free_ptr
execute_autotune calls free_mem
mem_free_c32_1d calls mem_free_ptr
mem_free_c32_2d calls mem_free_ptr
mem_free_c32_3d calls mem_free_ptr
mem_free_c64_1d calls mem_free_ptr
mem_free_c64_2d calls mem_free_ptr
mem_free_c64_3d calls mem_free_ptr
mem_free_r32_1d calls mem_free_ptr
mem_free_r32_2d calls mem_free_ptr
mem_free_r32_3d calls mem_free_ptr
mem_free_r64_1d calls mem_free_ptr
mem_free_r64_2d calls mem_free_ptr
mem_free_r64_3d calls mem_free_ptr
mem_free calls free_mem
test_compression calls test_pack_unpack, test_transpose
test_device_kernels calls execute_test
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
dtfft_destroy_c calls destroy
execute_many calls execute_autotune, execute_single
get_kernel calls create_nvrtc_module
run_execute_single calls execute_autotune
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid