ncclGetUniqueId – dtFFT
ncclGetUniqueId Interface
7 statements
Source File
interface
Generates an Id to be used in ncclCommInitRank. ncclGetUniqueId should be called once when creating a communicator and the Id should be distributed to all ranks in the communicator before calling ncclCommInitRank. uniqueId should point to a ncclUniqueId object allocated by the user.
Called by
public function ncclGetUniqueId(uniqueId) result(ncclResult_t) bind(C, name="ncclGetUniqueId")
Arguments
Type Intent Optional Attributes Name
type(ncclUniqueId), intent(out) :: uniqueId
Unique ID
Return Value integer(kind=c_int32_t)
Completion status
Call graph
create_helper calls ncclgetuniqueid
autotune_reshape_plan calls create_helper
create calls create_helper, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
run_autotune_backend calls create_helper
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid