ncclMemFree – dtFFT
ncclMemFree Interface
7 statements
Source File
interface
Free memory allocated by ncclMemAlloc().
Called by
public function ncclMemFree(ptr) result(ncclResult_t) bind(C, name="ncclMemFree")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: ptr
Buffer address
Return Value integer(kind=c_int32_t)
Completion status
Call graph
free_mem calls ncclmemfree
execute_autotune calls free_mem
mem_free calls free_mem
autotune_adaptive calls execute_autotune
autotune_reshape_plan calls execute_autotune, autotune_adaptive
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
create calls autotune_reshape_plan, run_autotune_backend, autotune_grid_decomposition
execute_single_transpose_modes calls run_execute_single
run_autotune_backend calls execute_many, execute_single
autotune_grid calls run_autotune_backend
execute_single calls execute_single_transpose_modes
autotune_grid_decomposition calls autotune_grid