ncclCommDestroy – dtFFT
ncclCommDestroy Interface
7 statements
Source File
interface
Destroy a communicator object comm.
Called by
public function ncclCommDestroy(comm) result(ncclResult_t) bind(C, name="ncclCommDestroy")
Arguments
Type Intent Optional Attributes Name
type(ncclComm), value :: comm
Communicator
Return Value integer(kind=c_int32_t)
Completion status
Call graph
destroy_helper calls ncclcommdestroy
autotune_reshape_plan calls destroy_helper, create_helper
create_helper calls destroy_helper
destroy calls destroy_helper, destroy
run_autotune_backend calls destroy_helper, create_helper
autotune_grid calls run_autotune_backend
create calls autotune_reshape_plan, create_helper, run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid