ncclCommDeregister – dtFFT
ncclCommDeregister Interface
8 statements
Source File
interface
Deregister a buffer for collective communication.
Called by
public function ncclCommDeregister(comm, handle) result(ncclResult_t) bind(C, name="ncclCommDeregister")
Arguments
Type Intent Optional Attributes Name
type(ncclComm), value :: comm
Communicator
type(c_ptr), value :: handle
Handle to the registered buffer
Return Value integer(kind=c_int32_t)
Completion status
Call graph
free_mem calls ncclcommderegister
execute_autotune calls free_mem
mem_free calls free_mem
autotune_reshape_plan calls execute_autotune
get_plan_execution_time calls execute_autotune
run_autotune_backend calls execute_autotune, run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_transpose_id calls get_plan_execution_time
create calls run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
autotune_grid_decomposition calls autotune_grid
run_autotune_datatypes calls autotune_transpose_id