ncclMemAlloc – dtFFT
ncclMemAlloc Interface
8 statements
Source File
interface
Allocate a GPU buffer with size. Allocated buffer head address will be returned by ptr, and the actual allocated size can be larger than requested because of the buffer granularity requirements from all types of NCCL optimizations.
Called by
public function ncclMemAlloc(ptr, alloc_bytes) result(ncclResult_t) bind(C, name="ncclMemAlloc")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(out) :: ptr
Buffer address
integer(kind=c_size_t), intent(in), value :: alloc_bytes
Number of bytes to allocate
Return Value integer(kind=c_int32_t)
Completion status
Call graph
alloc_mem calls ncclmemalloc
alloc_and_set_aux calls alloc_mem
mem_alloc calls alloc_mem
run_autotune_backend calls alloc_mem, alloc_and_set_aux
autotune_grid calls run_autotune_backend
create_cuda calls alloc_and_set_aux, run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid