ncclGetErrorString_c – dtFFT
ncclGetErrorString_c Interface
7 statements
Source File
interface
Returns a human-readable string corresponding to the passed error code.
Called by
private function ncclGetErrorString_c(ncclResult_t) result(message) bind(C, name="ncclGetErrorString")
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int32_t), intent(in), value :: ncclResult_t
Completion status of a NCCL function.
Return Value type(c_ptr)
Pointer to message
Call graph
ncclgeterrorstring calls ncclgeterrorstring_c
alloc_mem calls ncclgeterrorstring
create_helper calls ncclgeterrorstring, destroy_helper
destroy_helper calls ncclgeterrorstring
execute_nccl calls ncclgeterrorstring
free_mem calls ncclgeterrorstring
alloc_and_set_aux calls alloc_mem
autotune_reshape_plan calls create_helper, destroy_helper, execute_autotune, autotune_adaptive
create calls create_helper, run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
destroy calls destroy_helper, destroy
execute_autotune calls alloc_mem, free_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
mem_free calls free_mem
run_autotune_backend calls create_helper, destroy_helper, execute_many, execute_single
autotune_adaptive calls execute_autotune
autotune_grid calls run_autotune_backend
execute_many calls execute_autotune, execute_single
run_execute_single calls execute_autotune
autotune_grid_decomposition calls autotune_grid
execute_single_transpose_modes calls run_execute_single
execute_single calls execute_single_transpose_modes