ncclCommInitRank – dtFFT
ncclCommInitRank Interface
10 statements
Source File
interface
Creates a new communicator (multi thread/process version).
rank must be between 0 and nranks-1 and unique within a communicator clique. Each rank is associated to a CUDA device, which has to be set before calling ncclCommInitRank.
ncclCommInitRank implicitly synchronizes with other ranks, hence it must be called by different threads/processes or used within ncclGroupStart/ncclGroupEnd.
Called by
public function ncclCommInitRank(comm, nranks, uniqueId, rank) result(ncclResult_t) bind(C, name="ncclCommInitRank")
Arguments
Type Intent Optional Attributes Name
type(ncclComm) :: comm
Communicator
integer(kind=c_int), value :: nranks
Number of ranks in communicator
type(ncclUniqueId), value :: uniqueId
Unique ID
integer(kind=c_int), value :: rank
Calling rank
Return Value integer(kind=c_int32_t)
Completion status
Call graph
create_helper calls ncclcomminitrank
create calls create_helper, run_autotune_backend, autotune_grid_decomposition
run_autotune_backend calls create_helper
autotune_grid calls run_autotune_backend
autotune_grid_decomposition calls autotune_grid