nvshmem_malloc – dtFFT
nvshmem_malloc Interface
7 statements
Source File
interface
Called by
public function nvshmem_malloc(size) result(ptr) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_size_t), value :: size
Size of the allocation in bytes.
Return Value type(c_ptr)
Pointer to the allocated memory.
Description
Allocates symmetric memory in the NVSHMEM heap.
Call graph
alloc_mem calls nvshmem_malloc
alloc_and_set_aux calls alloc_mem
execute_autotune calls alloc_mem, alloc_and_set_aux
mem_alloc calls alloc_mem
autotune_reshape_plan calls execute_autotune
get_plan_execution_time calls execute_autotune
run_autotune_backend calls execute_autotune, run_autotune_datatypes
autotune_grid calls run_autotune_backend
autotune_transpose_id calls get_plan_execution_time
create calls run_autotune_backend, autotune_grid_decomposition, autotune_reshape_plan
autotune_grid_decomposition calls autotune_grid
run_autotune_datatypes calls autotune_transpose_id