operator(==) – dtFFT
operator(==) Interface
15 statements
Source File
public interface operator(==)
Calls
Module Procedures
private pure elemental function execute_type_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_execute_t), intent(in) :: left
type(dtfft_execute_t), intent(in) :: right
Return Value logical
private pure elemental function transpose_type_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_t), intent(in) :: left
type(dtfft_transpose_t), intent(in) :: right
Return Value logical
private pure elemental function reshape_type_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_reshape_t), intent(in) :: left
type(dtfft_reshape_t), intent(in) :: right
Return Value logical
private pure elemental function executor_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_executor_t), intent(in) :: left
type(dtfft_executor_t), intent(in) :: right
Return Value logical
private pure elemental function effort_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_effort_t), intent(in) :: left
type(dtfft_effort_t), intent(in) :: right
Return Value logical
private pure elemental function precision_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_precision_t), intent(in) :: left
type(dtfft_precision_t), intent(in) :: right
Return Value logical
private pure elemental function r2r_kind_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_r2r_kind_t), intent(in) :: left
type(dtfft_r2r_kind_t), intent(in) :: right
Return Value logical
private pure elemental function platform_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: left
type(dtfft_platform_t), intent(in) :: right
Return Value logical
private pure elemental function exec_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(async_exec_t), intent(in) :: left
type(async_exec_t), intent(in) :: right
Return Value logical
private pure elemental function backend_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: left
type(dtfft_backend_t), intent(in) :: right
Return Value logical
private pure elemental function layout_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_layout_t), intent(in) :: left
type(dtfft_layout_t), intent(in) :: right
Return Value logical
private pure elemental function transpose_mode_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_mode_t), intent(in) :: left
type(dtfft_transpose_mode_t), intent(in) :: right
Return Value logical
private pure elemental function access_mode_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_access_mode_t), intent(in) :: left
type(dtfft_access_mode_t), intent(in) :: right
Return Value logical
Call graph
operator(==) calls access_mode_eq, backend_eq, effort_eq, exec_eq, execute_type_eq, executor_eq, layout_eq, platform_eq, precision_eq, r2r_kind_eq, reshape_type_eq, transpose_mode_eq, transpose_type_eq