operator(==) – dtFFT
operator(==) Interface
10 statements
Source File
public interface operator(==)
Calls
Module Procedures
private pure elemental function execute_type_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_execute_t), intent(in) :: left
type(dtfft_execute_t), intent(in) :: right
Return Value logical
private pure elemental function transpose_type_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_t), intent(in) :: left
type(dtfft_transpose_t), intent(in) :: right
Return Value logical
private pure elemental function executor_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_executor_t), intent(in) :: left
type(dtfft_executor_t), intent(in) :: right
Return Value logical
private pure elemental function effort_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_effort_t), intent(in) :: left
type(dtfft_effort_t), intent(in) :: right
Return Value logical
private pure elemental function precision_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_precision_t), intent(in) :: left
type(dtfft_precision_t), intent(in) :: right
Return Value logical
private pure elemental function r2r_kind_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_r2r_kind_t), intent(in) :: left
type(dtfft_r2r_kind_t), intent(in) :: right
Return Value logical
private pure elemental function platform_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: left
type(dtfft_platform_t), intent(in) :: right
Return Value logical
private pure elemental function gpu_backend_eq(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: left
type(dtfft_backend_t), intent(in) :: right
Return Value logical
Call graph
operator(==) calls effort_eq, execute_type_eq, executor_eq, gpu_backend_eq, platform_eq, precision_eq, r2r_kind_eq, transpose_type_eq