operator(/=) – dtFFT
operator(/=) Interface
14 statements
Source File
public interface operator(/=)
Calls
Module Procedures
private pure elemental function execute_type_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_execute_t), intent(in) :: left
type(dtfft_execute_t), intent(in) :: right
Return Value logical
private pure elemental function transpose_type_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_t), intent(in) :: left
type(dtfft_transpose_t), intent(in) :: right
Return Value logical
private pure elemental function reshape_type_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_reshape_t), intent(in) :: left
type(dtfft_reshape_t), intent(in) :: right
Return Value logical
private pure elemental function executor_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_executor_t), intent(in) :: left
type(dtfft_executor_t), intent(in) :: right
Return Value logical
private pure elemental function effort_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_effort_t), intent(in) :: left
type(dtfft_effort_t), intent(in) :: right
Return Value logical
private pure elemental function precision_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_precision_t), intent(in) :: left
type(dtfft_precision_t), intent(in) :: right
Return Value logical
private pure elemental function r2r_kind_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_r2r_kind_t), intent(in) :: left
type(dtfft_r2r_kind_t), intent(in) :: right
Return Value logical
private pure elemental function platform_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_platform_t), intent(in) :: left
type(dtfft_platform_t), intent(in) :: right
Return Value logical
private pure elemental function backend_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_backend_t), intent(in) :: left
type(dtfft_backend_t), intent(in) :: right
Return Value logical
private pure elemental function layout_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_layout_t), intent(in) :: left
type(dtfft_layout_t), intent(in) :: right
Return Value logical
private pure elemental function transpose_mode_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_transpose_mode_t), intent(in) :: left
type(dtfft_transpose_mode_t), intent(in) :: right
Return Value logical
private pure elemental function access_mode_ne(left, right) result(res)
Arguments
Type Intent Optional Attributes Name
type(dtfft_access_mode_t), intent(in) :: left
type(dtfft_access_mode_t), intent(in) :: right
Return Value logical
Call graph
operator(SLASH=) calls access_mode_ne, backend_ne, effort_ne, execute_type_ne, executor_ne, layout_ne, platform_ne, precision_ne, r2r_kind_ne, reshape_type_ne, transpose_mode_ne, transpose_type_ne