run_cuda_kernel – dtFFT
run_cuda_kernel Interface
14 statements
Source File
interface
Launches a CUDA function CUfunction or a CUDA kernel CUkernel.
Called by
private function run_cuda_kernel(func, in, out, blocks, threads, stream, args, funptr) result(cuResult) bind(C, name="run_cuda_kernel")
Arguments
Type Intent Optional Attributes Name
type(CUfunction), value :: func
Function CUfunction or Kernel CUkernel to launch
type(c_ptr), value :: in
Input pointer
type(c_ptr), value :: out
Output pointer
type(dim3) :: blocks
Grid in blocks
type(dim3) :: threads
Thread block
type(dtfft_stream_t), value :: stream
Stream identifier
type(kernelArgs) :: args
Kernel parameters
type(c_funptr), value :: funptr
Pointer to cuLaunchKernel
Return Value integer(kind=c_int)
Driver result code
Description
Wrapper around cuLaunchKernel, since I have to idea how to pass array of pointers to cuLaunchKernel.
Launches a CUDA function CUfunction or a CUDA kernel CUkernel.
Call graph
culaunchkernel calls run_cuda_kernel
execute calls culaunchkernel, execute
execute_mpi calls execute
execute_nccl calls execute
execute_cuda calls execute
run_autotune_backend calls execute
autotune_grid calls run_autotune_backend
create_cuda calls run_autotune_backend, autotune_grid_decomposition
autotune_grid_decomposition calls autotune_grid