to_str – dtFFT
to_str Interface
7 statements
Source File
public interface to_str
Convert various types to string
Calls
Called by
Module Procedures
private function int8_to_string(n) result(str)
Convert 8-bit integer to string
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: n
Integer to convert
Return Value character(len=:), allocatable
Resulting string
private function int32_to_string(n) result(str)
Convert 32-bit integer to string
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: n
Integer to convert
Return Value character(len=:), allocatable
Resulting string
private function int64_to_string(n) result(str)
Convert 64-bit integer to string
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: n
Integer to convert
Return Value character(len=:), allocatable
Resulting string
private function double_to_string(n) result(str)
Convert double to string
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: n
Double to convert
Return Value character(len=:), allocatable
Resulting string
private function float_to_string(n) result(str)
Convert double to string
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: n
Double to convert
Return Value character(len=:), allocatable
Resulting string
Call graph
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
add calls to_str
alloc_mem calls to_str
autotune_grid calls to_str, create_pencils_and_comm, run_autotune_backend
check_aux calls to_str
compile_program calls to_str, set_name_expression
create_cart_comm calls to_str
create_host calls to_str, select_access_mode_f128, select_access_mode_f32, select_access_mode_f64, select_kernel
create_nvrtc_module calls to_str, add, create
create_pencil_init calls to_str
create calls to_str, autotune_grid_decomposition, create_pencils_and_comm, run_autotune_backend, autotune_reshape_plan, get_kernel, make_plan, compile_program
destroy calls to_str
execute calls to_str, execute_ptr
free_mem calls to_str
get_grid_str calls to_str
get_kernel calls to_str, create_nvrtc_module, get_kernel_instance
get_kernel_instance calls to_str, get
get_name_expression calls to_str
get_plan_execution_time calls to_str, execute_autotune
make_plan calls to_str
mem_alloc calls to_str, alloc_mem
mem_free calls to_str, free_mem
report calls to_str, get_grid_str
report_timings calls to_str
run_autotune_datatypes calls to_str, autotune_transpose_id
select_access_mode_f128 calls to_str
select_access_mode_f32 calls to_str
select_access_mode_f64 calls to_str
select_kernel calls to_str
alloc_and_set_aux calls alloc_mem
autotune_grid_decomposition calls autotune_grid
autotune_transpose_id calls get_plan_execution_time
create_pencils_and_comm calls create_cart_comm
dtfft_report_c calls report
execute_autotune calls alloc_mem, free_mem, report_timings, alloc_and_set_aux
execute_ptr calls check_aux
get_mangled_name calls get_name_expression
reshape_private calls check_aux
run_autotune_backend calls run_autotune_datatypes, execute_autotune
set_name_expression calls get_name_expression
transpose_private calls check_aux
autotune_reshape_plan calls execute_autotune
dtfft_execute_c calls execute_ptr
get calls get_mangled_name
reshape_ptr calls reshape_private
reshape_start_ptr calls reshape_private
transpose_ptr calls transpose_private
transpose_start_ptr calls transpose_private
dtfft_reshape_c calls reshape_ptr
dtfft_reshape_start_c calls reshape_start_ptr
dtfft_transpose_c calls transpose_ptr
dtfft_transpose_start_c calls transpose_start_ptr
reshape calls reshape_ptr
reshape_start calls reshape_start_ptr
transpose calls transpose_ptr
transpose_start calls transpose_start_ptr