zfp_field_dimensionality – dtFFT
zfp_field_dimensionality Interface
7 statements
Source File
interface
Called by
public function zfp_field_dimensionality(field) result(dims) bind(c, name="zfp_field_dimensionality")
Arguments
Type Intent Optional Attributes Name
type(zfp_field), value :: field
field metadata
Return Value integer(kind=c_int)
number of dimensions
Description
Field dimensionality (1, 2, 3, or 4)
Call graph
zfp_field_set_stride calls zfp_field_dimensionality
zfp_stream_set_rate calls zfp_field_dimensionality
init calls zfp_field_set_stride, zfp_stream_set_rate
compress calls init
decompress calls init