zfp_field_set_stride_2d – dtFFT
zfp_field_set_stride_2d Interface
8 statements
Source File
interface
Called by
public subroutine zfp_field_set_stride_2d(field, sx, sy) bind(c, name="zfp_field_set_stride_2d")
Arguments
Type Intent Optional Attributes Name
type(zfp_field), value :: field
field metadata
integer(kind=c_ptrdiff_t), value :: sx
stride in x dimension: &f[0][1] - &f[0][0]
integer(kind=c_ptrdiff_t), value :: sy
stride in y dimension: &f[1][0] - &f[0][0]
Description
Set 2D field strides in number of scalars
Call graph
zfp_field_set_stride calls zfp_field_set_stride_2d
init calls zfp_field_set_stride
compress calls init
decompress calls init