test_host_kernels – dtFFT
test_host_kernels Program
324 statements
Source File
Uses
iso_fortran_env
dtfft_kernel_host
Calls
Variables
Type Attributes Name Initial
real(kind=real32), allocatable :: in(:)
real(kind=real32), allocatable :: out(:)
real(kind=real32), allocatable :: gold(:)
real(kind=real32), allocatable :: temp(:)
integer(kind=int32) :: dims3(3)
integer(kind=int32) :: dims2(2)
integer(kind=int32) :: i
Subroutines
subroutine run_permute_forward(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
subroutine run_permute_backward(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
subroutine run_permute_backward_start(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
subroutine run_permute_backward_end(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
subroutine run_pack_unpack(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
subroutine compare(test_name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: test_name
Call graph
test_host_kernels calls run_pack_unpack, run_permute_backward, run_permute_backward_end, run_permute_backward_start, run_permute_forward
run_pack_unpack calls compare, pack_f32, pack_f32_block_16, pack_f32_block_32, pack_f32_block_4, pack_f32_block_64, pack_f32_block_8, unpack_f32, unpack_f32_block_16, unpack_f32_block_32, unpack_f32_block_4, unpack_f32_block_64, unpack_f32_block_8
run_permute_backward calls compare, pack_backward_read_f32, pack_backward_read_f32_block_16, pack_backward_read_f32_block_32, pack_backward_read_f32_block_4, pack_backward_read_f32_block_64, pack_backward_read_f32_block_8, pack_backward_write_f32, pack_backward_write_f32_block_16, pack_backward_write_f32_block_32, pack_backward_write_f32_block_4, pack_backward_write_f32_block_64, pack_backward_write_f32_block_8, permute_backward_read_f32, permute_backward_read_f32_block_16, permute_backward_read_f32_block_32, permute_backward_read_f32_block_4, permute_backward_read_f32_block_64, permute_backward_read_f32_block_8, permute_backward_write_f32, permute_backward_write_f32_block_16, permute_backward_write_f32_block_32, permute_backward_write_f32_block_4, permute_backward_write_f32_block_64, permute_backward_write_f32_block_8, unpack_backward_read_f32, unpack_backward_read_f32_block_16, unpack_backward_read_f32_block_32, unpack_backward_read_f32_block_4, unpack_backward_read_f32_block_64, unpack_backward_read_f32_block_8, unpack_backward_write_f32, unpack_backward_write_f32_block_16, unpack_backward_write_f32_block_32, unpack_backward_write_f32_block_4, unpack_backward_write_f32_block_64, unpack_backward_write_f32_block_8
run_permute_backward_end calls compare, permute_backward_end_read_f32, permute_backward_end_read_f32_block_16, permute_backward_end_read_f32_block_32, permute_backward_end_read_f32_block_4, permute_backward_end_read_f32_block_64, permute_backward_end_read_f32_block_8, permute_backward_end_write_f32, permute_backward_end_write_f32_block_16, permute_backward_end_write_f32_block_32, permute_backward_end_write_f32_block_4, permute_backward_end_write_f32_block_64, permute_backward_end_write_f32_block_8, permute_backward_start_write_f32, permute_backward_write_f32
run_permute_backward_start calls compare, permute_backward_start_read_f32, permute_backward_start_read_f32_block_16, permute_backward_start_read_f32_block_32, permute_backward_start_read_f32_block_4, permute_backward_start_read_f32_block_64, permute_backward_start_read_f32_block_8, permute_backward_start_write_f32, permute_backward_start_write_f32_block_16, permute_backward_start_write_f32_block_32, permute_backward_start_write_f32_block_4, permute_backward_start_write_f32_block_64, permute_backward_start_write_f32_block_8
run_permute_forward calls compare, pack_forward_read_f32, pack_forward_read_f32_block_16, pack_forward_read_f32_block_32, pack_forward_read_f32_block_4, pack_forward_read_f32_block_64, pack_forward_read_f32_block_8, pack_forward_write_f32, pack_forward_write_f32_block_16, pack_forward_write_f32_block_32, pack_forward_write_f32_block_4, pack_forward_write_f32_block_64, pack_forward_write_f32_block_8, permute_forward_read_f32, permute_forward_read_f32_block_16, permute_forward_read_f32_block_32, permute_forward_read_f32_block_4, permute_forward_read_f32_block_64, permute_forward_read_f32_block_8, permute_forward_write_f32, permute_forward_write_f32_block_16, permute_forward_write_f32_block_32, permute_forward_write_f32_block_4, permute_forward_write_f32_block_64, permute_forward_write_f32_block_8, unpack_forward_read_f32, unpack_forward_read_f32_block_16, unpack_forward_read_f32_block_32, unpack_forward_read_f32_block_4, unpack_forward_read_f32_block_64, unpack_forward_read_f32_block_8, unpack_forward_write_f32, unpack_forward_write_f32_block_16, unpack_forward_write_f32_block_32, unpack_forward_write_f32_block_4, unpack_forward_write_f32_block_64, unpack_forward_write_f32_block_8
pack_f32 calls pack_pipelined_f32
pack_f32_block_16 calls pack_pipelined_f32_block_16
pack_f32_block_32 calls pack_pipelined_f32_block_32
pack_f32_block_4 calls pack_pipelined_f32_block_4
pack_f32_block_64 calls pack_pipelined_f32_block_64
pack_f32_block_8 calls pack_pipelined_f32_block_8
permute_backward_end_read_f32 calls permute_backward_end_pipelined_read_f32
permute_backward_end_read_f32_block_16 calls permute_backward_end_pipelined_read_f32_block_16
permute_backward_end_read_f32_block_32 calls permute_backward_end_pipelined_read_f32_block_32
permute_backward_end_read_f32_block_4 calls permute_backward_end_pipelined_read_f32_block_4
permute_backward_end_read_f32_block_64 calls permute_backward_end_pipelined_read_f32_block_64
permute_backward_end_read_f32_block_8 calls permute_backward_end_pipelined_read_f32_block_8
permute_backward_end_write_f32 calls permute_backward_end_pipelined_write_f32
permute_backward_end_write_f32_block_16 calls permute_backward_end_pipelined_write_f32_block_16
permute_backward_end_write_f32_block_32 calls permute_backward_end_pipelined_write_f32_block_32
permute_backward_end_write_f32_block_4 calls permute_backward_end_pipelined_write_f32_block_4
permute_backward_end_write_f32_block_64 calls permute_backward_end_pipelined_write_f32_block_64
permute_backward_end_write_f32_block_8 calls permute_backward_end_pipelined_write_f32_block_8
unpack_backward_read_f32 calls unpack_backward_pipelined_read_f32
unpack_backward_read_f32_block_16 calls unpack_backward_pipelined_read_f32_block_16
unpack_backward_read_f32_block_32 calls unpack_backward_pipelined_read_f32_block_32
unpack_backward_read_f32_block_4 calls unpack_backward_pipelined_read_f32_block_4
unpack_backward_read_f32_block_64 calls unpack_backward_pipelined_read_f32_block_64
unpack_backward_read_f32_block_8 calls unpack_backward_pipelined_read_f32_block_8
unpack_backward_write_f32 calls unpack_backward_pipelined_write_f32
unpack_backward_write_f32_block_16 calls unpack_backward_pipelined_write_f32_block_16
unpack_backward_write_f32_block_32 calls unpack_backward_pipelined_write_f32_block_32
unpack_backward_write_f32_block_4 calls unpack_backward_pipelined_write_f32_block_4
unpack_backward_write_f32_block_64 calls unpack_backward_pipelined_write_f32_block_64
unpack_backward_write_f32_block_8 calls unpack_backward_pipelined_write_f32_block_8
unpack_f32 calls unpack_pipelined_f32
unpack_f32_block_16 calls unpack_pipelined_f32_block_16
unpack_f32_block_32 calls unpack_pipelined_f32_block_32
unpack_f32_block_4 calls unpack_pipelined_f32_block_4
unpack_f32_block_64 calls unpack_pipelined_f32_block_64
unpack_f32_block_8 calls unpack_pipelined_f32_block_8
unpack_forward_read_f32 calls unpack_forward_pipelined_read_f32
unpack_forward_read_f32_block_16 calls unpack_forward_pipelined_read_f32_block_16
unpack_forward_read_f32_block_32 calls unpack_forward_pipelined_read_f32_block_32
unpack_forward_read_f32_block_4 calls unpack_forward_pipelined_read_f32_block_4
unpack_forward_read_f32_block_64 calls unpack_forward_pipelined_read_f32_block_64
unpack_forward_read_f32_block_8 calls unpack_forward_pipelined_read_f32_block_8
unpack_forward_write_f32 calls unpack_forward_pipelined_write_f32
unpack_forward_write_f32_block_16 calls unpack_forward_pipelined_write_f32_block_16
unpack_forward_write_f32_block_32 calls unpack_forward_pipelined_write_f32_block_32
unpack_forward_write_f32_block_4 calls unpack_forward_pipelined_write_f32_block_4
unpack_forward_write_f32_block_64 calls unpack_forward_pipelined_write_f32_block_64
unpack_forward_write_f32_block_8 calls unpack_forward_pipelined_write_f32_block_8