test_compression – dtFFT
test_compression Program
161 statements
Source File
Uses
iso_c_binding
dtfft_kernel_host
mpi_f08
dtfft_config
dtfft_parameters
dtfft_utils
dtfft_compressor_zfp
iso_fortran_env
dtfft_abstract_kernel
dtfft_abstract_compressor
Calls
Variables
Type Attributes Name Initial
integer(kind=int32) :: ierror
type(dtfft_stream_t) :: stream
Subroutines
subroutine test_pack_unpack(dims)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
subroutine test_transpose(dims, f, fu, b, bu)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
type(kernel_type_t), intent(in) :: f
type(kernel_type_t), intent(in) :: fu
type(kernel_type_t), intent(in) :: b
type(kernel_type_t), intent(in) :: bu
Call graph
test_compression calls mpi_finalize, mpi_init, init_internal, test_pack_unpack, test_transpose
init_internal calls mpi_initialized, init_environment
test_pack_unpack calls mem_free_host, mpi_abort, create, destroy, execute, mem_alloc_host, set_compressor, write_message
test_transpose calls mem_free_host, to_str, mpi_abort, create, destroy_string, execute, get_kernel_string, mem_alloc_host, set_compressor, write_message
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create calls create_private
destroy calls mpi_abort, fname, cudaeventdestroy, cudageterrorstring
execute calls mpi_abort, write_message, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, sync
init_environment calls access_modes, destroy, get_env, platforms, destroy_strings, get_backend_from_env, transpose_modes
mem_alloc_host calls aligned_alloc
write_message calls mpi_comm_rank, mpi_finalized
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
compress calls to_str, mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, compress_private, is_same_ptr, ptr_offset
cudageterrorstring calls cudageterrorstring_c, string_c2f
decompress calls mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, decompress_private, is_same_ptr, ptr_offset
destroy_strings calls destroy_string
get_backend_from_env calls destroy_string, write_message, get_env, destroy_strings, is_valid_backend
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls mpi_abort, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls destroy_string, write_message, get_env
string_c2f calls is_null_ptr
is_null_ptr calls is_null_ptr, is_null_funptr