test_device_kernels – dtFFT
test_device_kernels Program
224 statements
Source File
Uses
dtfft_kernel_device
iso_c_binding
dtfft_interface_cuda
iso_fortran_env
dtfft_abstract_kernel
dtfft_parameters
dtfft_utils
dtfft_interface_nvrtc
dtfft_interface_cuda_runtime
dtfft_config
dtfft_kernel_host
mpi_f08
Calls
Variables
Type Attributes Name Initial
integer(kind=int32) :: ierror
type(dtfft_stream_t) :: stream
Subroutines
subroutine execute_test(dims, kernel_type)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: dims(:)
type(kernel_type_t), intent(in) :: kernel_type
Call graph
test_device_kernels calls fname, cudastreamcreate, cudastreamdestroy, mpi_abort, mpi_finalize, mpi_init, cudageterrorstring, execute_test, init_internal, load_cuda, load_nvrtc
cudageterrorstring calls cudageterrorstring_c, string_c2f
execute_test calls fname, mpi_abort, cudageterrorstring, cudadevicesynchronize, cudafree, cudamalloc, cudamemcpy, mem_free_host, to_str, create, destroy, execute, get_kernel_string, mem_alloc_host, write_message
init_internal calls mpi_initialized, init_environment
load_cuda calls destroy_strings, dynamic_load
load_nvrtc calls destroy_strings, dynamic_load
to_str calls double_to_string, float_to_string, int32_to_string, int64_to_string, int8_to_string
create calls mpi_abort, destroy, get_kernel_string, write_message, create_private, is_pack_kernel, is_unpack_kernel
destroy_strings calls destroy_string
destroy calls destroy_private, destroy_string
dynamic_load calls is_null_ptr, load_library, load_symbol, unload_library
execute calls mpi_abort, write_message, execute_private, post_sync, pre_sync, bytes_to_floats, compress, decompress, pop_nvtx_domain_range, push_nvtx_domain_range, sync
init_environment calls destroy_strings, access_modes, destroy, get_env, platforms, get_backend_from_env, transpose_modes
mem_alloc_host calls aligned_alloc
string_c2f calls is_null_ptr
write_message calls mpi_comm_rank, mpi_finalized
get_env calls get_env_base, get_env_int32, get_env_int8, get_env_logical, get_env_string
is_null_ptr calls is_null_ptr, is_null_funptr
compress calls mpi_abort, to_str, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, compress_private, is_same_ptr, ptr_offset
decompress calls mpi_abort, write_message, pop_nvtx_domain_range, push_nvtx_domain_range, decompress_private, is_same_ptr, ptr_offset
get_backend_from_env calls destroy_strings, write_message, get_env, destroy_string, is_valid_backend
load_library calls is_null_ptr, dlopen, astring_f2c, dl_error
load_symbol calls mpi_abort, write_message, is_null_ptr, dlsym, astring_f2c, dl_error
pop_nvtx_domain_range calls nvtxdomainrangepop_c
push_nvtx_domain_range calls nvtxdomainrangepushex_c, astring_f2c, create_nvtx_domain
unload_library calls dlclose, dl_error
astring_f2c calls string_f2c
create_nvtx_domain calls astring_f2c, nvtxdomaincreate_c
dl_error calls string_c2f, write_message, dlerror
get_env_base calls destroy_string, mpi_bcast
get_env_int32 calls mpi_abort, write_message, get_env
get_env_int8 calls get_env
get_env_logical calls get_env
get_env_string calls write_message, get_env, destroy_string