name: dtfft test

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Requirements
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get -y install gfortran-10
          sudo apt-get install libopenmpi-dev openmpi-bin libhdf5-openmpi-dev
          sudo apt-get install libfftw3-dev
          export OMPI_FC=gfortran-10
          export OMPI_CC=gcc-10
          export OMPI_CXX=g++-10
      - name: Checkout
        uses: actions/checkout@v4
      - run: mkdir build
      - run: cmake --version
      - run: ls -lah
      - run: pwd
      - name: Setup and run tests
        working-directory: ./build
        run: |
          cmake -DCMAKE_C_COMPILER=gcc-10 \
            -DCMAKE_CXX_COMPILER=g++-10 \
            -DCMAKE_Fortran_COMPILER=gfortran-10 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDTFFT_ENABLE_COVERAGE=on \
            -DDTFFT_BUILD_C_CXX_API=on ..
          make && make coverage
          make install
          ls -lah /usr/local/lib | grep dtfft
          ls -lah /usr/local/include | grep dtfft
