name: Intel linux

on: [push]
jobs:
  host:
    name: Intel OneAPI
    runs-on: ubuntu-latest
    env:
      CC: "icx"
      CXX: "icpx"
      FC: "ifx"
      DTFFT_ENABLE_LOG: "1"
    steps:
      - name: Get Requirements
        run: |
          sudo echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -y
          sudo apt install -y intel-oneapi-base-toolkit intel-oneapi-hpc-toolkit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDTFFT_BUILD_TESTS=on \
            -DDTFFT_ENABLE_PERSISTENT_COMM=on \
            -DDTFFT_BUILD_SHARED=on \
            -DDTFFT_WITH_MKL=on \
            -DDTFFT_USE_MPI=on \
            -DDTFFT_BUILD_C_CXX_API=on
          cmake --build build
      - name: Test
        run: |
          source /opt/intel/oneapi/setvars.sh
          ctest --test-dir build --output-on-failure
      - name: Install
        run: sudo cmake --install build
      - name: Test install
        working-directory: ./tests/install
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build -S . -Ddtfft_DIR=/usr/local/lib/cmake/dtfft/
          cmake --build build
  host_static:
    name: Intel OneAPI
    runs-on: ubuntu-latest
    env:
      CC: "icx"
      CXX: "icpx"
      FC: "ifx"
      DTFFT_ENABLE_LOG: "1"
    steps:
      - name: Get Requirements
        run: |
          sudo echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -y
          sudo apt install -y intel-oneapi-base-toolkit intel-oneapi-hpc-toolkit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDTFFT_BUILD_TESTS=on \
            -DDTFFT_BUILD_SHARED=OFF \
            -DDTFFT_USE_MPI=on \
            -DDTFFT_BUILD_C_CXX_API=on
          cmake --build build
      - name: Test
        run: |
          source /opt/intel/oneapi/setvars.sh
          ctest --test-dir build --output-on-failure
      - name: Install
        run: sudo cmake --install build
      - name: Test install
        working-directory: ./tests/install
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build -S . -Ddtfft_DIR=/usr/local/lib/cmake/dtfft/
          cmake --build build

  cuda:
    name: Intel OneAPI + CUDA
    runs-on: ubuntu-latest
    env:
      CC: "icx"
      CXX: "icpx"
      FC: "ifx"
      DTFFT_ENABLE_LOG: "1"
    steps:
      - name: Get Requirements
        run: |
          sudo echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -y
          sudo apt install -y intel-oneapi-base-toolkit intel-oneapi-hpc-toolkit

          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
          sudo mv cuda-ubuntu2404.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda-repo-ubuntu2404-12-8-local_12.8.0-570.86.10-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2404-12-8-local_12.8.0-570.86.10-1_amd64.deb
          sudo cp /var/cuda-repo-ubuntu2404-12-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get -y install cuda-toolkit-12-8
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDTFFT_BUILD_TESTS=on \
            -DDTFFT_ENABLE_PERSISTENT_COMM=on \
            -DDTFFT_BUILD_SHARED=OFF \
            -DDTFFT_WITH_MKL=on \
            -DDTFFT_USE_MPI=on \
            -DDTFFT_BUILD_C_CXX_API=on \
            -DDTFFT_WITH_CUFFT=on
          cmake --build build
      - name: Test
        run: |
          source /opt/intel/oneapi/setvars.sh
          ctest --test-dir build --output-on-failure
      - name: Install
        run: sudo cmake --install build
      - name: Test install
        working-directory: ./tests/install
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build -S . -Ddtfft_DIR=/usr/local/lib/cmake/dtfft/
          cmake --build build