name: dtfft workflow

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Requirements
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get -y install gfortran-10
          sudo apt-get install libopenmpi-dev openmpi-bin
          sudo apt-get install libfftw3-dev
          export OMPI_FC=gfortran-10
          export OMPI_CC=gcc-10
          export OMPI_CXX=g++-10
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Build Directory
        run: mkdir build
      - name: Setup and run tests
        working-directory: ./build
        run: |
          cmake -DCMAKE_C_COMPILER=gcc-10 \
            -DCMAKE_CXX_COMPILER=g++-10 \
            -DCMAKE_Fortran_COMPILER=gfortran-10 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDTFFT_RUNNING_CICD=on \
            -DDTFFT_WITH_FFTW=on \
            -DDTFFT_BUILD_C_CXX_API=on ..
          make
          ls -lah /home/runner/work/dtFFT/dtFFT/build/CMakeFiles/dtfft.dir/src/
          # make install
          # ls -lah /usr/local/lib | grep dtfft
          # ls -lah /usr/local/include | grep dtfft
          CTEST_OUTPUT_ON_FAILURE=1 make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}